// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// AccountSettingService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewAccountSettingService] method instead.
type AccountSettingService struct {
	Options []option.RequestOption
}

// NewAccountSettingService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewAccountSettingService(opts ...option.RequestOption) (r *AccountSettingService) {
	r = &AccountSettingService{}
	r.Options = opts
	return
}

// Returns all effective settings for the account, including values inherited from its organization, platform, and system defaults.
//
// Parameters:
//
//	ctx: Context for the request.
//	accountID: The ID of the account.
//	params: AccountSettingGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*AccountSettingsResponse: OK
//
// Example:
//
//	accountSetting, err := client.AccountSettings.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountSettingGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(accountSetting)
func (r *AccountSettingService) Get(ctx context.Context, accountID string, params AccountSettingGetParams, opts ...option.RequestOption) (res *AccountSettingsResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if accountID == "" {
		err = errors.New("missing required account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/account_settings/%s", url.PathEscape(accountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type AccountSettingsResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType AccountSettingsResponseResponseType `json:"response_type" api:"required"`
	Data         AccountSettings                     `json:"data" api:"required"`
	JSON         accountSettingsResponseJSON         `json:"-"`
}

// accountSettingsResponseJSON contains the JSON metadata for the struct [AccountSettingsResponse]
type accountSettingsResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *AccountSettingsResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountSettingsResponseJSON) RawJSON() string {
	return r.raw
}

type AccountSettingsResponseResponseType string

const (
	AccountSettingsResponseResponseTypeObject AccountSettingsResponseResponseType = "object"
	AccountSettingsResponseResponseTypeArray  AccountSettingsResponseResponseType = "array"
	AccountSettingsResponseResponseTypeError  AccountSettingsResponseResponseType = "error"
	AccountSettingsResponseResponseTypeNone   AccountSettingsResponseResponseType = "none"
)

func (r AccountSettingsResponseResponseType) IsKnown() bool {
	switch r {
	case AccountSettingsResponseResponseTypeObject, AccountSettingsResponseResponseTypeArray, AccountSettingsResponseResponseTypeError, AccountSettingsResponseResponseTypeNone:
		return true
	}
	return false
}

type AccountSettings struct {
	Charges           ChargeSettings              `json:"charges" api:"required"`
	Payouts           PayoutSettings              `json:"payouts" api:"required"`
	StatementSettings AccountStatementSettings    `json:"statement_settings" api:"required"`
	PaymentTypes      AccountPaymentTypeSettings  `json:"payment_types" api:"required"`
	CustomerTypes     AccountCustomerTypeSettings `json:"customer_types" api:"required"`
	ConsentTypes      AccountConsentSettings      `json:"consent_types" api:"required"`
	Configuration     AccountPolicyControls       `json:"configuration" api:"required"`
	JSON              accountSettingsJSON         `json:"-"`
}

// accountSettingsJSON contains the JSON metadata for the struct [AccountSettings]
type accountSettingsJSON struct {
	Charges           apijson.Field
	Payouts           apijson.Field
	StatementSettings apijson.Field
	PaymentTypes      apijson.Field
	CustomerTypes     apijson.Field
	ConsentTypes      apijson.Field
	Configuration     apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *AccountSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountSettingsJSON) RawJSON() string {
	return r.raw
}

type ChargeSettings struct {
	// Maximum amount in cents for one charge.
	MaxAmount int64 `json:"max_amount" api:"required"`
	// Monthly charge amount limit in cents.
	MonthlyAmount int64 `json:"monthly_amount" api:"required"`
	// Daily charge amount limit in cents.
	DailyAmount int64 `json:"daily_amount" api:"required"`
	// Maximum number of charges per calendar month.
	MonthlyCount int64 `json:"monthly_count" api:"required"`
	// Funding schedule applied to charges.
	FundingTime string `json:"funding_time" api:"nullable"`
	// ID of the linked bank account used for charge settlement.
	LinkedBankAccountID string             `json:"linked_bank_account_id" api:"nullable"`
	JSON                chargeSettingsJSON `json:"-"`
}

// chargeSettingsJSON contains the JSON metadata for the struct [ChargeSettings]
type chargeSettingsJSON struct {
	MaxAmount           apijson.Field
	MonthlyAmount       apijson.Field
	DailyAmount         apijson.Field
	MonthlyCount        apijson.Field
	FundingTime         apijson.Field
	LinkedBankAccountID apijson.Field
	raw                 string
	ExtraFields         map[string]apijson.Field
}

func (r *ChargeSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r chargeSettingsJSON) RawJSON() string {
	return r.raw
}

type PayoutSettings struct {
	// Maximum amount in cents for one payout.
	MaxAmount int64 `json:"max_amount" api:"required"`
	// Monthly payout amount limit in cents.
	MonthlyAmount int64 `json:"monthly_amount" api:"required"`
	// Daily payout amount limit in cents.
	DailyAmount int64 `json:"daily_amount" api:"required"`
	// Maximum number of payouts per calendar month.
	MonthlyCount int64 `json:"monthly_count" api:"required"`
	// Funding schedule applied to payouts.
	FundingTime string `json:"funding_time" api:"nullable"`
	// ID of the linked bank account used for payout settlement.
	LinkedBankAccountID string             `json:"linked_bank_account_id" api:"nullable"`
	JSON                payoutSettingsJSON `json:"-"`
}

// payoutSettingsJSON contains the JSON metadata for the struct [PayoutSettings]
type payoutSettingsJSON struct {
	MaxAmount           apijson.Field
	MonthlyAmount       apijson.Field
	DailyAmount         apijson.Field
	MonthlyCount        apijson.Field
	FundingTime         apijson.Field
	LinkedBankAccountID apijson.Field
	raw                 string
	ExtraFields         map[string]apijson.Field
}

func (r *PayoutSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payoutSettingsJSON) RawJSON() string {
	return r.raw
}

type AccountStatementSettings struct {
	// Company name used in statement records.
	CompanyName string `json:"company_name" api:"nullable"`
	// Company identifier used in ACH records.
	CompanyID string `json:"company_id" api:"nullable"`
	// Default descriptor for account payments.
	DefaultDescriptor string                       `json:"default_descriptor" api:"nullable"`
	JSON              accountStatementSettingsJSON `json:"-"`
}

// accountStatementSettingsJSON contains the JSON metadata for the struct [AccountStatementSettings]
type accountStatementSettingsJSON struct {
	CompanyName       apijson.Field
	CompanyID         apijson.Field
	DefaultDescriptor apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *AccountStatementSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountStatementSettingsJSON) RawJSON() string {
	return r.raw
}

type AccountPaymentTypeSettings struct {
	// Status of charge support for the account.
	Charges AccountPaymentTypeSettingsCharges `json:"charges" api:"required"`
	// Status of payout support for the account.
	Payouts AccountPaymentTypeSettingsPayouts `json:"payouts" api:"required"`
	JSON    accountPaymentTypeSettingsJSON    `json:"-"`
}

// accountPaymentTypeSettingsJSON contains the JSON metadata for the struct [AccountPaymentTypeSettings]
type accountPaymentTypeSettingsJSON struct {
	Charges     apijson.Field
	Payouts     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AccountPaymentTypeSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountPaymentTypeSettingsJSON) RawJSON() string {
	return r.raw
}

type AccountPaymentTypeSettingsCharges string

const (
	AccountPaymentTypeSettingsChargesActive   AccountPaymentTypeSettingsCharges = "active"
	AccountPaymentTypeSettingsChargesInactive AccountPaymentTypeSettingsCharges = "inactive"
)

func (r AccountPaymentTypeSettingsCharges) IsKnown() bool {
	switch r {
	case AccountPaymentTypeSettingsChargesActive, AccountPaymentTypeSettingsChargesInactive:
		return true
	}
	return false
}

type AccountPaymentTypeSettingsPayouts string

const (
	AccountPaymentTypeSettingsPayoutsActive   AccountPaymentTypeSettingsPayouts = "active"
	AccountPaymentTypeSettingsPayoutsInactive AccountPaymentTypeSettingsPayouts = "inactive"
)

func (r AccountPaymentTypeSettingsPayouts) IsKnown() bool {
	switch r {
	case AccountPaymentTypeSettingsPayoutsActive, AccountPaymentTypeSettingsPayoutsInactive:
		return true
	}
	return false
}

type AccountCustomerTypeSettings struct {
	// Status of individual-customer support for the account.
	Individuals AccountCustomerTypeSettingsIndividuals `json:"individuals" api:"required"`
	// Status of business-customer support for the account.
	Businesses AccountCustomerTypeSettingsBusinesses `json:"businesses" api:"required"`
	JSON       accountCustomerTypeSettingsJSON       `json:"-"`
}

// accountCustomerTypeSettingsJSON contains the JSON metadata for the struct [AccountCustomerTypeSettings]
type accountCustomerTypeSettingsJSON struct {
	Individuals apijson.Field
	Businesses  apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AccountCustomerTypeSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountCustomerTypeSettingsJSON) RawJSON() string {
	return r.raw
}

type AccountCustomerTypeSettingsIndividuals string

const (
	AccountCustomerTypeSettingsIndividualsActive   AccountCustomerTypeSettingsIndividuals = "active"
	AccountCustomerTypeSettingsIndividualsInactive AccountCustomerTypeSettingsIndividuals = "inactive"
)

func (r AccountCustomerTypeSettingsIndividuals) IsKnown() bool {
	switch r {
	case AccountCustomerTypeSettingsIndividualsActive, AccountCustomerTypeSettingsIndividualsInactive:
		return true
	}
	return false
}

type AccountCustomerTypeSettingsBusinesses string

const (
	AccountCustomerTypeSettingsBusinessesActive   AccountCustomerTypeSettingsBusinesses = "active"
	AccountCustomerTypeSettingsBusinessesInactive AccountCustomerTypeSettingsBusinesses = "inactive"
)

func (r AccountCustomerTypeSettingsBusinesses) IsKnown() bool {
	switch r {
	case AccountCustomerTypeSettingsBusinessesActive, AccountCustomerTypeSettingsBusinessesInactive:
		return true
	}
	return false
}

type AccountConsentSettings struct {
	// Status of internet authorization support for the account.
	Internet AccountConsentSettingsInternet `json:"internet" api:"required"`
	// Status of signed-agreement authorization support for the account.
	SignedAgreement AccountConsentSettingsSignedAgreement `json:"signed_agreement" api:"required"`
	JSON            accountConsentSettingsJSON            `json:"-"`
}

// accountConsentSettingsJSON contains the JSON metadata for the struct [AccountConsentSettings]
type accountConsentSettingsJSON struct {
	Internet        apijson.Field
	SignedAgreement apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *AccountConsentSettings) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountConsentSettingsJSON) RawJSON() string {
	return r.raw
}

type AccountConsentSettingsInternet string

const (
	AccountConsentSettingsInternetActive   AccountConsentSettingsInternet = "active"
	AccountConsentSettingsInternetInactive AccountConsentSettingsInternet = "inactive"
)

func (r AccountConsentSettingsInternet) IsKnown() bool {
	switch r {
	case AccountConsentSettingsInternetActive, AccountConsentSettingsInternetInactive:
		return true
	}
	return false
}

type AccountConsentSettingsSignedAgreement string

const (
	AccountConsentSettingsSignedAgreementActive   AccountConsentSettingsSignedAgreement = "active"
	AccountConsentSettingsSignedAgreementInactive AccountConsentSettingsSignedAgreement = "inactive"
)

func (r AccountConsentSettingsSignedAgreement) IsKnown() bool {
	switch r {
	case AccountConsentSettingsSignedAgreementActive, AccountConsentSettingsSignedAgreementInactive:
		return true
	}
	return false
}

type AccountPolicyControls struct {
	// Whether the account can retrieve unmasked sensitive fields.
	AllowDataUnmask bool `json:"allow_data_unmask" api:"required"`
	// Whether multiple customers can share one email address.
	AllowDuplicateEmail bool `json:"allow_duplicate_email" api:"required"`
	// Whether customer identity verification can be skipped.
	AllowCustomerIdentitySkip bool `json:"allow_customer_identity_skip" api:"required"`
	// Whether paykey verification can be skipped.
	AllowPaykeyVerificationSkip bool                      `json:"allow_paykey_verification_skip" api:"required"`
	JSON                        accountPolicyControlsJSON `json:"-"`
}

// accountPolicyControlsJSON contains the JSON metadata for the struct [AccountPolicyControls]
type accountPolicyControlsJSON struct {
	AllowDataUnmask             apijson.Field
	AllowDuplicateEmail         apijson.Field
	AllowCustomerIdentitySkip   apijson.Field
	AllowPaykeyVerificationSkip apijson.Field
	raw                         string
	ExtraFields                 map[string]apijson.Field
}

func (r *AccountPolicyControls) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountPolicyControlsJSON) RawJSON() string {
	return r.raw
}

type AccountSettingGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}
