// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// CapabilityRequestService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewCapabilityRequestService] method instead.
type CapabilityRequestService struct {
	Options []option.RequestOption
}

// NewCapabilityRequestService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewCapabilityRequestService(opts ...option.RequestOption) (r *CapabilityRequestService) {
	r = &CapabilityRequestService{}
	r.Options = opts
	return
}

// Creates one or more capability requests for an account and returns the resulting requests.
//
// Parameters:
//
//	ctx: Context for the request.
//	accountID: The ID of the account.
//	body: CapabilityRequestNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*CapabilityRequestList: Created
//
// Example:
//
//	capabilityRequest, err := client.CapabilityRequests.New(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CapabilityRequestNewParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(capabilityRequest)
func (r *CapabilityRequestService) New(ctx context.Context, accountID string, body CapabilityRequestNewParams, opts ...option.RequestOption) (res *CapabilityRequestList, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if accountID == "" {
		err = errors.New("missing required account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/accounts/%s/capability_requests", url.PathEscape(accountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Returns a paginated list of capability requests for an account. Filter the list by capability type, category, or status.
//
// Parameters:
//
//	ctx: Context for the request.
//	accountID: The ID of the account.
//	query: CapabilityRequestListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*CapabilityRequestList: OK
//
// Example:
//
//	capabilityRequest, err := client.CapabilityRequests.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CapabilityRequestListParams{
//		PageNumber: sdk.F[int64](1),
//		PageSize:   sdk.F[int64](100),
//		SortBy:     sdk.F[string]("id"),
//		SortOrder:  sdk.F[sdk.CapabilityRequestListParamsSortOrder](sdk.CapabilityRequestListParamsSortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(capabilityRequest)
func (r *CapabilityRequestService) List(ctx context.Context, accountID string, query CapabilityRequestListParams, opts ...option.RequestOption) (res *CapabilityRequestList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if accountID == "" {
		err = errors.New("missing required account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/accounts/%s/capability_requests", url.PathEscape(accountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

type CapabilityRequestList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType CapabilityRequestListResponseType `json:"response_type" api:"required"`
	// Capability requests returned for this page.
	Data []CapabilityRequest       `json:"data" api:"required"`
	JSON capabilityRequestListJSON `json:"-"`
}

// capabilityRequestListJSON contains the JSON metadata for the struct [CapabilityRequestList]
type capabilityRequestListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *CapabilityRequestList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r capabilityRequestListJSON) RawJSON() string {
	return r.raw
}

type CapabilityRequestListResponseType string

const (
	CapabilityRequestListResponseTypeObject CapabilityRequestListResponseType = "object"
	CapabilityRequestListResponseTypeArray  CapabilityRequestListResponseType = "array"
	CapabilityRequestListResponseTypeError  CapabilityRequestListResponseType = "error"
	CapabilityRequestListResponseTypeNone   CapabilityRequestListResponseType = "none"
)

func (r CapabilityRequestListResponseType) IsKnown() bool {
	switch r {
	case CapabilityRequestListResponseTypeObject, CapabilityRequestListResponseTypeArray, CapabilityRequestListResponseTypeError, CapabilityRequestListResponseTypeNone:
		return true
	}
	return false
}

type CapabilityRequest struct {
	// Straddle's unique ID for the capability request.
	ID string `json:"id" api:"required" format:"uuid"`
	// ID of the account associated with the capability request.
	AccountID string `json:"account_id" api:"required" format:"uuid"`
	// Capability type requested within the category.
	Type CapabilityRequestType `json:"type" api:"required"`
	// Groups the requested capability. `payment_type` covers `charges` and `payouts`.
	// `customer_type` covers `individuals` and `businesses`. `consent_type` covers
	// `signed_agreement` and `internet` authorization.
	Category CapabilityRequestCategory `json:"category" api:"required"`
	// Status of the capability request.
	Status CapabilityRequestStatus `json:"status" api:"required"`
	// Date and time when Straddle created the capability request.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Date and time of the most recent capability request update.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Whether the request enables or disables the capability.
	Enable bool `json:"enable" api:"required"`
	// Limits and other settings requested for the capability.
	Settings map[string]interface{} `json:"settings" api:"nullable"`
	JSON     capabilityRequestJSON  `json:"-"`
}

// capabilityRequestJSON contains the JSON metadata for the struct [CapabilityRequest]
type capabilityRequestJSON struct {
	ID          apijson.Field
	AccountID   apijson.Field
	Type        apijson.Field
	Category    apijson.Field
	Status      apijson.Field
	CreatedAt   apijson.Field
	UpdatedAt   apijson.Field
	Enable      apijson.Field
	Settings    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CapabilityRequest) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r capabilityRequestJSON) RawJSON() string {
	return r.raw
}

type CapabilityRequestType string

const (
	CapabilityRequestTypeCharges         CapabilityRequestType = "charges"
	CapabilityRequestTypePayouts         CapabilityRequestType = "payouts"
	CapabilityRequestTypeIndividuals     CapabilityRequestType = "individuals"
	CapabilityRequestTypeBusinesses      CapabilityRequestType = "businesses"
	CapabilityRequestTypeSignedAgreement CapabilityRequestType = "signed_agreement"
	CapabilityRequestTypeInternet        CapabilityRequestType = "internet"
)

func (r CapabilityRequestType) IsKnown() bool {
	switch r {
	case CapabilityRequestTypeCharges, CapabilityRequestTypePayouts, CapabilityRequestTypeIndividuals, CapabilityRequestTypeBusinesses, CapabilityRequestTypeSignedAgreement, CapabilityRequestTypeInternet:
		return true
	}
	return false
}

type CapabilityRequestCategory string

const (
	CapabilityRequestCategoryPaymentType  CapabilityRequestCategory = "payment_type"
	CapabilityRequestCategoryCustomerType CapabilityRequestCategory = "customer_type"
	CapabilityRequestCategoryConsentType  CapabilityRequestCategory = "consent_type"
)

func (r CapabilityRequestCategory) IsKnown() bool {
	switch r {
	case CapabilityRequestCategoryPaymentType, CapabilityRequestCategoryCustomerType, CapabilityRequestCategoryConsentType:
		return true
	}
	return false
}

type CapabilityRequestStatus string

const (
	CapabilityRequestStatusActive    CapabilityRequestStatus = "active"
	CapabilityRequestStatusInactive  CapabilityRequestStatus = "inactive"
	CapabilityRequestStatusInReview  CapabilityRequestStatus = "in_review"
	CapabilityRequestStatusRejected  CapabilityRequestStatus = "rejected"
	CapabilityRequestStatusApproved  CapabilityRequestStatus = "approved"
	CapabilityRequestStatusReviewing CapabilityRequestStatus = "reviewing"
)

func (r CapabilityRequestStatus) IsKnown() bool {
	switch r {
	case CapabilityRequestStatusActive, CapabilityRequestStatusInactive, CapabilityRequestStatusInReview, CapabilityRequestStatusRejected, CapabilityRequestStatusApproved, CapabilityRequestStatusReviewing:
		return true
	}
	return false
}

type CapabilityRequestNewParams struct {
	// Request to enable or disable payments from businesses.
	Businesses param.Field[CapabilityRequestNewParamsBusinesses] `json:"businesses"`
	// Requested charge capability and limits.
	Charges param.Field[CapabilityRequestNewParamsCharges] `json:"charges"`
	// Request to enable or disable payments from individuals.
	Individuals param.Field[CapabilityRequestNewParamsIndividuals] `json:"individuals"`
	// Request to enable or disable internet and mobile payment authorization.
	Internet param.Field[CapabilityRequestNewParamsInternet] `json:"internet"`
	// Requested payout capability and limits.
	Payouts param.Field[CapabilityRequestNewParamsPayouts] `json:"payouts"`
	// Request to enable or disable signed-agreement payment authorization.
	SignedAgreement param.Field[CapabilityRequestNewParamsSignedAgreement] `json:"signed_agreement"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

func (r CapabilityRequestNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestNewParamsCharges struct {
	// Daily charge amount limit in cents.
	DailyAmount param.Field[float64] `json:"daily_amount" api:"required"`
	// Whether to enable or disable charges for the account.
	Enable param.Field[bool] `json:"enable" api:"required"`
	// Maximum amount in cents for one charge.
	MaxAmount param.Field[float64] `json:"max_amount" api:"required"`
	// Monthly charge amount limit in cents.
	MonthlyAmount param.Field[float64] `json:"monthly_amount" api:"required"`
	// Maximum number of charges per calendar month.
	MonthlyCount param.Field[int64] `json:"monthly_count" api:"required"`
}

func (r CapabilityRequestNewParamsCharges) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestNewParamsPayouts struct {
	// Daily payout amount limit in cents.
	DailyAmount param.Field[float64] `json:"daily_amount" api:"required"`
	// Whether to enable or disable payouts for the account.
	Enable param.Field[bool] `json:"enable" api:"required"`
	// Maximum amount in cents for one payout.
	MaxAmount param.Field[float64] `json:"max_amount" api:"required"`
	// Monthly payout amount limit in cents.
	MonthlyAmount param.Field[float64] `json:"monthly_amount" api:"required"`
	// Maximum number of payouts per calendar month.
	MonthlyCount param.Field[int64] `json:"monthly_count" api:"required"`
}

func (r CapabilityRequestNewParamsPayouts) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestNewParamsInternet struct {
	// Whether the request enables or disables the capability.
	Enable param.Field[bool] `json:"enable" api:"required"`
}

func (r CapabilityRequestNewParamsInternet) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestNewParamsIndividuals struct {
	// Whether the request enables or disables the capability.
	Enable param.Field[bool] `json:"enable" api:"required"`
}

func (r CapabilityRequestNewParamsIndividuals) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestNewParamsBusinesses struct {
	// Whether the request enables or disables the capability.
	Enable param.Field[bool] `json:"enable" api:"required"`
}

func (r CapabilityRequestNewParamsBusinesses) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestNewParamsSignedAgreement struct {
	// Whether the request enables or disables the capability.
	Enable param.Field[bool] `json:"enable" api:"required"`
}

func (r CapabilityRequestNewParamsSignedAgreement) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CapabilityRequestListParams struct {
	// Capability category to return.
	Category param.Field[CapabilityRequestListParamsCategory] `query:"category"`
	// Page number. Defaults to `1`.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results per page. Defaults to `100`. Maximum `1000`.
	PageSize param.Field[int64] `query:"page_size"`
	// Field used to sort results. Defaults to `id`.
	SortBy param.Field[string] `query:"sort_by"`
	// Sort direction. Defaults to `asc`.
	SortOrder param.Field[CapabilityRequestListParamsSortOrder] `query:"sort_order"`
	// Capability request status to return.
	Status param.Field[CapabilityRequestListParamsStatus] `query:"status"`
	// Capability type to return.
	Type param.Field[CapabilityRequestListParamsType] `query:"type"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

// URLQuery serializes [CapabilityRequestListParams]'s query parameters as `url.Values`.
func (r CapabilityRequestListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type CapabilityRequestListParamsType string

const (
	CapabilityRequestListParamsTypeCharges         CapabilityRequestListParamsType = "charges"
	CapabilityRequestListParamsTypePayouts         CapabilityRequestListParamsType = "payouts"
	CapabilityRequestListParamsTypeIndividuals     CapabilityRequestListParamsType = "individuals"
	CapabilityRequestListParamsTypeBusinesses      CapabilityRequestListParamsType = "businesses"
	CapabilityRequestListParamsTypeSignedAgreement CapabilityRequestListParamsType = "signed_agreement"
	CapabilityRequestListParamsTypeInternet        CapabilityRequestListParamsType = "internet"
)

func (r CapabilityRequestListParamsType) IsKnown() bool {
	switch r {
	case CapabilityRequestListParamsTypeCharges, CapabilityRequestListParamsTypePayouts, CapabilityRequestListParamsTypeIndividuals, CapabilityRequestListParamsTypeBusinesses, CapabilityRequestListParamsTypeSignedAgreement, CapabilityRequestListParamsTypeInternet:
		return true
	}
	return false
}

type CapabilityRequestListParamsCategory string

const (
	CapabilityRequestListParamsCategoryPaymentType  CapabilityRequestListParamsCategory = "payment_type"
	CapabilityRequestListParamsCategoryCustomerType CapabilityRequestListParamsCategory = "customer_type"
	CapabilityRequestListParamsCategoryConsentType  CapabilityRequestListParamsCategory = "consent_type"
)

func (r CapabilityRequestListParamsCategory) IsKnown() bool {
	switch r {
	case CapabilityRequestListParamsCategoryPaymentType, CapabilityRequestListParamsCategoryCustomerType, CapabilityRequestListParamsCategoryConsentType:
		return true
	}
	return false
}

type CapabilityRequestListParamsStatus string

const (
	CapabilityRequestListParamsStatusActive   CapabilityRequestListParamsStatus = "active"
	CapabilityRequestListParamsStatusInactive CapabilityRequestListParamsStatus = "inactive"
	CapabilityRequestListParamsStatusInReview CapabilityRequestListParamsStatus = "in_review"
	CapabilityRequestListParamsStatusRejected CapabilityRequestListParamsStatus = "rejected"
)

func (r CapabilityRequestListParamsStatus) IsKnown() bool {
	switch r {
	case CapabilityRequestListParamsStatusActive, CapabilityRequestListParamsStatusInactive, CapabilityRequestListParamsStatusInReview, CapabilityRequestListParamsStatusRejected:
		return true
	}
	return false
}

type CapabilityRequestListParamsSortOrder string

const (
	CapabilityRequestListParamsSortOrderAsc  CapabilityRequestListParamsSortOrder = "asc"
	CapabilityRequestListParamsSortOrderDesc CapabilityRequestListParamsSortOrder = "desc"
)

func (r CapabilityRequestListParamsSortOrder) IsKnown() bool {
	switch r {
	case CapabilityRequestListParamsSortOrderAsc, CapabilityRequestListParamsSortOrderDesc:
		return true
	}
	return false
}
