// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apiform"
	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// ChargeService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewChargeService] method instead.
type ChargeService struct {
	Options []option.RequestOption
}

// NewChargeService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewChargeService(opts ...option.RequestOption) (r *ChargeService) {
	r = &ChargeService{}
	r.Options = opts
	return
}

// Returns a charge by its unique identifier.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	params: ChargeGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: OK
//
// Example:
//
//	charge, err := client.Charges.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Get(ctx context.Context, id string, params ChargeGetParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Updates the description, amount, `payment_date`, or metadata. The charge must have a status of `created` or `on_hold`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: OK
//
// Example:
//
//	charge, err := client.Charges.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeUpdateParams{
//		Amount:      sdk.F[int64](10000),
//		Description: sdk.F[string]("Monthly subscription fee"),
//		PaymentDate: sdk.F[time.Time](time.Now()),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Update(ctx context.Context, id string, body ChargeUpdateParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Creates a charge against a customer's paykey. Straddle submits the charge for processing on `payment_date` unless the charge is on hold.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: ChargeNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: Created
//
// Example:
//
//	charge, err := client.Charges.New(context.Background(), sdk.ChargeNewParams{
//		Amount:      sdk.F[int64](10000),
//		Config:      sdk.F[sdk.ChargeConfigurationParam](sdk.ChargeConfigurationParam{}),
//		Currency:    sdk.F[string](""),
//		Description: sdk.F[string]("Monthly subscription fee"),
//		Device: sdk.F[sdk.PaymentDeviceParam](sdk.PaymentDeviceParam{
//			IPAddress: sdk.F[string]("192.168.1.1"),
//		}),
//		ExternalID:  sdk.F[string](""),
//		Paykey:      sdk.F[string](""),
//		PaymentDate: sdk.F[time.Time](time.Now()),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) New(ctx context.Context, body ChargeNewParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/charges"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Places a charge on hold to prevent submission for processing. The charge must have a status of `created` or `scheduled`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeHoldParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: OK
//
// Example:
//
//	charge, err := client.Charges.Hold(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeHoldParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Hold(ctx context.Context, id string, body ChargeHoldParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/hold", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Releases a charge from `on_hold` and returns it to `created` for submission on `payment_date`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeReleaseParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: OK
//
// Example:
//
//	charge, err := client.Charges.Release(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeReleaseParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Release(ctx context.Context, id string, body ChargeReleaseParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/release", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Cancels a charge. The charge must have a status of `created`, `scheduled`, or `on_hold`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeCancelParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: OK
//
// Example:
//
//	charge, err := client.Charges.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeCancelParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Cancel(ctx context.Context, id string, body ChargeCancelParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/cancel", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Return a charge with its sensitive fields unmasked.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	params: ChargeListUnmaskedParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*UnmaskedChargeResponse: OK
//
// Example:
//
//	charge, err := client.Charges.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeListUnmaskedParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) ListUnmasked(ctx context.Context, id string, params ChargeListUnmaskedParams, opts ...option.RequestOption) (res *UnmaskedChargeResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/unmask", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Creates a new charge from a failed, reversed, or cancelled charge. The request can override `description`, `external_id`, and `payment_date`. Other payment details come from the original charge.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeResubmitParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: Created
//
// Example:
//
//	charge, err := client.Charges.Resubmit(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeResubmitParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Resubmit(ctx context.Context, id string, body ChargeResubmitParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/resubmit", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Creates a payout to return funds from a paid charge to the customer's bank account. The payout is linked to the charge through `related_payments`. A charge can be refunded once, either fully or partially.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeRefundParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: Created
//
// Example:
//
//	charge, err := client.Charges.Refund(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeRefundParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) Refund(ctx context.Context, id string, body ChargeRefundParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/refund", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Uploads a proof-of-authorization document for a charge. A later upload adds another document and does not replace an existing one.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the charge.
//	body: ChargeUploadAuthorizationProofParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*ChargeResponse: Created
//
// Example:
//
//	charge, err := client.Charges.UploadAuthorizationProof(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeUploadAuthorizationProofParams{
//		File: sdk.F[io.Reader](strings.NewReader("")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(charge)
func (r *ChargeService) UploadAuthorizationProof(ctx context.Context, id string, body ChargeUploadAuthorizationProofParams, opts ...option.RequestOption) (res *ChargeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/charges/%s/authorization", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type ChargeResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType       `json:"response_type" api:"required"`
	Data         Charge             `json:"data" api:"required"`
	JSON         chargeResponseJSON `json:"-"`
}

// chargeResponseJSON contains the JSON metadata for the struct [ChargeResponse]
type chargeResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *ChargeResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r chargeResponseJSON) RawJSON() string {
	return r.raw
}

type UnmaskedChargeResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType               `json:"response_type" api:"required"`
	Data         UnmaskedCharge             `json:"data" api:"required"`
	JSON         unmaskedChargeResponseJSON `json:"-"`
}

// unmaskedChargeResponseJSON contains the JSON metadata for the struct [UnmaskedChargeResponse]
type unmaskedChargeResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedChargeResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedChargeResponseJSON) RawJSON() string {
	return r.raw
}

type PayoutResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType       `json:"response_type" api:"required"`
	Data         Payout             `json:"data" api:"required"`
	JSON         payoutResponseJSON `json:"-"`
}

// payoutResponseJSON contains the JSON metadata for the struct [PayoutResponse]
type payoutResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *PayoutResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payoutResponseJSON) RawJSON() string {
	return r.raw
}

type Charge struct {
	// Unique identifier for this charge.
	ID string `json:"id" api:"required" format:"uuid"`
	// The masked paykey token used for this charge.
	Paykey string `json:"paykey" api:"required"`
	// A human-readable description of the charge.
	Description string `json:"description" api:"required,nullable"`
	// Amount in cents.
	Amount int64 `json:"amount" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency string `json:"currency" api:"required"`
	// Date when Straddle submits the charge for processing.
	PaymentDate time.Time `json:"payment_date" api:"required" format:"date"`
	// How the customer authorized the charge. `internet` covers online and mobile
	// authorization. `signed` covers written or PDF-signed agreements.
	ConsentType ConsentType `json:"consent_type" api:"required"`
	// Device used when the customer authorized the charge.
	Device MaskedPaymentDevice `json:"device" api:"required"`
	// Your unique identifier for this charge, used to correlate with your internal
	// records.
	ExternalID string `json:"external_id" api:"required"`
	// Configuration options for the charge.
	Config ChargeConfiguration `json:"config" api:"required"`
	// Timestamp when this charge was created.
	CreatedAt time.Time `json:"created_at" api:"required,nullable" format:"date-time"`
	// Timestamp when this charge was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"required,nullable" format:"date-time"`
	// The current status of the charge.
	Status PaymentStatus `json:"status" api:"required"`
	// Reason, source, and message for the most recent charge status change.
	StatusDetails PaymentStatusDetails `json:"status_details" api:"required"`
	// Complete ordered history of all status changes for this charge.
	StatusHistory []PaymentStatusHistory `json:"status_history" api:"required"`
	// IDs of the funding events that included this charge.
	FundingIDs []string `json:"funding_ids" api:"required" format:"uuid"`
	// Trace identifiers from the payment network. Keys depend on the payment rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Whether an associated payout has refunded this charge.
	HasRefund bool `json:"has_refund" api:"required"`
	// Whether this charge resubmits an original charge.
	IsResubmit bool `json:"is_resubmit" api:"required"`
	// Whether this charge has been resubmitted.
	HasResubmit bool `json:"has_resubmit" api:"required"`
	// Payment rail used to process the charge.
	PaymentRail PaymentRail `json:"payment_rail"`
	// Information about the paykey used for the charge.
	PaykeyDetails PaykeyDetails `json:"paykey_details"`
	// Information about the customer associated with the charge.
	CustomerDetails CustomerDetails `json:"customer_details"`
	// Timestamp when this charge was submitted to the payment network. Null until
	// processed.
	ProcessedAt time.Time `json:"processed_at" api:"nullable" format:"date-time"`
	// Timestamp when funds were settled. Null until settlement is confirmed.
	EffectiveAt time.Time `json:"effective_at" api:"nullable" format:"date-time"`
	// Key-value metadata stored with this charge.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	// Related payments and their relationship to this charge.
	RelatedPayments []RelatedPayment `json:"related_payments" api:"nullable"`
	// Authorization documents for this charge, ordered by upload time.
	Documents []PaymentAuthorizationProof `json:"documents" api:"nullable"`
	JSON      chargeJSON                  `json:"-"`
}

// chargeJSON contains the JSON metadata for the struct [Charge]
type chargeJSON struct {
	ID              apijson.Field
	Paykey          apijson.Field
	Description     apijson.Field
	Amount          apijson.Field
	Currency        apijson.Field
	PaymentDate     apijson.Field
	ConsentType     apijson.Field
	Device          apijson.Field
	ExternalID      apijson.Field
	Config          apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	Status          apijson.Field
	StatusDetails   apijson.Field
	StatusHistory   apijson.Field
	FundingIDs      apijson.Field
	TraceIDs        apijson.Field
	HasRefund       apijson.Field
	IsResubmit      apijson.Field
	HasResubmit     apijson.Field
	PaymentRail     apijson.Field
	PaykeyDetails   apijson.Field
	CustomerDetails apijson.Field
	ProcessedAt     apijson.Field
	EffectiveAt     apijson.Field
	Metadata        apijson.Field
	RelatedPayments apijson.Field
	Documents       apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *Charge) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r chargeJSON) RawJSON() string {
	return r.raw
}

type UnmaskedCharge struct {
	// Unique identifier for this charge.
	ID string `json:"id" api:"required" format:"uuid"`
	// A human-readable description of the charge.
	Description string `json:"description" api:"required,nullable"`
	// Amount in cents.
	Amount int64 `json:"amount" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency string `json:"currency" api:"required"`
	// Date when Straddle submits the charge for processing.
	PaymentDate time.Time `json:"payment_date" api:"required" format:"date"`
	// How the customer authorized the charge. `internet` covers online and mobile
	// authorization. `signed` covers written or PDF-signed agreements.
	ConsentType ConsentType   `json:"consent_type" api:"required"`
	Device      PaymentDevice `json:"device" api:"required"`
	// Your unique identifier for this charge, used to correlate with your internal
	// records.
	ExternalID string              `json:"external_id" api:"required"`
	Config     ChargeConfiguration `json:"config" api:"required"`
	// Timestamp when this charge was created.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp when this charge was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// The current status of the `charge` or `payout`.
	Status        PaymentStatus        `json:"status" api:"required"`
	StatusDetails PaymentStatusDetails `json:"status_details" api:"required"`
	// Complete ordered history of all status changes for this charge.
	StatusHistory []PaymentStatusHistory `json:"status_history" api:"required"`
	// IDs of the funding events that included this charge.
	FundingIDs []string `json:"funding_ids" api:"required" format:"uuid"`
	// Unmasked paykey token used for this charge.
	Paykey string `json:"paykey" api:"required"`
	// Trace identifiers from the payment network. Keys depend on the payment rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Whether an associated payout has refunded this charge.
	HasRefund bool `json:"has_refund" api:"required"`
	// Whether this charge resubmits an original charge.
	IsResubmit bool `json:"is_resubmit" api:"required"`
	// Whether this charge has been resubmitted.
	HasResubmit bool `json:"has_resubmit" api:"required"`
	// The payment rail used for the charge or payout.
	PaymentRail   PaymentRail   `json:"payment_rail"`
	PaykeyDetails PaykeyDetails `json:"paykey_details"`
	// Information about the customer associated with the charge or payout.
	CustomerDetails CustomerDetails `json:"customer_details"`
	// Timestamp when this charge was submitted to the payment network. Null until
	// processed.
	ProcessedAt time.Time `json:"processed_at" api:"nullable" format:"date-time"`
	// Timestamp when funds were settled. Null until settlement is confirmed.
	EffectiveAt time.Time `json:"effective_at" api:"nullable" format:"date-time"`
	// Key-value metadata stored with this charge.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	// Related payments and their relationship to this charge.
	RelatedPayments []RelatedPayment `json:"related_payments" api:"nullable"`
	// Authorization documents for this charge, ordered by upload time.
	Documents []PaymentAuthorizationProof `json:"documents" api:"nullable"`
	JSON      unmaskedChargeJSON          `json:"-"`
}

// unmaskedChargeJSON contains the JSON metadata for the struct [UnmaskedCharge]
type unmaskedChargeJSON struct {
	ID              apijson.Field
	Description     apijson.Field
	Amount          apijson.Field
	Currency        apijson.Field
	PaymentDate     apijson.Field
	ConsentType     apijson.Field
	Device          apijson.Field
	ExternalID      apijson.Field
	Config          apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	Status          apijson.Field
	StatusDetails   apijson.Field
	StatusHistory   apijson.Field
	FundingIDs      apijson.Field
	Paykey          apijson.Field
	TraceIDs        apijson.Field
	HasRefund       apijson.Field
	IsResubmit      apijson.Field
	HasResubmit     apijson.Field
	PaymentRail     apijson.Field
	PaykeyDetails   apijson.Field
	CustomerDetails apijson.Field
	ProcessedAt     apijson.Field
	EffectiveAt     apijson.Field
	Metadata        apijson.Field
	RelatedPayments apijson.Field
	Documents       apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *UnmaskedCharge) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedChargeJSON) RawJSON() string {
	return r.raw
}

type Payout struct {
	// Unique identifier for this payout.
	ID string `json:"id" api:"required" format:"uuid"`
	// The masked paykey token used for this payout.
	Paykey string `json:"paykey" api:"required"`
	// A human-readable description of the payout.
	Description string `json:"description" api:"required,nullable"`
	// Amount in cents.
	Amount int64 `json:"amount" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency string `json:"currency" api:"required"`
	// Date when Straddle submits the payout for processing.
	PaymentDate time.Time `json:"payment_date" api:"required" format:"date"`
	// Device used when the customer authorized the payout.
	Device MaskedPaymentDevice `json:"device" api:"required"`
	// Your unique identifier for this payout, used to correlate with your internal
	// records.
	ExternalID string `json:"external_id" api:"required"`
	// Configuration for the payout.
	Config PayoutConfiguration `json:"config" api:"required"`
	// The current status of the payout.
	Status PaymentStatus `json:"status" api:"required"`
	// Reason, source, and message for the most recent payout status change.
	StatusDetails PaymentStatusDetails `json:"status_details" api:"required"`
	// Complete ordered history of all status changes for this payout.
	StatusHistory []PaymentStatusHistory `json:"status_history" api:"required"`
	// IDs of the funding events that included this payout.
	FundingIDs []string `json:"funding_ids" api:"required" format:"uuid"`
	// Trace identifiers from the payment network. Keys depend on the payment rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Whether this payout refunds an original charge.
	IsRefund bool `json:"is_refund" api:"required"`
	// Whether this payout resubmits an original payout.
	IsResubmit bool `json:"is_resubmit" api:"required"`
	// Whether this payout has been resubmitted.
	HasResubmit bool `json:"has_resubmit" api:"required"`
	// Payment rail used to process the payout.
	PaymentRail PaymentRail `json:"payment_rail"`
	// Information about the customer associated with the payout.
	CustomerDetails CustomerDetails `json:"customer_details"`
	// Information about the paykey used for the payout.
	PaykeyDetails PaykeyDetails `json:"paykey_details"`
	// Timestamp when this payout was created.
	CreatedAt time.Time `json:"created_at" api:"nullable" format:"date-time"`
	// Timestamp when this payout was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"nullable" format:"date-time"`
	// Timestamp when this payout was submitted to the payment network. Null until
	// processed.
	ProcessedAt time.Time `json:"processed_at" api:"nullable" format:"date-time"`
	// Timestamp when funds were settled. Null until settlement is confirmed.
	EffectiveAt time.Time `json:"effective_at" api:"nullable" format:"date-time"`
	// Key-value metadata stored with this payout.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	// Related payments and their relationship to this payout.
	RelatedPayments []RelatedPayment `json:"related_payments" api:"nullable"`
	// Authorization documents for this payout, ordered by upload time.
	Documents []PaymentAuthorizationProof `json:"documents" api:"nullable"`
	JSON      payoutJSON                  `json:"-"`
}

// payoutJSON contains the JSON metadata for the struct [Payout]
type payoutJSON struct {
	ID              apijson.Field
	Paykey          apijson.Field
	Description     apijson.Field
	Amount          apijson.Field
	Currency        apijson.Field
	PaymentDate     apijson.Field
	Device          apijson.Field
	ExternalID      apijson.Field
	Config          apijson.Field
	Status          apijson.Field
	StatusDetails   apijson.Field
	StatusHistory   apijson.Field
	FundingIDs      apijson.Field
	TraceIDs        apijson.Field
	IsRefund        apijson.Field
	IsResubmit      apijson.Field
	HasResubmit     apijson.Field
	PaymentRail     apijson.Field
	CustomerDetails apijson.Field
	PaykeyDetails   apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	ProcessedAt     apijson.Field
	EffectiveAt     apijson.Field
	Metadata        apijson.Field
	RelatedPayments apijson.Field
	Documents       apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *Payout) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payoutJSON) RawJSON() string {
	return r.raw
}

type PaymentRail string

const (
	PaymentRailACH PaymentRail = "ach"
)

func (r PaymentRail) IsKnown() bool {
	switch r {
	case PaymentRailACH:
		return true
	}
	return false
}

type PaykeyDetails struct {
	// Unique identifier for the paykey.
	ID string `json:"id" api:"required" format:"uuid"`
	// Unique identifier for the customer associated with the paykey.
	CustomerID string `json:"customer_id" api:"required" format:"uuid"`
	// Display label combining the bank name and masked account number.
	Label string `json:"label" api:"required"`
	// The most recent available balance in the smallest currency unit, if a balance
	// check was performed.
	Balance int64             `json:"balance" api:"nullable"`
	JSON    paykeyDetailsJSON `json:"-"`
}

// paykeyDetailsJSON contains the JSON metadata for the struct [PaykeyDetails]
type paykeyDetailsJSON struct {
	ID          apijson.Field
	CustomerID  apijson.Field
	Label       apijson.Field
	Balance     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PaykeyDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeyDetailsJSON) RawJSON() string {
	return r.raw
}

type CustomerDetails struct {
	// Unique identifier for the customer.
	ID string `json:"id" api:"required" format:"uuid"`
	// Customer's full name or business name.
	Name string `json:"name" api:"required"`
	// Whether the customer is an individual or a business.
	CustomerType CustomerType `json:"customer_type" api:"required"`
	// Customer's email address.
	Email string `json:"email" api:"required"`
	// Customer's phone number in E.164 format.
	Phone string              `json:"phone" api:"required"`
	JSON  customerDetailsJSON `json:"-"`
}

// customerDetailsJSON contains the JSON metadata for the struct [CustomerDetails]
type customerDetailsJSON struct {
	ID           apijson.Field
	Name         apijson.Field
	CustomerType apijson.Field
	Email        apijson.Field
	Phone        apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *CustomerDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerDetailsJSON) RawJSON() string {
	return r.raw
}

type ConsentType string

const (
	ConsentTypeInternet ConsentType = "internet"
	ConsentTypeSigned   ConsentType = "signed"
)

func (r ConsentType) IsKnown() bool {
	switch r {
	case ConsentTypeInternet, ConsentTypeSigned:
		return true
	}
	return false
}

type MaskedPaymentDevice struct {
	// Masked IP address of the device used when the customer authorized the charge or
	// payout.
	IPAddress string                  `json:"ip_address" api:"required"`
	JSON      maskedPaymentDeviceJSON `json:"-"`
}

// maskedPaymentDeviceJSON contains the JSON metadata for the struct [MaskedPaymentDevice]
type maskedPaymentDeviceJSON struct {
	IPAddress   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *MaskedPaymentDevice) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r maskedPaymentDeviceJSON) RawJSON() string {
	return r.raw
}

type ChargeConfiguration struct {
	// Balance check mode to use before processing the charge.
	BalanceCheck BalanceCheckMode `json:"balance_check" api:"required"`
	// Payment will simulate processing if not Standard.
	SandboxOutcome SimulatedPaymentOutcome `json:"sandbox_outcome"`
	// Whether to place the charge on hold automatically after creation.
	AutoHold bool `json:"auto_hold" api:"nullable"`
	// Reason for placing the charge on hold automatically.
	AutoHoldMessage string                  `json:"auto_hold_message" api:"nullable"`
	JSON            chargeConfigurationJSON `json:"-"`
}

// chargeConfigurationJSON contains the JSON metadata for the struct [ChargeConfiguration]
type chargeConfigurationJSON struct {
	BalanceCheck    apijson.Field
	SandboxOutcome  apijson.Field
	AutoHold        apijson.Field
	AutoHoldMessage apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *ChargeConfiguration) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r chargeConfigurationJSON) RawJSON() string {
	return r.raw
}

type ChargeConfigurationParam struct {
	// Balance check mode to use before processing the charge.
	BalanceCheck param.Field[BalanceCheckMode] `json:"balance_check" api:"required"`
	// Whether to place the charge on hold automatically after creation.
	AutoHold param.Field[bool] `json:"auto_hold"`
	// Reason for placing the charge on hold automatically.
	AutoHoldMessage param.Field[string] `json:"auto_hold_message"`
	// Payment will simulate processing if not Standard.
	SandboxOutcome param.Field[SimulatedPaymentOutcome] `json:"sandbox_outcome"`
}

func (r ChargeConfigurationParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PaymentStatus string

const (
	PaymentStatusCreated    PaymentStatus = "created"
	PaymentStatusScheduled  PaymentStatus = "scheduled"
	PaymentStatusFailed     PaymentStatus = "failed"
	PaymentStatusCancelled  PaymentStatus = "cancelled"
	PaymentStatusOnHold     PaymentStatus = "on_hold"
	PaymentStatusPending    PaymentStatus = "pending"
	PaymentStatusPaid       PaymentStatus = "paid"
	PaymentStatusReversed   PaymentStatus = "reversed"
	PaymentStatusValidating PaymentStatus = "validating"
)

func (r PaymentStatus) IsKnown() bool {
	switch r {
	case PaymentStatusCreated, PaymentStatusScheduled, PaymentStatusFailed, PaymentStatusCancelled, PaymentStatusOnHold, PaymentStatusPending, PaymentStatusPaid, PaymentStatusReversed, PaymentStatusValidating:
		return true
	}
	return false
}

type PaymentStatusHistory struct {
	// Machine-readable reason for the status.
	Reason PaymentStatusReason `json:"reason" api:"required"`
	// Source of the status change.
	Source PaymentStatusSource `json:"source" api:"required"`
	// Human-readable status description.
	Message string `json:"message" api:"required"`
	// Timestamp when the status changed.
	ChangedAt time.Time `json:"changed_at" api:"required" format:"date-time"`
	// The current status of the `charge` or `payout`.
	Status PaymentStatus `json:"status" api:"required"`
	// Status code, when available.
	Code string                   `json:"code" api:"nullable"`
	JSON paymentStatusHistoryJSON `json:"-"`
}

// paymentStatusHistoryJSON contains the JSON metadata for the struct [PaymentStatusHistory]
type paymentStatusHistoryJSON struct {
	Reason      apijson.Field
	Source      apijson.Field
	Message     apijson.Field
	ChangedAt   apijson.Field
	Status      apijson.Field
	Code        apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PaymentStatusHistory) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paymentStatusHistoryJSON) RawJSON() string {
	return r.raw
}

type RelatedPayment struct {
	// Unique identifier of the related payment.
	ID           string              `json:"id" api:"required" format:"uuid"`
	Relationship PaymentRelationship `json:"relationship" api:"required"`
	// The type of payment.
	PaymentType PaymentType        `json:"payment_type" api:"required"`
	JSON        relatedPaymentJSON `json:"-"`
}

// relatedPaymentJSON contains the JSON metadata for the struct [RelatedPayment]
type relatedPaymentJSON struct {
	ID           apijson.Field
	Relationship apijson.Field
	PaymentType  apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *RelatedPayment) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r relatedPaymentJSON) RawJSON() string {
	return r.raw
}

type PaymentAuthorizationProof struct {
	// Unique identifier for this document.
	DocumentID string `json:"document_id" api:"required" format:"uuid"`
	// The file name of this document as uploaded.
	DocumentName string              `json:"document_name" api:"required"`
	DocumentType PaymentDocumentType `json:"document_type" api:"required"`
	// The size of this document in bytes.
	DocumentSize int64 `json:"document_size" api:"required"`
	// The UTC timestamp when this document was uploaded.
	UploadedAt time.Time                     `json:"uploaded_at" api:"required" format:"date-time"`
	JSON       paymentAuthorizationProofJSON `json:"-"`
}

// paymentAuthorizationProofJSON contains the JSON metadata for the struct [PaymentAuthorizationProof]
type paymentAuthorizationProofJSON struct {
	DocumentID   apijson.Field
	DocumentName apijson.Field
	DocumentType apijson.Field
	DocumentSize apijson.Field
	UploadedAt   apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *PaymentAuthorizationProof) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paymentAuthorizationProofJSON) RawJSON() string {
	return r.raw
}

type PaymentDevice struct {
	// The IP address of the device used when the customer authorized the charge or
	// payout. Use `0.0.0.0` to represent an offline consent interaction.
	IPAddress string            `json:"ip_address" api:"required"`
	JSON      paymentDeviceJSON `json:"-"`
}

// paymentDeviceJSON contains the JSON metadata for the struct [PaymentDevice]
type paymentDeviceJSON struct {
	IPAddress   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PaymentDevice) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paymentDeviceJSON) RawJSON() string {
	return r.raw
}

type PaymentDeviceParam struct {
	// The IP address of the device used when the customer authorized the charge or
	// payout. Use `0.0.0.0` to represent an offline consent interaction.
	IPAddress param.Field[string] `json:"ip_address" api:"required"`
}

func (r PaymentDeviceParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutConfiguration struct {
	// Payment will simulate processing if not Standard.
	SandboxOutcome SimulatedPaymentOutcome `json:"sandbox_outcome"`
	// Whether to place the payout on hold automatically after creation.
	AutoHold bool `json:"auto_hold" api:"nullable"`
	// Reason for placing the payout on hold automatically.
	AutoHoldMessage string                  `json:"auto_hold_message" api:"nullable"`
	JSON            payoutConfigurationJSON `json:"-"`
}

// payoutConfigurationJSON contains the JSON metadata for the struct [PayoutConfiguration]
type payoutConfigurationJSON struct {
	SandboxOutcome  apijson.Field
	AutoHold        apijson.Field
	AutoHoldMessage apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *PayoutConfiguration) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r payoutConfigurationJSON) RawJSON() string {
	return r.raw
}

type PayoutConfigurationParam struct {
	// Whether to place the payout on hold automatically after creation.
	AutoHold param.Field[bool] `json:"auto_hold"`
	// Reason for placing the payout on hold automatically.
	AutoHoldMessage param.Field[string] `json:"auto_hold_message"`
	// Payment will simulate processing if not Standard.
	SandboxOutcome param.Field[SimulatedPaymentOutcome] `json:"sandbox_outcome"`
}

func (r PayoutConfigurationParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type BalanceCheckMode string

const (
	BalanceCheckModeRequired BalanceCheckMode = "required"
	BalanceCheckModeEnabled  BalanceCheckMode = "enabled"
	BalanceCheckModeDisabled BalanceCheckMode = "disabled"
)

func (r BalanceCheckMode) IsKnown() bool {
	switch r {
	case BalanceCheckModeRequired, BalanceCheckModeEnabled, BalanceCheckModeDisabled:
		return true
	}
	return false
}

type SimulatedPaymentOutcome string

const (
	SimulatedPaymentOutcomeStandard                  SimulatedPaymentOutcome = "standard"
	SimulatedPaymentOutcomePaid                      SimulatedPaymentOutcome = "paid"
	SimulatedPaymentOutcomeOnHoldDailyLimit          SimulatedPaymentOutcome = "on_hold_daily_limit"
	SimulatedPaymentOutcomeCancelledForFraudRisk     SimulatedPaymentOutcome = "cancelled_for_fraud_risk"
	SimulatedPaymentOutcomeCancelledForBalanceCheck  SimulatedPaymentOutcome = "cancelled_for_balance_check"
	SimulatedPaymentOutcomeFailedInsufficientFunds   SimulatedPaymentOutcome = "failed_insufficient_funds"
	SimulatedPaymentOutcomeReversedInsufficientFunds SimulatedPaymentOutcome = "reversed_insufficient_funds"
	SimulatedPaymentOutcomeFailedCustomerDispute     SimulatedPaymentOutcome = "failed_customer_dispute"
	SimulatedPaymentOutcomeReversedCustomerDispute   SimulatedPaymentOutcome = "reversed_customer_dispute"
	SimulatedPaymentOutcomeFailedClosedBankAccount   SimulatedPaymentOutcome = "failed_closed_bank_account"
	SimulatedPaymentOutcomeReversedClosedBankAccount SimulatedPaymentOutcome = "reversed_closed_bank_account"
	SimulatedPaymentOutcomeFailedNotAuthorized       SimulatedPaymentOutcome = "failed_not_authorized"
	SimulatedPaymentOutcomeReversedNotAuthorized     SimulatedPaymentOutcome = "reversed_not_authorized"
)

func (r SimulatedPaymentOutcome) IsKnown() bool {
	switch r {
	case SimulatedPaymentOutcomeStandard, SimulatedPaymentOutcomePaid, SimulatedPaymentOutcomeOnHoldDailyLimit, SimulatedPaymentOutcomeCancelledForFraudRisk, SimulatedPaymentOutcomeCancelledForBalanceCheck, SimulatedPaymentOutcomeFailedInsufficientFunds, SimulatedPaymentOutcomeReversedInsufficientFunds, SimulatedPaymentOutcomeFailedCustomerDispute, SimulatedPaymentOutcomeReversedCustomerDispute, SimulatedPaymentOutcomeFailedClosedBankAccount, SimulatedPaymentOutcomeReversedClosedBankAccount, SimulatedPaymentOutcomeFailedNotAuthorized, SimulatedPaymentOutcomeReversedNotAuthorized:
		return true
	}
	return false
}

type PaymentRelationship string

const (
	PaymentRelationshipOriginal PaymentRelationship = "original"
	PaymentRelationshipResubmit PaymentRelationship = "resubmit"
	PaymentRelationshipRefund   PaymentRelationship = "refund"
)

func (r PaymentRelationship) IsKnown() bool {
	switch r {
	case PaymentRelationshipOriginal, PaymentRelationshipResubmit, PaymentRelationshipRefund:
		return true
	}
	return false
}

type PaymentType string

const (
	PaymentTypeCharge PaymentType = "charge"
	PaymentTypePayout PaymentType = "payout"
)

func (r PaymentType) IsKnown() bool {
	switch r {
	case PaymentTypeCharge, PaymentTypePayout:
		return true
	}
	return false
}

type PaymentDocumentType string

const (
	PaymentDocumentTypePaymentAuthorization PaymentDocumentType = "payment_authorization"
)

func (r PaymentDocumentType) IsKnown() bool {
	switch r {
	case PaymentDocumentTypePaymentAuthorization:
		return true
	}
	return false
}

type ChargeGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type ChargeUpdateParams struct {
	// Amount in cents.
	Amount param.Field[int64] `json:"amount" api:"required"`
	// Updated description for the charge.
	Description param.Field[string] `json:"description" api:"required"`
	// New date for Straddle to submit the charge for processing.
	PaymentDate param.Field[time.Time] `json:"payment_date" api:"required" format:"date"`
	// Replacement metadata for the charge. Up to 20 user-defined string key-value
	// pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeNewParams struct {
	// Amount in cents.
	Amount param.Field[int64]                    `json:"amount" api:"required"`
	Config param.Field[ChargeConfigurationParam] `json:"config" api:"required"`
	// How the customer authorized the charge. `internet` covers online and mobile
	// authorization. `signed` covers written or PDF-signed agreements.
	ConsentType param.Field[ConsentType] `json:"consent_type" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency param.Field[string] `json:"currency" api:"required"`
	// Description shown on the customer's bank statement where supported.
	Description param.Field[string]             `json:"description" api:"required"`
	Device      param.Field[PaymentDeviceParam] `json:"device" api:"required"`
	// Your unique identifier for the charge. Must be unique across charges.
	ExternalID param.Field[string] `json:"external_id" api:"required"`
	// The paykey token that identifies the customer's bank account.
	Paykey param.Field[string] `json:"paykey" api:"required"`
	// Date when Straddle submits the charge for processing.
	PaymentDate param.Field[time.Time] `json:"payment_date" api:"required" format:"date"`
	// Up to 20 user-defined string key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeHoldParams struct {
	// Message explaining the charge status change.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeHoldParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeReleaseParams struct {
	// Message explaining the charge status change.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeReleaseParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeCancelParams struct {
	// Message explaining the charge status change.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeCancelParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeListUnmaskedParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type ChargeResubmitParams struct {
	// Description for the resubmitted charge. Defaults to the original description if
	// omitted.
	Description param.Field[string] `json:"description"`
	// Your unique identifier for the resubmitted charge. Defaults to a new value if
	// omitted.
	ExternalID param.Field[string] `json:"external_id"`
	// Date when Straddle submits the resubmitted charge for processing. Defaults to
	// today if omitted.
	PaymentDate param.Field[time.Time] `json:"payment_date" format:"date"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeResubmitParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeRefundParams struct {
	// Refund amount in cents. `null` refunds the full original amount. A value must be
	// greater than zero and no more than the original charge amount.
	Amount param.Field[int64] `json:"amount"`
	// Description for the refund payout. Defaults to a description that identifies the
	// original charge.
	Description param.Field[string] `json:"description"`
	// Your unique identifier for the refund. Defaults to a new value if omitted.
	ExternalID param.Field[string] `json:"external_id"`
	// User-defined string key-value pairs for the refund payout.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Date when Straddle submits the refund payout for processing. Defaults to today
	// if omitted.
	PaymentDate param.Field[time.Time] `json:"payment_date" format:"date"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeRefundParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type ChargeUploadAuthorizationProofParams struct {
	// The document file to upload as proof of authorization for this charge. Supported
	// file types are PDF (.pdf), PNG (.png), JPEG (.jpg, .jpeg), Word (.doc), and Word
	// (.docx), with a maximum file size of 10 MiB (10,485,760 bytes). Empty (0-byte)
	// files are rejected. Uploaded files are validated for matching file signatures
	// (magic bytes) and file extension agreement.
	File param.Field[io.Reader] `json:"File" api:"required" format:"binary"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r ChargeUploadAuthorizationProofParams) MarshalMultipart() (data []byte, contentType string, err error) {
	buf := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(buf)
	err = apiform.MarshalRoot(r, writer)
	if err != nil {
		writer.Close()
		return nil, "", err
	}
	err = writer.Close()
	if err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}
