// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"net/http"
	"os"
	"slices"
	"strings"

	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// Client creates a struct with services and top level methods that help with
// interacting with the Straddle API. You should not instantiate this client
// directly, and instead use the [NewClient] method instead.
type Client struct {
	Options            []option.RequestOption
	Accounts           *AccountService
	CapabilityRequests *CapabilityRequestService
	LinkedBankAccounts *LinkedBankAccountService
	Organizations      *OrganizationService
	Representatives    *RepresentativeService
	Bridge             *BridgeService
	Customers          *CustomerService
	Paykeys            *PaykeyService
	Charges            *ChargeService
	FundingEvents      *FundingEventService
	Payments           *PaymentService
	Payouts            *PayoutService
	AccountSettings    *AccountSettingService
	Webhooks           *WebhookService
}

// DefaultClientOptions read from the environment. This should be used to initialize
// new clients.
func DefaultClientOptions() []option.RequestOption {
	defaults := []option.RequestOption{option.WithHTTPClient(defaultHTTPClient()), option.WithEnvironmentStraddleApiServer()}
	if o, ok := os.LookupEnv("STRADDLE_BASE_URL"); ok {
		defaults = append(defaults, option.WithBaseURL(o))
	}
	if o, ok := os.LookupEnv("BEARER"); ok {
		defaults = append(defaults, option.WithBearer(o))
	}
	if o, ok := os.LookupEnv("STRADDLE_WEBHOOK_SECRET"); ok && o != "" {
		defaults = append(defaults, option.WithWebhookSecret(o))
	}
	if o, ok := os.LookupEnv("STRADDLE_CUSTOM_HEADERS"); ok {
		for _, line := range strings.Split(o, "\n") {
			colon := strings.Index(line, ":")
			if colon >= 0 {
				defaults = append(defaults, option.WithHeader(strings.TrimSpace(line[:colon]), strings.TrimSpace(line[colon+1:])))
			}
		}
	}
	return defaults
}

// NewClient generates a new client with the default option read from the
// environment. The option passed in as arguments are applied after these default
// arguments, and all option will be passed down to the services and requests that
// this client makes.
func NewClient(opts ...option.RequestOption) (r *Client) {
	opts = append(DefaultClientOptions(), opts...)

	r = &Client{Options: opts}

	r.Accounts = NewAccountService(opts...)
	r.CapabilityRequests = NewCapabilityRequestService(opts...)
	r.LinkedBankAccounts = NewLinkedBankAccountService(opts...)
	r.Organizations = NewOrganizationService(opts...)
	r.Representatives = NewRepresentativeService(opts...)
	r.Bridge = NewBridgeService(opts...)
	r.Customers = NewCustomerService(opts...)
	r.Paykeys = NewPaykeyService(opts...)
	r.Charges = NewChargeService(opts...)
	r.FundingEvents = NewFundingEventService(opts...)
	r.Payments = NewPaymentService(opts...)
	r.Payouts = NewPayoutService(opts...)
	r.AccountSettings = NewAccountSettingService(opts...)
	r.Webhooks = NewWebhookService(opts...)

	return
}

// Execute makes a request with the given context, method, URL, request params,
// response, and request options.
func (r *Client) Execute(ctx context.Context, method string, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	opts = slices.Concat(r.Options, opts)
	return requestconfig.ExecuteNewRequest(ctx, method, path, params, res, opts...)
}

// Get makes a GET request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Get(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodGet, path, params, res, opts...)
}

// Post makes a POST request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Post(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPost, path, params, res, opts...)
}

// Put makes a PUT request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Put(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPut, path, params, res, opts...)
}

// Patch makes a PATCH request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Patch(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodPatch, path, params, res, opts...)
}

// Delete makes a DELETE request with the given URL, params, and optionally
// deserializes to a response. See [Execute] documentation on the params and response.
func (r *Client) Delete(ctx context.Context, path string, params interface{}, res interface{}, opts ...option.RequestOption) error {
	return r.Execute(ctx, http.MethodDelete, path, params, res, opts...)
}
