// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// CustomerReviewService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewCustomerReviewService] method instead.
type CustomerReviewService struct {
	Options []option.RequestOption
}

// NewCustomerReviewService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewCustomerReviewService(opts ...option.RequestOption) (r *CustomerReviewService) {
	r = &CustomerReviewService{}
	r.Options = opts
	return
}

// Returns the results of a customer's identity and fraud review. The response includes decisions, risk and correlation scores, reason codes, watchlist matches, and network alerts.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the customer.
//	params: CustomerReviewListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*CustomerReviewResponse: OK
//
// Example:
//
//	review, err := client.Customers.Review.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerReviewListParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(review)
func (r *CustomerReviewService) List(ctx context.Context, id string, params CustomerReviewListParams, opts ...option.RequestOption) (res *CustomerReviewResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/customers/%s/review", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Updates the verification decision for a customer. The customer's current `status` must be `review`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the customer.
//	body: CustomerReviewSetVerificationDecisionParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*CustomerResponse: OK
//
// Example:
//
//	review, err := client.Customers.Review.SetVerificationDecision(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerReviewSetVerificationDecisionParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(review)
func (r *CustomerReviewService) SetVerificationDecision(ctx context.Context, id string, body CustomerReviewSetVerificationDecisionParams, opts ...option.RequestOption) (res *CustomerResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/customers/%s/review", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

type CustomerReviewResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType               `json:"response_type" api:"required"`
	Data         CustomerReview             `json:"data" api:"required"`
	JSON         customerReviewResponseJSON `json:"-"`
}

// customerReviewResponseJSON contains the JSON metadata for the struct [CustomerReviewResponse]
type customerReviewResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *CustomerReviewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerReviewResponseJSON) RawJSON() string {
	return r.raw
}

type CustomerReview struct {
	CustomerDetails Customer                     `json:"customer_details" api:"required"`
	IdentityDetails CustomerIdentityVerification `json:"identity_details"`
	JSON            customerReviewJSON           `json:"-"`
}

// customerReviewJSON contains the JSON metadata for the struct [CustomerReview]
type customerReviewJSON struct {
	CustomerDetails apijson.Field
	IdentityDetails apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *CustomerReview) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerReviewJSON) RawJSON() string {
	return r.raw
}

type CustomerIdentityVerification struct {
	// Unique identifier for the review.
	ReviewID string               `json:"review_id" api:"required" format:"uuid"`
	Decision VerificationDecision `json:"decision" api:"required"`
	// Results for each customer verification check, including decisions, risk scores,
	// and correlation scores.
	Breakdown CustomerIdentityVerificationBreakdown `json:"breakdown" api:"required"`
	// Timestamp of when the review was initiated.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp of the most recent update to the review.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Messages returned by the customer verification process.
	Messages      map[string]string                `json:"messages" api:"nullable"`
	NetworkAlerts IdentityVerificationAlerts       `json:"network_alerts"`
	WatchList     IdentityVerificationWatchlist    `json:"watch_list"`
	KYC           CustomerKYCVerification          `json:"kyc"`
	Reputation    ReputationCheck                  `json:"reputation"`
	JSON          customerIdentityVerificationJSON `json:"-"`
}

// customerIdentityVerificationJSON contains the JSON metadata for the struct [CustomerIdentityVerification]
type customerIdentityVerificationJSON struct {
	ReviewID      apijson.Field
	Decision      apijson.Field
	Breakdown     apijson.Field
	CreatedAt     apijson.Field
	UpdatedAt     apijson.Field
	Messages      apijson.Field
	NetworkAlerts apijson.Field
	WatchList     apijson.Field
	KYC           apijson.Field
	Reputation    apijson.Field
	raw           string
	ExtraFields   map[string]apijson.Field
}

func (r *CustomerIdentityVerification) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerIdentityVerificationJSON) RawJSON() string {
	return r.raw
}

type VerificationDecision string

const (
	VerificationDecisionAccept VerificationDecision = "accept"
	VerificationDecisionReject VerificationDecision = "reject"
	VerificationDecisionReview VerificationDecision = "review"
)

func (r VerificationDecision) IsKnown() bool {
	switch r {
	case VerificationDecisionAccept, VerificationDecisionReject, VerificationDecisionReview:
		return true
	}
	return false
}

type IdentityVerificationBreakdown struct {
	Decision VerificationDecision `json:"decision"`
	// List of specific result codes from the fraud and risk screening.
	Codes []string `json:"codes" api:"nullable"`
	// Predicts the inherent risk associated with the customer for a given module. A
	// higher score indicates a greater likelihood of fraud.
	RiskScore float64 `json:"risk_score" api:"nullable"`
	// Represents the strength of the correlation between provided and known
	// information. A higher score indicates a stronger correlation.
	CorrelationScore float64                           `json:"correlation_score" api:"nullable"`
	Correlation      CorrelationBucket                 `json:"correlation"`
	JSON             identityVerificationBreakdownJSON `json:"-"`
}

// identityVerificationBreakdownJSON contains the JSON metadata for the struct [IdentityVerificationBreakdown]
type identityVerificationBreakdownJSON struct {
	Decision         apijson.Field
	Codes            apijson.Field
	RiskScore        apijson.Field
	CorrelationScore apijson.Field
	Correlation      apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *IdentityVerificationBreakdown) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r identityVerificationBreakdownJSON) RawJSON() string {
	return r.raw
}

type IdentityVerificationAlerts struct {
	Decision VerificationDecision `json:"decision"`
	// List of specific result codes from the consortium alert screening.
	Codes []string `json:"codes" api:"nullable"`
	// Any alerts or flags raised during the consortium alert screening.
	Alerts []string                       `json:"alerts" api:"nullable"`
	JSON   identityVerificationAlertsJSON `json:"-"`
}

// identityVerificationAlertsJSON contains the JSON metadata for the struct [IdentityVerificationAlerts]
type identityVerificationAlertsJSON struct {
	Decision    apijson.Field
	Codes       apijson.Field
	Alerts      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *IdentityVerificationAlerts) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r identityVerificationAlertsJSON) RawJSON() string {
	return r.raw
}

type IdentityVerificationWatchlist struct {
	Decision VerificationDecision `json:"decision"`
	// Result codes from Straddle watchlist screening.
	Codes []string `json:"codes" api:"nullable"`
	// Names of watchlists with matches.
	Matched []string `json:"matched" api:"nullable"`
	// Details for matches found during watchlist screening.
	Matches []IdentityVerificationWatchlistMatch `json:"matches" api:"nullable"`
	JSON    identityVerificationWatchlistJSON    `json:"-"`
}

// identityVerificationWatchlistJSON contains the JSON metadata for the struct [IdentityVerificationWatchlist]
type identityVerificationWatchlistJSON struct {
	Decision    apijson.Field
	Codes       apijson.Field
	Matched     apijson.Field
	Matches     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *IdentityVerificationWatchlist) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r identityVerificationWatchlistJSON) RawJSON() string {
	return r.raw
}

type CustomerKYCVerification struct {
	// Results for each Know Your Customer (KYC) validation.
	Validations CustomerKYCVerificationValidations `json:"validations" api:"required"`
	Decision    VerificationDecision               `json:"decision"`
	// Result codes from Know Your Customer (KYC) screening.
	Codes []string                    `json:"codes" api:"nullable"`
	JSON  customerKYCVerificationJSON `json:"-"`
}

// customerKYCVerificationJSON contains the JSON metadata for the struct [CustomerKYCVerification]
type customerKYCVerificationJSON struct {
	Validations apijson.Field
	Decision    apijson.Field
	Codes       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CustomerKYCVerification) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerKYCVerificationJSON) RawJSON() string {
	return r.raw
}

type ReputationCheck struct {
	Decision VerificationDecision `json:"decision"`
	// Specific codes related to the Straddle reputation screening results.
	Codes []string `json:"codes" api:"nullable"`
	// Risk score produced by the reputation check.
	RiskScore float64             `json:"risk_score" api:"nullable"`
	Insights  ReputationInsights  `json:"insights"`
	JSON      reputationCheckJSON `json:"-"`
}

// reputationCheckJSON contains the JSON metadata for the struct [ReputationCheck]
type reputationCheckJSON struct {
	Decision    apijson.Field
	Codes       apijson.Field
	RiskScore   apijson.Field
	Insights    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *ReputationCheck) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r reputationCheckJSON) RawJSON() string {
	return r.raw
}

type CorrelationBucket string

const (
	CorrelationBucketLowConfidence  CorrelationBucket = "low_confidence"
	CorrelationBucketPotentialMatch CorrelationBucket = "potential_match"
	CorrelationBucketLikelyMatch    CorrelationBucket = "likely_match"
	CorrelationBucketHighConfidence CorrelationBucket = "high_confidence"
)

func (r CorrelationBucket) IsKnown() bool {
	switch r {
	case CorrelationBucketLowConfidence, CorrelationBucketPotentialMatch, CorrelationBucketLikelyMatch, CorrelationBucketHighConfidence:
		return true
	}
	return false
}

type IdentityVerificationWatchlistMatch struct {
	// Name of the watchlist that contains the matching record.
	ListName string `json:"list_name" api:"required"`
	// Source URLs associated with the match.
	URLs []string `json:"urls" api:"required"`
	// Customer fields that match the watchlist record.
	MatchFields []string                               `json:"match_fields" api:"required"`
	Correlation CorrelationBucket                      `json:"correlation" api:"required"`
	JSON        identityVerificationWatchlistMatchJSON `json:"-"`
}

// identityVerificationWatchlistMatchJSON contains the JSON metadata for the struct [IdentityVerificationWatchlistMatch]
type identityVerificationWatchlistMatchJSON struct {
	ListName    apijson.Field
	URLs        apijson.Field
	MatchFields apijson.Field
	Correlation apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *IdentityVerificationWatchlistMatch) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r identityVerificationWatchlistMatchJSON) RawJSON() string {
	return r.raw
}

type ReputationInsights struct {
	// Number of fraudulent ACH transactions.
	ACHFraudTransactionsCount int64 `json:"ach_fraud_transactions_count" api:"nullable"`
	// Total amount of fraudulent ACH transactions.
	ACHFraudTransactionsTotalAmount float64 `json:"ach_fraud_transactions_total_amount" api:"nullable"`
	// Dates when fraudulent ACH transactions occurred.
	ACHFraudTransactionsDates []time.Time `json:"ach_fraud_transactions_dates" api:"nullable" format:"date"`
	// Number of returned ACH transactions.
	ACHReturnedTransactionsCount int64 `json:"ach_returned_transactions_count" api:"nullable"`
	// Total amount of returned ACH transactions.
	ACHReturnedTransactionsTotalAmount float64 `json:"ach_returned_transactions_total_amount" api:"nullable"`
	// Dates when ACH transactions were returned.
	ACHReturnedTransactionsDates []time.Time `json:"ach_returned_transactions_dates" api:"nullable" format:"date"`
	// Number of fraudulent card transactions.
	CardFraudTransactionsCount int64 `json:"card_fraud_transactions_count" api:"nullable"`
	// Total amount of fraudulent card transactions.
	CardFraudTransactionsTotalAmount float64 `json:"card_fraud_transactions_total_amount" api:"nullable"`
	// Dates when fraudulent card transactions occurred.
	CardFraudTransactionsDates []time.Time `json:"card_fraud_transactions_dates" api:"nullable" format:"date"`
	// Number of disputed card transactions.
	CardDisputedTransactionsCount int64 `json:"card_disputed_transactions_count" api:"nullable"`
	// Total amount of disputed card transactions.
	CardDisputedTransactionsTotalAmount float64 `json:"card_disputed_transactions_total_amount" api:"nullable"`
	// Dates when card transactions were disputed.
	CardDisputedTransactionsDates []time.Time `json:"card_disputed_transactions_dates" api:"nullable" format:"date"`
	// Number of stopped card transactions.
	CardStoppedTransactionsCount int64 `json:"card_stopped_transactions_count" api:"nullable"`
	// Dates when card transactions were stopped.
	CardStoppedTransactionsDates []time.Time `json:"card_stopped_transactions_dates" api:"nullable" format:"date"`
	// Number of accounts associated with the identity.
	AccountsCount int64 `json:"accounts_count" api:"nullable"`
	// Number of active accounts associated with the identity.
	AccountsActiveCount int64 `json:"accounts_active_count" api:"nullable"`
	// Number of closed accounts associated with the identity.
	AccountsClosedCount int64 `json:"accounts_closed_count" api:"nullable"`
	// Dates when accounts associated with the identity were closed.
	AccountsClosedDates []time.Time `json:"accounts_closed_dates" api:"nullable" format:"date"`
	// Number of accounts associated with fraud.
	AccountsFraudCount int64 `json:"accounts_fraud_count" api:"nullable"`
	// Total fraud loss associated with the accounts.
	AccountsFraudLossTotalAmount float64 `json:"accounts_fraud_loss_total_amount" api:"nullable"`
	// Dates when accounts were labeled as fraudulent.
	AccountsFraudLabeledDates []time.Time `json:"accounts_fraud_labeled_dates" api:"nullable" format:"date"`
	// Number of applications associated with the identity.
	ApplicationsCount int64 `json:"applications_count" api:"nullable"`
	// Dates when applications associated with the identity were submitted.
	ApplicationsDates []time.Time `json:"applications_dates" api:"nullable" format:"date"`
	// Number of approved applications associated with the identity.
	ApplicationsApprovedCount int64 `json:"applications_approved_count" api:"nullable"`
	// Number of declined applications associated with the identity.
	ApplicationsDeclinedCount int64 `json:"applications_declined_count" api:"nullable"`
	// Number of applications associated with fraud.
	ApplicationsFraudCount int64 `json:"applications_fraud_count" api:"nullable"`
	// Number of financial institutions associated with the identity.
	UserInstitutionCount int64 `json:"user_institution_count" api:"nullable"`
	// Number of dates of birth associated with the identity.
	UserDobCount int64 `json:"user_dob_count" api:"nullable"`
	// Number of mobile numbers associated with the identity.
	UserMobileCount int64 `json:"user_mobile_count" api:"nullable"`
	// Number of email addresses associated with the identity.
	UserEmailCount int64 `json:"user_email_count" api:"nullable"`
	// Number of addresses associated with the identity.
	UserAddressCount int64 `json:"user_address_count" api:"nullable"`
	// Number of active profiles associated with the identity.
	UserActiveProfileCount int64 `json:"user_active_profile_count" api:"nullable"`
	// Number of closed profiles associated with the identity.
	UserClosedProfileCount int64                  `json:"user_closed_profile_count" api:"nullable"`
	JSON                   reputationInsightsJSON `json:"-"`
}

// reputationInsightsJSON contains the JSON metadata for the struct [ReputationInsights]
type reputationInsightsJSON struct {
	ACHFraudTransactionsCount           apijson.Field
	ACHFraudTransactionsTotalAmount     apijson.Field
	ACHFraudTransactionsDates           apijson.Field
	ACHReturnedTransactionsCount        apijson.Field
	ACHReturnedTransactionsTotalAmount  apijson.Field
	ACHReturnedTransactionsDates        apijson.Field
	CardFraudTransactionsCount          apijson.Field
	CardFraudTransactionsTotalAmount    apijson.Field
	CardFraudTransactionsDates          apijson.Field
	CardDisputedTransactionsCount       apijson.Field
	CardDisputedTransactionsTotalAmount apijson.Field
	CardDisputedTransactionsDates       apijson.Field
	CardStoppedTransactionsCount        apijson.Field
	CardStoppedTransactionsDates        apijson.Field
	AccountsCount                       apijson.Field
	AccountsActiveCount                 apijson.Field
	AccountsClosedCount                 apijson.Field
	AccountsClosedDates                 apijson.Field
	AccountsFraudCount                  apijson.Field
	AccountsFraudLossTotalAmount        apijson.Field
	AccountsFraudLabeledDates           apijson.Field
	ApplicationsCount                   apijson.Field
	ApplicationsDates                   apijson.Field
	ApplicationsApprovedCount           apijson.Field
	ApplicationsDeclinedCount           apijson.Field
	ApplicationsFraudCount              apijson.Field
	UserInstitutionCount                apijson.Field
	UserDobCount                        apijson.Field
	UserMobileCount                     apijson.Field
	UserEmailCount                      apijson.Field
	UserAddressCount                    apijson.Field
	UserActiveProfileCount              apijson.Field
	UserClosedProfileCount              apijson.Field
	raw                                 string
	ExtraFields                         map[string]apijson.Field
}

func (r *ReputationInsights) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r reputationInsightsJSON) RawJSON() string {
	return r.raw
}

type CustomerReviewListParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type CustomerReviewSetVerificationDecisionParams struct {
	// The final status of the customer review.
	Status param.Field[CustomerReviewSetVerificationDecisionParamsStatus] `json:"status" api:"required"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r CustomerReviewSetVerificationDecisionParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type CustomerReviewSetVerificationDecisionParamsStatus string

const (
	CustomerReviewSetVerificationDecisionParamsStatusVerified CustomerReviewSetVerificationDecisionParamsStatus = "verified"
	CustomerReviewSetVerificationDecisionParamsStatusRejected CustomerReviewSetVerificationDecisionParamsStatus = "rejected"
)

func (r CustomerReviewSetVerificationDecisionParamsStatus) IsKnown() bool {
	switch r {
	case CustomerReviewSetVerificationDecisionParamsStatusVerified, CustomerReviewSetVerificationDecisionParamsStatusRejected:
		return true
	}
	return false
}

type CustomerIdentityVerificationBreakdown struct {
	Address                IdentityVerificationBreakdown             `json:"address"`
	Email                  IdentityVerificationBreakdown             `json:"email"`
	Fraud                  IdentityVerificationBreakdown             `json:"fraud"`
	Phone                  IdentityVerificationBreakdown             `json:"phone"`
	Synthetic              IdentityVerificationBreakdown             `json:"synthetic"`
	BusinessIdentification IdentityVerificationBreakdown             `json:"business_identification"`
	BusinessValidation     IdentityVerificationBreakdown             `json:"business_validation"`
	BusinessEvaluation     IdentityVerificationBreakdown             `json:"business_evaluation"`
	JSON                   customerIdentityVerificationBreakdownJSON `json:"-"`
}

// customerIdentityVerificationBreakdownJSON contains the JSON metadata for the struct [CustomerIdentityVerificationBreakdown]
type customerIdentityVerificationBreakdownJSON struct {
	Address                apijson.Field
	Email                  apijson.Field
	Fraud                  apijson.Field
	Phone                  apijson.Field
	Synthetic              apijson.Field
	BusinessIdentification apijson.Field
	BusinessValidation     apijson.Field
	BusinessEvaluation     apijson.Field
	raw                    string
	ExtraFields            map[string]apijson.Field
}

func (r *CustomerIdentityVerificationBreakdown) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerIdentityVerificationBreakdownJSON) RawJSON() string {
	return r.raw
}

type CustomerKYCVerificationValidations struct {
	// Whether the customer's first name passed validation.
	FirstName bool `json:"first_name"`
	// Whether the customer's last name passed validation.
	LastName bool `json:"last_name"`
	// Whether the customer's address passed validation.
	Address bool `json:"address"`
	// Whether the customer's city passed validation.
	City bool `json:"city"`
	// Whether the customer's state passed validation.
	State bool `json:"state"`
	// Whether the customer's ZIP code passed validation.
	Zip bool `json:"zip"`
	// Whether the customer's phone passed validation.
	Phone bool `json:"phone"`
	// Whether the customer's date of birth passed validation.
	Dob bool `json:"dob"`
	// Whether the customer's Social Security number passed validation.
	Ssn bool `json:"ssn"`
	// Whether the customer's email passed validation.
	Email bool                                   `json:"email"`
	JSON  customerKYCVerificationValidationsJSON `json:"-"`
}

// customerKYCVerificationValidationsJSON contains the JSON metadata for the struct [CustomerKYCVerificationValidations]
type customerKYCVerificationValidationsJSON struct {
	FirstName   apijson.Field
	LastName    apijson.Field
	Address     apijson.Field
	City        apijson.Field
	State       apijson.Field
	Zip         apijson.Field
	Phone       apijson.Field
	Dob         apijson.Field
	Ssn         apijson.Field
	Email       apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *CustomerKYCVerificationValidations) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r customerKYCVerificationValidationsJSON) RawJSON() string {
	return r.raw
}
