// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// FundingEventService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewFundingEventService] method instead.
type FundingEventService struct {
	Options []option.RequestOption
}

// NewFundingEventService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewFundingEventService(opts ...option.RequestOption) (r *FundingEventService) {
	r = &FundingEventService{}
	r.Options = opts
	return
}

// Returns a paginated list of funding events that match the specified filters.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: FundingEventListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*FundingEventSummaryList: OK
//
// Example:
//
//	fundingEvent, err := client.FundingEvents.List(context.Background(), sdk.FundingEventListParams{
//		PageNumber: sdk.F[int64](1),
//		PageSize:   sdk.F[int64](100),
//		SortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(fundingEvent)
func (r *FundingEventService) List(ctx context.Context, query FundingEventListParams, opts ...option.RequestOption) (res *FundingEventSummaryList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	if query.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", query.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/funding_events"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Returns a funding event by its unique identifier, including its current status, status history, and linked bank account details when available.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the funding event.
//	params: FundingEventGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*FundingEventResponse: OK
//
// Example:
//
//	fundingEvent, err := client.FundingEvents.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.FundingEventGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(fundingEvent)
func (r *FundingEventService) Get(ctx context.Context, id string, params FundingEventGetParams, opts ...option.RequestOption) (res *FundingEventResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/funding_events/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Creates a funding event for unfunded charge or payout activity in the sandbox and returns its ID. This endpoint is unavailable in production.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: FundingEventSimulateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*FundingEventSimulation: Created
//
// Example:
//
//	fundingEvent, err := client.FundingEvents.Simulate(context.Background(), sdk.FundingEventSimulateParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(fundingEvent)
func (r *FundingEventService) Simulate(ctx context.Context, body FundingEventSimulateParams, opts ...option.RequestOption) (res *FundingEventSimulation, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/funding_events/simulate"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Returns a paginated list of payments included in the funding event.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the funding event.
//	query: FundingEventListPaymentsParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*FundingEventPaymentList: OK
//
// Example:
//
//	fundingEvent, err := client.FundingEvents.ListPayments(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.FundingEventListPaymentsParams{
//		DefaultSortOrder: sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
//		SortOrder:        sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(fundingEvent)
func (r *FundingEventService) ListPayments(ctx context.Context, id string, query FundingEventListPaymentsParams, opts ...option.RequestOption) (res *FundingEventPaymentList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	if query.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", query.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/funding_event_payments/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

type FundingEventSummaryList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType `json:"response_type" api:"required"`
	// Funding events returned for this page.
	Data []FundingEventSummary       `json:"data" api:"required"`
	JSON fundingEventSummaryListJSON `json:"-"`
}

// fundingEventSummaryListJSON contains the JSON metadata for the struct [FundingEventSummaryList]
type fundingEventSummaryListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *FundingEventSummaryList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventSummaryListJSON) RawJSON() string {
	return r.raw
}

type FundingEventResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType             `json:"response_type" api:"required"`
	Data         FundingEvent             `json:"data" api:"required"`
	JSON         fundingEventResponseJSON `json:"-"`
}

// fundingEventResponseJSON contains the JSON metadata for the struct [FundingEventResponse]
type fundingEventResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *FundingEventResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventResponseJSON) RawJSON() string {
	return r.raw
}

type FundingEventSimulation struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType                 `json:"response_type" api:"required"`
	Data         FundingEventSimulationResult `json:"data" api:"required"`
	JSON         fundingEventSimulationJSON   `json:"-"`
}

// fundingEventSimulationJSON contains the JSON metadata for the struct [FundingEventSimulation]
type fundingEventSimulationJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *FundingEventSimulation) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventSimulationJSON) RawJSON() string {
	return r.raw
}

type FundingEventPaymentList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType `json:"response_type" api:"required"`
	// Funding-event payments returned for this page.
	Data []FundingEventPayment       `json:"data" api:"required"`
	JSON fundingEventPaymentListJSON `json:"-"`
}

// fundingEventPaymentListJSON contains the JSON metadata for the struct [FundingEventPaymentList]
type fundingEventPaymentListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *FundingEventPaymentList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventPaymentListJSON) RawJSON() string {
	return r.raw
}

type FundingEventSummary struct {
	// Unique identifier for this funding event.
	ID string `json:"id" api:"required" format:"uuid"`
	// Total funding event amount in the smallest currency unit. For example, `1000` is
	// $10.00 USD.
	Amount int64 `json:"amount" api:"required"`
	// Transfer direction relative to the linked bank account. `deposit` moves funds
	// into the account, and `withdrawal` moves funds out.
	Direction TransferDirection `json:"direction" api:"required"`
	// Reason for the funding event. `charge_deposit` settles collected charges to the
	// linked bank account. `charge_reversal` withdraws funds for reversed charges.
	// `payout_withdrawal` withdraws funds for payouts. `payout_return` deposits
	// returned payout funds.
	EventType FundingEventType `json:"event_type" api:"required"`
	// Number of payments included in this funding event.
	PaymentCount int64 `json:"payment_count" api:"required"`
	// The date the funds transfer was initiated.
	TransferDate time.Time `json:"transfer_date" api:"required" format:"date"`
	// Network trace numbers associated with payments in this funding event.
	TraceNumbers []string `json:"trace_numbers" api:"required"`
	// Timestamp when this funding event was created.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp when this funding event was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Network-level trace identifiers assigned during processing. Keys vary by payment
	// rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// The trace number of the funding event.
	TraceNumber string `json:"trace_number" api:"nullable"`
	// Current status of this funding event.
	Status PaymentStatus `json:"status"`
	// Reason, source, and message for the most recent status change.
	StatusDetails PaymentStatusDetails    `json:"status_details"`
	JSON          fundingEventSummaryJSON `json:"-"`
}

// fundingEventSummaryJSON contains the JSON metadata for the struct [FundingEventSummary]
type fundingEventSummaryJSON struct {
	ID            apijson.Field
	Amount        apijson.Field
	Direction     apijson.Field
	EventType     apijson.Field
	PaymentCount  apijson.Field
	TransferDate  apijson.Field
	TraceNumbers  apijson.Field
	CreatedAt     apijson.Field
	UpdatedAt     apijson.Field
	TraceIDs      apijson.Field
	TraceNumber   apijson.Field
	Status        apijson.Field
	StatusDetails apijson.Field
	raw           string
	ExtraFields   map[string]apijson.Field
}

func (r *FundingEventSummary) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventSummaryJSON) RawJSON() string {
	return r.raw
}

type FundingEvent struct {
	// Unique identifier for this funding event.
	ID string `json:"id" api:"required" format:"uuid"`
	// Total funding event amount in the smallest currency unit. For example, `1000` is
	// $10.00 USD.
	Amount int64 `json:"amount" api:"required"`
	// Transfer direction relative to the linked bank account. `deposit` moves funds
	// into the account, and `withdrawal` moves funds out.
	Direction FundingEventTransferDirection `json:"direction" api:"required"`
	// Reason for the funding event. `charge_deposit` settles collected charges to the
	// linked bank account. `charge_reversal` withdraws funds for reversed charges.
	// `payout_withdrawal` withdraws funds for payouts. `payout_return` deposits
	// returned payout funds.
	EventType FundingEventType `json:"event_type" api:"required"`
	// Network trace numbers associated with payments in this funding event.
	TraceNumbers []string `json:"trace_numbers" api:"required"`
	// Number of payments included in this funding event.
	PaymentCount int64 `json:"payment_count" api:"required"`
	// The date the funds transfer was initiated.
	TransferDate time.Time `json:"transfer_date" api:"required" format:"date"`
	// Timestamp when this funding event was created.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp when this funding event was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Network-level trace identifiers assigned during processing. Keys vary by payment
	// rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Complete ordered history of all status changes for this funding event.
	StatusHistory []PaymentStatusHistory `json:"status_history" api:"required"`
	// Current status of this funding event.
	Status PaymentStatus `json:"status"`
	// Reason, source, and message for the most recent status change.
	StatusDetails PaymentStatusDetails `json:"status_details"`
	// Configuration used to process this funding event.
	Config FundingEventConfiguration `json:"config"`
	// Details of the linked bank account used for this funding event.
	LinkedBankAccountDetails UnmaskedLinkedBankAccountDetails `json:"linked_bank_account_details"`
	JSON                     fundingEventJSON                 `json:"-"`
}

// fundingEventJSON contains the JSON metadata for the struct [FundingEvent]
type fundingEventJSON struct {
	ID                       apijson.Field
	Amount                   apijson.Field
	Direction                apijson.Field
	EventType                apijson.Field
	TraceNumbers             apijson.Field
	PaymentCount             apijson.Field
	TransferDate             apijson.Field
	CreatedAt                apijson.Field
	UpdatedAt                apijson.Field
	TraceIDs                 apijson.Field
	StatusHistory            apijson.Field
	Status                   apijson.Field
	StatusDetails            apijson.Field
	Config                   apijson.Field
	LinkedBankAccountDetails apijson.Field
	raw                      string
	ExtraFields              map[string]apijson.Field
}

func (r *FundingEvent) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventJSON) RawJSON() string {
	return r.raw
}

type FundingEventSimulationResult struct {
	// Unique identifier for the created funding event.
	ID   string                           `json:"id" api:"required" format:"uuid"`
	JSON fundingEventSimulationResultJSON `json:"-"`
}

// fundingEventSimulationResultJSON contains the JSON metadata for the struct [FundingEventSimulationResult]
type fundingEventSimulationResultJSON struct {
	ID          apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *FundingEventSimulationResult) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventSimulationResultJSON) RawJSON() string {
	return r.raw
}

type FundingEventPayment struct {
	// Unique identifier for this payment.
	ID string `json:"id" api:"required" format:"uuid"`
	// Whether this payment is a charge or payout.
	PaymentType PaymentType `json:"payment_type" api:"required"`
	// The date on which this payment was submitted for processing.
	PaymentDate time.Time `json:"payment_date" api:"required" format:"date"`
	// Three-letter ISO 4217 currency code.
	Currency string `json:"currency" api:"required"`
	// Portion of the payment amount included in this funding event, in the smallest
	// currency unit.
	FundingAmount int64 `json:"funding_amount" api:"required"`
	// Reason this payment was included in the funding event.
	Reason FundingEventPaymentReason `json:"reason" api:"required"`
	// Total payment amount in the smallest currency unit (e.g. 1000 = $10.00 USD).
	PaymentAmount int64 `json:"payment_amount" api:"required"`
	// Current status of this payment.
	Status PaymentStatus `json:"status" api:"required"`
	// Your unique identifier for this payment, used to correlate with your internal
	// records.
	ExternalID string `json:"external_id" api:"required"`
	// Network-level trace identifiers assigned during processing. Keys vary by payment
	// rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Details of the customer associated with this payment.
	CustomerDetails CustomerDetails `json:"customer_details"`
	// Details of the paykey used for this payment.
	PaykeyDetails PaykeyDetails `json:"paykey_details"`
	// Key-value metadata for this payment. Included only when `include_metadata` is
	// `true`.
	Metadata map[string]string       `json:"metadata" api:"nullable"`
	JSON     fundingEventPaymentJSON `json:"-"`
}

// fundingEventPaymentJSON contains the JSON metadata for the struct [FundingEventPayment]
type fundingEventPaymentJSON struct {
	ID              apijson.Field
	PaymentType     apijson.Field
	PaymentDate     apijson.Field
	Currency        apijson.Field
	FundingAmount   apijson.Field
	Reason          apijson.Field
	PaymentAmount   apijson.Field
	Status          apijson.Field
	ExternalID      apijson.Field
	TraceIDs        apijson.Field
	CustomerDetails apijson.Field
	PaykeyDetails   apijson.Field
	Metadata        apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *FundingEventPayment) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventPaymentJSON) RawJSON() string {
	return r.raw
}

type TransferDirection string

const (
	TransferDirectionDeposit    TransferDirection = "deposit"
	TransferDirectionWithdrawal TransferDirection = "withdrawal"
)

func (r TransferDirection) IsKnown() bool {
	switch r {
	case TransferDirectionDeposit, TransferDirectionWithdrawal:
		return true
	}
	return false
}

type FundingEventType string

const (
	FundingEventTypeChargeDeposit    FundingEventType = "charge_deposit"
	FundingEventTypeChargeReversal   FundingEventType = "charge_reversal"
	FundingEventTypePayoutReturn     FundingEventType = "payout_return"
	FundingEventTypePayoutWithdrawal FundingEventType = "payout_withdrawal"
)

func (r FundingEventType) IsKnown() bool {
	switch r {
	case FundingEventTypeChargeDeposit, FundingEventTypeChargeReversal, FundingEventTypePayoutReturn, FundingEventTypePayoutWithdrawal:
		return true
	}
	return false
}

type FundingEventTransferDirection string

const (
	FundingEventTransferDirectionDeposit    FundingEventTransferDirection = "deposit"
	FundingEventTransferDirectionWithdrawal FundingEventTransferDirection = "withdrawal"
)

func (r FundingEventTransferDirection) IsKnown() bool {
	switch r {
	case FundingEventTransferDirectionDeposit, FundingEventTransferDirectionWithdrawal:
		return true
	}
	return false
}

type FundingEventConfiguration struct {
	// Processing outcome configured for this simulated funding event.
	SandboxOutcome SimulatedPaymentOutcome       `json:"sandbox_outcome"`
	JSON           fundingEventConfigurationJSON `json:"-"`
}

// fundingEventConfigurationJSON contains the JSON metadata for the struct [FundingEventConfiguration]
type fundingEventConfigurationJSON struct {
	SandboxOutcome apijson.Field
	raw            string
	ExtraFields    map[string]apijson.Field
}

func (r *FundingEventConfiguration) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r fundingEventConfigurationJSON) RawJSON() string {
	return r.raw
}

type FundingEventPaymentReason string

const (
	FundingEventPaymentReasonCredit   FundingEventPaymentReason = "credit"
	FundingEventPaymentReasonDebit    FundingEventPaymentReason = "debit"
	FundingEventPaymentReasonReversal FundingEventPaymentReason = "reversal"
	FundingEventPaymentReasonFailed   FundingEventPaymentReason = "failed"
)

func (r FundingEventPaymentReason) IsKnown() bool {
	switch r {
	case FundingEventPaymentReasonCredit, FundingEventPaymentReasonDebit, FundingEventPaymentReasonReversal, FundingEventPaymentReasonFailed:
		return true
	}
	return false
}

type FundingEventListParams struct {
	// Filter to funding events created on or after this date.
	CreatedFrom param.Field[time.Time] `query:"created_from" format:"date"`
	// Filter to funding events created on or before this date.
	CreatedTo param.Field[time.Time] `query:"created_to" format:"date"`
	// Filter by transfer direction relative to the linked bank account.
	Direction param.Field[TransferDirection] `query:"direction"`
	// Filter by funding event type.
	EventType param.Field[FundingEventType] `query:"event_type"`
	// Results page number. Starts at page 1.
	PageNumber param.Field[int64] `query:"page_number"`
	// Results page size. Max value: 1000.
	PageSize param.Field[int64] `query:"page_size"`
	// Free-text search across funding event fields.
	SearchText param.Field[string] `query:"search_text"`
	// Field used to sort the results.
	SortBy param.Field[FundingEventListParamsSortBy] `query:"sort_by"`
	// Order in which to sort the results.
	SortOrder param.Field[SortOrder] `query:"sort_order"`
	// Filter by funding event status.
	Status param.Field[[]PaymentStatus] `query:"status"`
	// Filter by the reason for the most recent status change.
	StatusReason param.Field[[]PaymentStatusReason] `query:"status_reason"`
	// Filter by the source of the most recent status change.
	StatusSource param.Field[[]PaymentStatusSource] `query:"status_source"`
	// Filter by a network-level trace identifier assigned during processing.
	TraceID param.Field[string] `query:"trace_id"`
	// Filter by a network trace number assigned during processing.
	TraceNumber param.Field[string] `query:"trace_number"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

// URLQuery serializes [FundingEventListParams]'s query parameters as `url.Values`.
func (r FundingEventListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type FundingEventListParamsSortBy string

const (
	FundingEventListParamsSortByTransferDate FundingEventListParamsSortBy = "transfer_date"
	FundingEventListParamsSortByID           FundingEventListParamsSortBy = "id"
	FundingEventListParamsSortByAmount       FundingEventListParamsSortBy = "amount"
)

func (r FundingEventListParamsSortBy) IsKnown() bool {
	switch r {
	case FundingEventListParamsSortByTransferDate, FundingEventListParamsSortByID, FundingEventListParamsSortByAmount:
		return true
	}
	return false
}

type FundingEventGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type FundingEventSimulateParams struct {
	// Required. Selects charge or payout activity for the simulated funding event.
	FundingEventJobType param.Field[FundingEventSimulateParamsFundingEventJobType] `json:"funding_event_job_type" api:"required"`
	// Optional. Sets the processing outcome for the simulated funding event. Defaults
	// to `standard`.
	SandboxOutcome param.Field[SimulatedPaymentOutcome] `json:"sandbox_outcome"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r FundingEventSimulateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type FundingEventSimulateParamsFundingEventJobType string

const (
	FundingEventSimulateParamsFundingEventJobTypeCharges FundingEventSimulateParamsFundingEventJobType = "charges"
	FundingEventSimulateParamsFundingEventJobTypePayouts FundingEventSimulateParamsFundingEventJobType = "payouts"
)

func (r FundingEventSimulateParamsFundingEventJobType) IsKnown() bool {
	switch r {
	case FundingEventSimulateParamsFundingEventJobTypeCharges, FundingEventSimulateParamsFundingEventJobTypePayouts:
		return true
	}
	return false
}

type FundingEventListPaymentsParams struct {
	// Default number of results returned per page.
	DefaultPageSize param.Field[int64] `query:"default_page_size"`
	// Default field used to sort the results.
	DefaultSort param.Field[FundingEventListPaymentsParamsDefaultSort] `query:"default_sort"`
	// Default order in which to sort the results.
	DefaultSortOrder param.Field[SortOrder] `query:"default_sort_order"`
	// When `true`, includes each payment's metadata. Defaults to `false`.
	IncludeMetadata param.Field[bool] `query:"include_metadata"`
	// Results page number. Starts at 1. Defaults to 1.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results per page. Maximum 1,000. Defaults to 100.
	PageSize param.Field[int64] `query:"page_size"`
	// Field used to sort the results.
	SortBy param.Field[FundingEventListPaymentsParamsSortBy] `query:"sort_by"`
	// Order in which to sort the results.
	SortOrder param.Field[SortOrder] `query:"sort_order"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

// URLQuery serializes [FundingEventListPaymentsParams]'s query parameters as `url.Values`.
func (r FundingEventListPaymentsParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type FundingEventListPaymentsParamsDefaultSort string

const (
	FundingEventListPaymentsParamsDefaultSortCreatedAt   FundingEventListPaymentsParamsDefaultSort = "created_at"
	FundingEventListPaymentsParamsDefaultSortPaymentDate FundingEventListPaymentsParamsDefaultSort = "payment_date"
	FundingEventListPaymentsParamsDefaultSortEffectiveAt FundingEventListPaymentsParamsDefaultSort = "effective_at"
	FundingEventListPaymentsParamsDefaultSortID          FundingEventListPaymentsParamsDefaultSort = "id"
)

func (r FundingEventListPaymentsParamsDefaultSort) IsKnown() bool {
	switch r {
	case FundingEventListPaymentsParamsDefaultSortCreatedAt, FundingEventListPaymentsParamsDefaultSortPaymentDate, FundingEventListPaymentsParamsDefaultSortEffectiveAt, FundingEventListPaymentsParamsDefaultSortID:
		return true
	}
	return false
}

type FundingEventListPaymentsParamsSortBy string

const (
	FundingEventListPaymentsParamsSortByCreatedAt   FundingEventListPaymentsParamsSortBy = "created_at"
	FundingEventListPaymentsParamsSortByPaymentDate FundingEventListPaymentsParamsSortBy = "payment_date"
	FundingEventListPaymentsParamsSortByEffectiveAt FundingEventListPaymentsParamsSortBy = "effective_at"
	FundingEventListPaymentsParamsSortByID          FundingEventListPaymentsParamsSortBy = "id"
)

func (r FundingEventListPaymentsParamsSortBy) IsKnown() bool {
	switch r {
	case FundingEventListPaymentsParamsSortByCreatedAt, FundingEventListPaymentsParamsSortByPaymentDate, FundingEventListPaymentsParamsSortByEffectiveAt, FundingEventListPaymentsParamsSortByID:
		return true
	}
	return false
}
