// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// LinkedBankAccountService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewLinkedBankAccountService] method instead.
type LinkedBankAccountService struct {
	Options []option.RequestOption
}

// NewLinkedBankAccountService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewLinkedBankAccountService(opts ...option.RequestOption) (r *LinkedBankAccountService) {
	r = &LinkedBankAccountService{}
	r.Options = opts
	return
}

// Creates a linked bank account for an account or platform, assigns its payment purposes, and returns the linked bank account.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: LinkedBankAccountNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LinkedBankAccountResponse: Created
//
// Example:
//
//	linkedBankAccount, err := client.LinkedBankAccounts.New(context.Background(), sdk.LinkedBankAccountNewParams{
//		BankAccount: sdk.F[sdk.LinkedBankAccountNewParamsBankAccount](sdk.LinkedBankAccountNewParamsBankAccount{
//			AccountHolder: sdk.F[string](""),
//			RoutingNumber: sdk.F[string]("xxxxxxxxx"),
//			AccountNumber: sdk.F[string](""),
//		}),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(linkedBankAccount)
func (r *LinkedBankAccountService) New(ctx context.Context, body LinkedBankAccountNewParams, opts ...option.RequestOption) (res *LinkedBankAccountResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/linked_bank_accounts"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Returns a paginated list of linked bank accounts. Filter the list by account, scope, purpose, or status.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: LinkedBankAccountListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LinkedBankAccountList: OK
//
// Example:
//
//	linkedBankAccount, err := client.LinkedBankAccounts.List(context.Background(), sdk.LinkedBankAccountListParams{
//		PageNumber: sdk.F[int64](1),
//		PageSize:   sdk.F[int64](100),
//		SortBy:     sdk.F[string]("id"),
//		SortOrder:  sdk.F[sdk.LinkedBankAccountListParamsSortOrder](sdk.LinkedBankAccountListParamsSortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(linkedBankAccount)
func (r *LinkedBankAccountService) List(ctx context.Context, query LinkedBankAccountListParams, opts ...option.RequestOption) (res *LinkedBankAccountList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/linked_bank_accounts"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Updates bank account details and metadata, then returns the linked bank account. The linked bank account must have status `created`, or status `onboarding` with `status_detail.reason` set to `stuck`.
//
// Parameters:
//
//	ctx: Context for the request.
//	linkedBankAccountID: The ID of the linked bank account.
//	body: LinkedBankAccountUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LinkedBankAccountResponse: OK
//
// Example:
//
//	linkedBankAccount, err := client.LinkedBankAccounts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountUpdateParams{
//		BankAccount: sdk.F[sdk.LinkedBankAccountUpdateParamsBankAccount](sdk.LinkedBankAccountUpdateParamsBankAccount{
//			AccountHolder: sdk.F[string](""),
//			RoutingNumber: sdk.F[string]("xxxxxxxxx"),
//			AccountNumber: sdk.F[string](""),
//		}),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(linkedBankAccount)
func (r *LinkedBankAccountService) Update(ctx context.Context, linkedBankAccountID string, body LinkedBankAccountUpdateParams, opts ...option.RequestOption) (res *LinkedBankAccountResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if linkedBankAccountID == "" {
		err = errors.New("missing required linked_bank_account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/linked_bank_accounts/%s", url.PathEscape(linkedBankAccountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Returns the linked bank account with the specified ID. The response masks the account number.
//
// Parameters:
//
//	ctx: Context for the request.
//	linkedBankAccountID: The ID of the linked bank account.
//	params: LinkedBankAccountGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LinkedBankAccountResponse: OK
//
// Example:
//
//	linkedBankAccount, err := client.LinkedBankAccounts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(linkedBankAccount)
func (r *LinkedBankAccountService) Get(ctx context.Context, linkedBankAccountID string, params LinkedBankAccountGetParams, opts ...option.RequestOption) (res *LinkedBankAccountResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if linkedBankAccountID == "" {
		err = errors.New("missing required linked_bank_account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/linked_bank_accounts/%s", url.PathEscape(linkedBankAccountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Returns the linked bank account with the specified ID without masking its account number. This endpoint is available only when Straddle enables data unmasking for the account.
//
// Parameters:
//
//	ctx: Context for the request.
//	linkedBankAccountID: The ID of the linked bank account.
//	params: LinkedBankAccountListUnmaskedParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*UnmaskedLinkedBankAccountResponse: OK
//
// Example:
//
//	linkedBankAccount, err := client.LinkedBankAccounts.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountListUnmaskedParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(linkedBankAccount)
func (r *LinkedBankAccountService) ListUnmasked(ctx context.Context, linkedBankAccountID string, params LinkedBankAccountListUnmaskedParams, opts ...option.RequestOption) (res *UnmaskedLinkedBankAccountResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if linkedBankAccountID == "" {
		err = errors.New("missing required linked_bank_account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/linked_bank_accounts/%s/unmask", url.PathEscape(linkedBankAccountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Cancels a linked bank account and returns it with status `canceled`. The linked bank account must have status `created`.
//
// Parameters:
//
//	ctx: Context for the request.
//	linkedBankAccountID: The ID of the linked bank account.
//	params: LinkedBankAccountCancelParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*LinkedBankAccountResponse: OK
//
// Example:
//
//	linkedBankAccount, err := client.LinkedBankAccounts.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountCancelParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(linkedBankAccount)
func (r *LinkedBankAccountService) Cancel(ctx context.Context, linkedBankAccountID string, params LinkedBankAccountCancelParams, opts ...option.RequestOption) (res *LinkedBankAccountResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", params.IdempotencyKey.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if linkedBankAccountID == "" {
		err = errors.New("missing required linked_bank_account_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/linked_bank_accounts/%s/cancel", url.PathEscape(linkedBankAccountID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, nil, &res, opts...)
	return res, err
}

type LinkedBankAccountResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType LinkedBankAccountResponseResponseType `json:"response_type" api:"required"`
	Data         LinkedBankAccount                     `json:"data" api:"required"`
	JSON         linkedBankAccountResponseJSON         `json:"-"`
}

// linkedBankAccountResponseJSON contains the JSON metadata for the struct [LinkedBankAccountResponse]
type linkedBankAccountResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *LinkedBankAccountResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r linkedBankAccountResponseJSON) RawJSON() string {
	return r.raw
}

type LinkedBankAccountResponseResponseType string

const (
	LinkedBankAccountResponseResponseTypeObject LinkedBankAccountResponseResponseType = "object"
	LinkedBankAccountResponseResponseTypeArray  LinkedBankAccountResponseResponseType = "array"
	LinkedBankAccountResponseResponseTypeError  LinkedBankAccountResponseResponseType = "error"
	LinkedBankAccountResponseResponseTypeNone   LinkedBankAccountResponseResponseType = "none"
)

func (r LinkedBankAccountResponseResponseType) IsKnown() bool {
	switch r {
	case LinkedBankAccountResponseResponseTypeObject, LinkedBankAccountResponseResponseTypeArray, LinkedBankAccountResponseResponseTypeError, LinkedBankAccountResponseResponseTypeNone:
		return true
	}
	return false
}

type LinkedBankAccountList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType LinkedBankAccountListResponseType `json:"response_type" api:"required"`
	// Linked bank accounts returned for this page.
	Data []LinkedBankAccount       `json:"data" api:"required"`
	JSON linkedBankAccountListJSON `json:"-"`
}

// linkedBankAccountListJSON contains the JSON metadata for the struct [LinkedBankAccountList]
type linkedBankAccountListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *LinkedBankAccountList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r linkedBankAccountListJSON) RawJSON() string {
	return r.raw
}

type LinkedBankAccountListResponseType string

const (
	LinkedBankAccountListResponseTypeObject LinkedBankAccountListResponseType = "object"
	LinkedBankAccountListResponseTypeArray  LinkedBankAccountListResponseType = "array"
	LinkedBankAccountListResponseTypeError  LinkedBankAccountListResponseType = "error"
	LinkedBankAccountListResponseTypeNone   LinkedBankAccountListResponseType = "none"
)

func (r LinkedBankAccountListResponseType) IsKnown() bool {
	switch r {
	case LinkedBankAccountListResponseTypeObject, LinkedBankAccountListResponseTypeArray, LinkedBankAccountListResponseTypeError, LinkedBankAccountListResponseTypeNone:
		return true
	}
	return false
}

type UnmaskedLinkedBankAccountResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType UnmaskedLinkedBankAccountResponseResponseType `json:"response_type" api:"required"`
	Data         UnmaskedLinkedBankAccount                     `json:"data" api:"required"`
	JSON         unmaskedLinkedBankAccountResponseJSON         `json:"-"`
}

// unmaskedLinkedBankAccountResponseJSON contains the JSON metadata for the struct [UnmaskedLinkedBankAccountResponse]
type unmaskedLinkedBankAccountResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedLinkedBankAccountResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedLinkedBankAccountResponseJSON) RawJSON() string {
	return r.raw
}

type UnmaskedLinkedBankAccountResponseResponseType string

const (
	UnmaskedLinkedBankAccountResponseResponseTypeObject UnmaskedLinkedBankAccountResponseResponseType = "object"
	UnmaskedLinkedBankAccountResponseResponseTypeArray  UnmaskedLinkedBankAccountResponseResponseType = "array"
	UnmaskedLinkedBankAccountResponseResponseTypeError  UnmaskedLinkedBankAccountResponseResponseType = "error"
	UnmaskedLinkedBankAccountResponseResponseTypeNone   UnmaskedLinkedBankAccountResponseResponseType = "none"
)

func (r UnmaskedLinkedBankAccountResponseResponseType) IsKnown() bool {
	switch r {
	case UnmaskedLinkedBankAccountResponseResponseTypeObject, UnmaskedLinkedBankAccountResponseResponseTypeArray, UnmaskedLinkedBankAccountResponseResponseTypeError, UnmaskedLinkedBankAccountResponseResponseTypeNone:
		return true
	}
	return false
}

type LinkedBankAccount struct {
	// Straddle's unique ID for the linked bank account.
	ID string `json:"id" api:"required" format:"uuid"`
	// ID of the related account, if this is an account-level linked bank account.
	AccountID string `json:"account_id" api:"required,nullable" format:"uuid"`
	// Status of the linked bank account.
	Status       LinkedBankAccountStatus        `json:"status" api:"required"`
	StatusDetail LinkedBankAccountStatusDetail  `json:"status_detail" api:"required"`
	BankAccount  MaskedLinkedBankAccountDetails `json:"bank_account" api:"required"`
	// Date and time when Straddle created the linked bank account.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Date and time of the most recent linked bank account update.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Payment purposes assigned to the linked bank account.
	Purposes []LinkedBankAccountPurpose `json:"purposes" api:"required"`
	// Up to 20 user-defined key-value pairs.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	// ID of the related platform, if this is a platform-level linked bank account.
	PlatformID string `json:"platform_id" api:"nullable" format:"uuid"`
	// Your description for the linked bank account.
	Description string                `json:"description" api:"nullable"`
	JSON        linkedBankAccountJSON `json:"-"`
}

// linkedBankAccountJSON contains the JSON metadata for the struct [LinkedBankAccount]
type linkedBankAccountJSON struct {
	ID           apijson.Field
	AccountID    apijson.Field
	Status       apijson.Field
	StatusDetail apijson.Field
	BankAccount  apijson.Field
	CreatedAt    apijson.Field
	UpdatedAt    apijson.Field
	Purposes     apijson.Field
	Metadata     apijson.Field
	PlatformID   apijson.Field
	Description  apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *LinkedBankAccount) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r linkedBankAccountJSON) RawJSON() string {
	return r.raw
}

type LinkedBankAccountStatus string

const (
	LinkedBankAccountStatusCreated    LinkedBankAccountStatus = "created"
	LinkedBankAccountStatusOnboarding LinkedBankAccountStatus = "onboarding"
	LinkedBankAccountStatusActive     LinkedBankAccountStatus = "active"
	LinkedBankAccountStatusRejected   LinkedBankAccountStatus = "rejected"
	LinkedBankAccountStatusInactive   LinkedBankAccountStatus = "inactive"
	LinkedBankAccountStatusCanceled   LinkedBankAccountStatus = "canceled"
)

func (r LinkedBankAccountStatus) IsKnown() bool {
	switch r {
	case LinkedBankAccountStatusCreated, LinkedBankAccountStatusOnboarding, LinkedBankAccountStatusActive, LinkedBankAccountStatusRejected, LinkedBankAccountStatusInactive, LinkedBankAccountStatusCanceled:
		return true
	}
	return false
}

type UnmaskedLinkedBankAccount struct {
	// Straddle's unique ID for the linked bank account.
	ID string `json:"id" api:"required" format:"uuid"`
	// ID of the Straddle account associated with the linked bank account.
	AccountID string `json:"account_id" api:"required" format:"uuid"`
	// Status of the linked bank account.
	Status UnmaskedLinkedBankAccountStatus `json:"status" api:"required"`
	// Details about the linked bank account's status.
	StatusDetail LinkedBankAccountStatusDetail `json:"status_detail" api:"required"`
	// Unmasked bank account details.
	BankAccount UnmaskedLinkedBankAccountDetails `json:"bank_account" api:"required"`
	// Date and time when Straddle created the linked bank account.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Date and time of the most recent linked bank account update.
	UpdatedAt time.Time                     `json:"updated_at" api:"required" format:"date-time"`
	Metadata  map[string]string             `json:"metadata" api:"nullable"`
	JSON      unmaskedLinkedBankAccountJSON `json:"-"`
}

// unmaskedLinkedBankAccountJSON contains the JSON metadata for the struct [UnmaskedLinkedBankAccount]
type unmaskedLinkedBankAccountJSON struct {
	ID           apijson.Field
	AccountID    apijson.Field
	Status       apijson.Field
	StatusDetail apijson.Field
	BankAccount  apijson.Field
	CreatedAt    apijson.Field
	UpdatedAt    apijson.Field
	Metadata     apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedLinkedBankAccount) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedLinkedBankAccountJSON) RawJSON() string {
	return r.raw
}

type UnmaskedLinkedBankAccountStatus string

const (
	UnmaskedLinkedBankAccountStatusCreated    UnmaskedLinkedBankAccountStatus = "created"
	UnmaskedLinkedBankAccountStatusOnboarding UnmaskedLinkedBankAccountStatus = "onboarding"
	UnmaskedLinkedBankAccountStatusActive     UnmaskedLinkedBankAccountStatus = "active"
	UnmaskedLinkedBankAccountStatusRejected   UnmaskedLinkedBankAccountStatus = "rejected"
	UnmaskedLinkedBankAccountStatusInactive   UnmaskedLinkedBankAccountStatus = "inactive"
	UnmaskedLinkedBankAccountStatusCanceled   UnmaskedLinkedBankAccountStatus = "canceled"
)

func (r UnmaskedLinkedBankAccountStatus) IsKnown() bool {
	switch r {
	case UnmaskedLinkedBankAccountStatusCreated, UnmaskedLinkedBankAccountStatusOnboarding, UnmaskedLinkedBankAccountStatusActive, UnmaskedLinkedBankAccountStatusRejected, UnmaskedLinkedBankAccountStatusInactive, UnmaskedLinkedBankAccountStatusCanceled:
		return true
	}
	return false
}

type LinkedBankAccountStatusDetail struct {
	// Machine-readable reason for the linked bank account's status.
	Reason LinkedBankAccountStatusDetailReason `json:"reason" api:"required"`
	// System that produced the linked bank account status detail.
	Source LinkedBankAccountStatusDetailSource `json:"source" api:"required"`
	// Machine-readable status code from the source.
	Code string `json:"code" api:"required"`
	// Human-readable description of the linked bank account's status.
	Message string                            `json:"message" api:"required"`
	JSON    linkedBankAccountStatusDetailJSON `json:"-"`
}

// linkedBankAccountStatusDetailJSON contains the JSON metadata for the struct [LinkedBankAccountStatusDetail]
type linkedBankAccountStatusDetailJSON struct {
	Reason      apijson.Field
	Source      apijson.Field
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *LinkedBankAccountStatusDetail) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r linkedBankAccountStatusDetailJSON) RawJSON() string {
	return r.raw
}

type LinkedBankAccountStatusDetailReason string

const (
	LinkedBankAccountStatusDetailReasonUnverified         LinkedBankAccountStatusDetailReason = "unverified"
	LinkedBankAccountStatusDetailReasonInReview           LinkedBankAccountStatusDetailReason = "in_review"
	LinkedBankAccountStatusDetailReasonPending            LinkedBankAccountStatusDetailReason = "pending"
	LinkedBankAccountStatusDetailReasonStuck              LinkedBankAccountStatusDetailReason = "stuck"
	LinkedBankAccountStatusDetailReasonVerified           LinkedBankAccountStatusDetailReason = "verified"
	LinkedBankAccountStatusDetailReasonFailedVerification LinkedBankAccountStatusDetailReason = "failed_verification"
	LinkedBankAccountStatusDetailReasonDisabled           LinkedBankAccountStatusDetailReason = "disabled"
	LinkedBankAccountStatusDetailReasonNew                LinkedBankAccountStatusDetailReason = "new"
)

func (r LinkedBankAccountStatusDetailReason) IsKnown() bool {
	switch r {
	case LinkedBankAccountStatusDetailReasonUnverified, LinkedBankAccountStatusDetailReasonInReview, LinkedBankAccountStatusDetailReasonPending, LinkedBankAccountStatusDetailReasonStuck, LinkedBankAccountStatusDetailReasonVerified, LinkedBankAccountStatusDetailReasonFailedVerification, LinkedBankAccountStatusDetailReasonDisabled, LinkedBankAccountStatusDetailReasonNew:
		return true
	}
	return false
}

type LinkedBankAccountStatusDetailSource string

const (
	LinkedBankAccountStatusDetailSourceWatchtower LinkedBankAccountStatusDetailSource = "watchtower"
)

func (r LinkedBankAccountStatusDetailSource) IsKnown() bool {
	switch r {
	case LinkedBankAccountStatusDetailSourceWatchtower:
		return true
	}
	return false
}

type MaskedLinkedBankAccountDetails struct {
	// Name of the financial institution.
	InstitutionName string `json:"institution_name" api:"required"`
	// Name of the account holder as it appears on the bank account.
	AccountHolder string `json:"account_holder" api:"required"`
	// Nine-digit ABA routing number for the bank account.
	RoutingNumber string `json:"routing_number" api:"required"`
	// Last four digits of the bank account number.
	AccountMask string                             `json:"account_mask" api:"required"`
	JSON        maskedLinkedBankAccountDetailsJSON `json:"-"`
}

// maskedLinkedBankAccountDetailsJSON contains the JSON metadata for the struct [MaskedLinkedBankAccountDetails]
type maskedLinkedBankAccountDetailsJSON struct {
	InstitutionName apijson.Field
	AccountHolder   apijson.Field
	RoutingNumber   apijson.Field
	AccountMask     apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *MaskedLinkedBankAccountDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r maskedLinkedBankAccountDetailsJSON) RawJSON() string {
	return r.raw
}

type UnmaskedLinkedBankAccountDetails struct {
	// Name of the financial institution.
	InstitutionName string `json:"institution_name" api:"required"`
	// Name of the account holder as it appears on the bank account.
	AccountHolder string `json:"account_holder" api:"required"`
	// Nine-digit ABA routing number for the bank account.
	RoutingNumber string `json:"routing_number" api:"required"`
	// Bank account number.
	AccountNumber string                               `json:"account_number" api:"required"`
	JSON          unmaskedLinkedBankAccountDetailsJSON `json:"-"`
}

// unmaskedLinkedBankAccountDetailsJSON contains the JSON metadata for the struct [UnmaskedLinkedBankAccountDetails]
type unmaskedLinkedBankAccountDetailsJSON struct {
	InstitutionName apijson.Field
	AccountHolder   apijson.Field
	RoutingNumber   apijson.Field
	AccountNumber   apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *UnmaskedLinkedBankAccountDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedLinkedBankAccountDetailsJSON) RawJSON() string {
	return r.raw
}

type LinkedBankAccountNewParams struct {
	BankAccount param.Field[LinkedBankAccountNewParamsBankAccount] `json:"bank_account" api:"required"`
	// ID of the account that will own the linked bank account. Omit this field to
	// assign ownership to the platform in the authenticated request context.
	AccountID param.Field[string] `json:"account_id" format:"uuid"`
	// Your description for the linked bank account.
	Description param.Field[string] `json:"description"`
	// Up to 20 user-defined key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// ID of the platform to associate with the linked bank account.
	PlatformID param.Field[string] `json:"platform_id" format:"uuid"`
	// Payment purposes for the linked bank account. Defaults to `charges`, `payouts`,
	// and `billing`.
	Purposes param.Field[[]LinkedBankAccountNewParamsPurpose] `json:"purposes"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

func (r LinkedBankAccountNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LinkedBankAccountNewParamsBankAccount struct {
	// Account holder name as it appears on the bank account. This is usually the
	// business's legal name.
	AccountHolder param.Field[string] `json:"account_holder" api:"required"`
	// The bank account number.
	AccountNumber param.Field[string] `json:"account_number" api:"required"`
	// Nine-digit ABA routing number.
	RoutingNumber param.Field[string] `json:"routing_number" api:"required"`
}

func (r LinkedBankAccountNewParamsBankAccount) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LinkedBankAccountNewParamsPurpose string

const (
	LinkedBankAccountNewParamsPurposeCharges LinkedBankAccountNewParamsPurpose = "charges"
	LinkedBankAccountNewParamsPurposePayouts LinkedBankAccountNewParamsPurpose = "payouts"
	LinkedBankAccountNewParamsPurposeBilling LinkedBankAccountNewParamsPurpose = "billing"
)

func (r LinkedBankAccountNewParamsPurpose) IsKnown() bool {
	switch r {
	case LinkedBankAccountNewParamsPurposeCharges, LinkedBankAccountNewParamsPurposePayouts, LinkedBankAccountNewParamsPurposeBilling:
		return true
	}
	return false
}

type LinkedBankAccountListParams struct {
	// Account ID used to filter the results.
	AccountID param.Field[string] `query:"account_id" format:"uuid"`
	// Scope of linked bank accounts to return.
	Level param.Field[LinkedBankAccountListParamsLevel] `query:"level"`
	// Page number. Defaults to `1`.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results per page. Defaults to `100`. Maximum `1000`.
	PageSize param.Field[int64] `query:"page_size"`
	// Linked bank account purpose. Accepted values are `charges`, `payouts`, and
	// `billing`.
	Purpose param.Field[LinkedBankAccountListParamsPurpose] `query:"purpose"`
	// Field used to sort results. Defaults to `id`.
	SortBy param.Field[string] `query:"sort_by"`
	// Sort direction. Defaults to `asc`.
	SortOrder param.Field[LinkedBankAccountListParamsSortOrder] `query:"sort_order"`
	// Linked bank account status. Accepted values are `created`, `onboarding`,
	// `active`, `rejected`, `inactive`, and `canceled`.
	Status param.Field[LinkedBankAccountListParamsStatus] `query:"status"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

// URLQuery serializes [LinkedBankAccountListParams]'s query parameters as `url.Values`.
func (r LinkedBankAccountListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type LinkedBankAccountListParamsSortOrder string

const (
	LinkedBankAccountListParamsSortOrderAsc  LinkedBankAccountListParamsSortOrder = "asc"
	LinkedBankAccountListParamsSortOrderDesc LinkedBankAccountListParamsSortOrder = "desc"
)

func (r LinkedBankAccountListParamsSortOrder) IsKnown() bool {
	switch r {
	case LinkedBankAccountListParamsSortOrderAsc, LinkedBankAccountListParamsSortOrderDesc:
		return true
	}
	return false
}

type LinkedBankAccountListParamsLevel string

const (
	LinkedBankAccountListParamsLevelAccount  LinkedBankAccountListParamsLevel = "account"
	LinkedBankAccountListParamsLevelPlatform LinkedBankAccountListParamsLevel = "platform"
)

func (r LinkedBankAccountListParamsLevel) IsKnown() bool {
	switch r {
	case LinkedBankAccountListParamsLevelAccount, LinkedBankAccountListParamsLevelPlatform:
		return true
	}
	return false
}

type LinkedBankAccountListParamsPurpose string

const (
	LinkedBankAccountListParamsPurposeCharges LinkedBankAccountListParamsPurpose = "charges"
	LinkedBankAccountListParamsPurposePayouts LinkedBankAccountListParamsPurpose = "payouts"
	LinkedBankAccountListParamsPurposeBilling LinkedBankAccountListParamsPurpose = "billing"
)

func (r LinkedBankAccountListParamsPurpose) IsKnown() bool {
	switch r {
	case LinkedBankAccountListParamsPurposeCharges, LinkedBankAccountListParamsPurposePayouts, LinkedBankAccountListParamsPurposeBilling:
		return true
	}
	return false
}

type LinkedBankAccountListParamsStatus string

const (
	LinkedBankAccountListParamsStatusCreated    LinkedBankAccountListParamsStatus = "created"
	LinkedBankAccountListParamsStatusOnboarding LinkedBankAccountListParamsStatus = "onboarding"
	LinkedBankAccountListParamsStatusActive     LinkedBankAccountListParamsStatus = "active"
	LinkedBankAccountListParamsStatusRejected   LinkedBankAccountListParamsStatus = "rejected"
	LinkedBankAccountListParamsStatusInactive   LinkedBankAccountListParamsStatus = "inactive"
	LinkedBankAccountListParamsStatusCanceled   LinkedBankAccountListParamsStatus = "canceled"
)

func (r LinkedBankAccountListParamsStatus) IsKnown() bool {
	switch r {
	case LinkedBankAccountListParamsStatusCreated, LinkedBankAccountListParamsStatusOnboarding, LinkedBankAccountListParamsStatusActive, LinkedBankAccountListParamsStatusRejected, LinkedBankAccountListParamsStatusInactive, LinkedBankAccountListParamsStatusCanceled:
		return true
	}
	return false
}

type LinkedBankAccountUpdateParams struct {
	BankAccount param.Field[LinkedBankAccountUpdateParamsBankAccount] `json:"bank_account" api:"required"`
	// Up to 20 user-defined key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

func (r LinkedBankAccountUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LinkedBankAccountUpdateParamsBankAccount struct {
	// Account holder name as it appears on the bank account. This is usually the
	// business's legal name.
	AccountHolder param.Field[string] `json:"account_holder" api:"required"`
	// The bank account number.
	AccountNumber param.Field[string] `json:"account_number" api:"required"`
	// Nine-digit ABA routing number.
	RoutingNumber param.Field[string] `json:"routing_number" api:"required"`
}

func (r LinkedBankAccountUpdateParamsBankAccount) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type LinkedBankAccountGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

type LinkedBankAccountListUnmaskedParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

type LinkedBankAccountCancelParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

type LinkedBankAccountPurpose string

const (
	LinkedBankAccountPurposeCharges LinkedBankAccountPurpose = "charges"
	LinkedBankAccountPurposePayouts LinkedBankAccountPurpose = "payouts"
	LinkedBankAccountPurposeBilling LinkedBankAccountPurpose = "billing"
)

func (r LinkedBankAccountPurpose) IsKnown() bool {
	switch r {
	case LinkedBankAccountPurposeCharges, LinkedBankAccountPurposePayouts, LinkedBankAccountPurposeBilling:
		return true
	}
	return false
}
