// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// OrganizationService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewOrganizationService] method instead.
type OrganizationService struct {
	Options []option.RequestOption
}

// NewOrganizationService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewOrganizationService(opts ...option.RequestOption) (r *OrganizationService) {
	r = &OrganizationService{}
	r.Options = opts
	return
}

// Creates an organization for your platform and returns it. Organizations group related accounts and users.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: OrganizationNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OrganizationResponse: Created
//
// Example:
//
//	organization, err := client.Organizations.New(context.Background(), sdk.OrganizationNewParams{
//		Name: sdk.F[string](""),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(organization)
func (r *OrganizationService) New(ctx context.Context, body OrganizationNewParams, opts ...option.RequestOption) (res *OrganizationResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/organizations"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Returns a paginated list of organizations for your platform. Filter the list by name or external ID.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: OrganizationListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OrganizationList: OK
//
// Example:
//
//	organization, err := client.Organizations.List(context.Background(), sdk.OrganizationListParams{
//		PageNumber: sdk.F[int64](1),
//		PageSize:   sdk.F[int64](100),
//		SortBy:     sdk.F[string]("id"),
//		SortOrder:  sdk.F[sdk.OrganizationListParamsSortOrder](sdk.OrganizationListParamsSortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(organization)
func (r *OrganizationService) List(ctx context.Context, query OrganizationListParams, opts ...option.RequestOption) (res *OrganizationList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/organizations"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Returns the organization with the specified ID.
//
// Parameters:
//
//	ctx: Context for the request.
//	organizationID: The ID of the organization.
//	params: OrganizationGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*OrganizationResponse: OK
//
// Example:
//
//	organization, err := client.Organizations.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.OrganizationGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(organization)
func (r *OrganizationService) Get(ctx context.Context, organizationID string, params OrganizationGetParams, opts ...option.RequestOption) (res *OrganizationResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if organizationID == "" {
		err = errors.New("missing required organization_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/organizations/%s", url.PathEscape(organizationID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type OrganizationResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType OrganizationResponseResponseType `json:"response_type" api:"required"`
	Data         Organization                     `json:"data" api:"required"`
	JSON         organizationResponseJSON         `json:"-"`
}

// organizationResponseJSON contains the JSON metadata for the struct [OrganizationResponse]
type organizationResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *OrganizationResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r organizationResponseJSON) RawJSON() string {
	return r.raw
}

type OrganizationResponseResponseType string

const (
	OrganizationResponseResponseTypeObject OrganizationResponseResponseType = "object"
	OrganizationResponseResponseTypeArray  OrganizationResponseResponseType = "array"
	OrganizationResponseResponseTypeError  OrganizationResponseResponseType = "error"
	OrganizationResponseResponseTypeNone   OrganizationResponseResponseType = "none"
)

func (r OrganizationResponseResponseType) IsKnown() bool {
	switch r {
	case OrganizationResponseResponseTypeObject, OrganizationResponseResponseTypeArray, OrganizationResponseResponseTypeError, OrganizationResponseResponseTypeNone:
		return true
	}
	return false
}

type OrganizationList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType OrganizationListResponseType `json:"response_type" api:"required"`
	// Organizations returned for this page.
	Data []Organization       `json:"data" api:"required"`
	JSON organizationListJSON `json:"-"`
}

// organizationListJSON contains the JSON metadata for the struct [OrganizationList]
type organizationListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *OrganizationList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r organizationListJSON) RawJSON() string {
	return r.raw
}

type OrganizationListResponseType string

const (
	OrganizationListResponseTypeObject OrganizationListResponseType = "object"
	OrganizationListResponseTypeArray  OrganizationListResponseType = "array"
	OrganizationListResponseTypeError  OrganizationListResponseType = "error"
	OrganizationListResponseTypeNone   OrganizationListResponseType = "none"
)

func (r OrganizationListResponseType) IsKnown() bool {
	switch r {
	case OrganizationListResponseTypeObject, OrganizationListResponseTypeArray, OrganizationListResponseTypeError, OrganizationListResponseTypeNone:
		return true
	}
	return false
}

type Organization struct {
	// Straddle's unique ID for the organization.
	ID string `json:"id" api:"required" format:"uuid"`
	// The name of the organization.
	Name string `json:"name" api:"required"`
	// Date and time when Straddle created the organization.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Date and time of the most recent organization update.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Your unique ID for the organization.
	ExternalID string `json:"external_id" api:"nullable"`
	// Up to 20 user-defined key-value pairs.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	JSON     organizationJSON  `json:"-"`
}

// organizationJSON contains the JSON metadata for the struct [Organization]
type organizationJSON struct {
	ID          apijson.Field
	Name        apijson.Field
	CreatedAt   apijson.Field
	UpdatedAt   apijson.Field
	ExternalID  apijson.Field
	Metadata    apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *Organization) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r organizationJSON) RawJSON() string {
	return r.raw
}

type OrganizationNewParams struct {
	// Organization name.
	Name param.Field[string] `json:"name" api:"required"`
	// Your unique ID for the organization.
	ExternalID param.Field[string] `json:"external_id"`
	// Up to 20 user-defined key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

func (r OrganizationNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type OrganizationListParams struct {
	// Your external ID for the organization.
	ExternalID param.Field[string] `query:"external_id"`
	// Organization name. Supports partial matches.
	Name param.Field[string] `query:"name"`
	// Page number. Defaults to `1`.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results per page. Defaults to `100`. Maximum `1000`.
	PageSize param.Field[int64] `query:"page_size"`
	// Field used to sort results. Defaults to `id`.
	SortBy param.Field[string] `query:"sort_by"`
	// Sort direction. Defaults to `asc`.
	SortOrder param.Field[OrganizationListParamsSortOrder] `query:"sort_order"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

// URLQuery serializes [OrganizationListParams]'s query parameters as `url.Values`.
func (r OrganizationListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type OrganizationListParamsSortOrder string

const (
	OrganizationListParamsSortOrderAsc  OrganizationListParamsSortOrder = "asc"
	OrganizationListParamsSortOrderDesc OrganizationListParamsSortOrder = "desc"
)

func (r OrganizationListParamsSortOrder) IsKnown() bool {
	switch r {
	case OrganizationListParamsSortOrderAsc, OrganizationListParamsSortOrderDesc:
		return true
	}
	return false
}

type OrganizationGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}
