// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// PaykeyService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPaykeyService] method instead.
type PaykeyService struct {
	Options []option.RequestOption
	Review  *PaykeyReviewService
}

// NewPaykeyService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPaykeyService(opts ...option.RequestOption) (r *PaykeyService) {
	r = &PaykeyService{}
	r.Options = opts
	r.Review = NewPaykeyReviewService(opts...)
	return
}

// Returns a paykey by `id`, including the masked paykey value and bank account details.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	params: PaykeyGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyResponse: OK
//
// Example:
//
//	paykey, err := client.Paykeys.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) Get(ctx context.Context, id string, params PaykeyGetParams, opts ...option.RequestOption) (res *PaykeyResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Returns a paykey by `id`, including the full paykey value and unmasked bank account details. Straddle must enable this endpoint for your account. Use this endpoint only when unmasked data is necessary.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	params: PaykeyListUnmaskedParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*UnmaskedPaykeyResponse: OK
//
// Example:
//
//	paykey, err := client.Paykeys.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyListUnmaskedParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) ListUnmasked(ctx context.Context, id string, params PaykeyListUnmaskedParams, opts ...option.RequestOption) (res *UnmaskedPaykeyResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/unmasked", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Returns a paginated list of paykeys for the account. Optional query parameters filter, search, and sort the results.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PaykeyListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeySummaryList: OK
//
// Example:
//
//	paykey, err := client.Paykeys.List(context.Background(), sdk.PaykeyListParams{
//		PageNumber: sdk.F[int64](1),
//		PageSize:   sdk.F[int64](100),
//		SortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) List(ctx context.Context, query PaykeyListParams, opts ...option.RequestOption) (res *PaykeySummaryList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	if query.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", query.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/paykeys"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Returns a paykey by `id`, including the full paykey value and masked bank account details.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	params: PaykeyRevealParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*RevealedPaykeyResponse: OK
//
// Example:
//
//	paykey, err := client.Paykeys.Reveal(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRevealParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) Reveal(ctx context.Context, id string, params PaykeyRevealParams, opts ...option.RequestOption) (res *RevealedPaykeyResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/reveal", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Cancels a paykey so it cannot be used for new payments.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	body: PaykeyCancelParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyResponse: OK
//
// Example:
//
//	paykey, err := client.Paykeys.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyCancelParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) Cancel(ctx context.Context, id string, body PaykeyCancelParams, opts ...option.RequestOption) (res *PaykeyResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/cancel", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Starts a new verification review for a paykey. The review runs asynchronously. Webhooks and the paykey review endpoint return updated results.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	params: PaykeyRefreshReviewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyResponse: Accepted
//
// Example:
//
//	paykey, err := client.Paykeys.RefreshReview(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRefreshReviewParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) RefreshReview(ctx context.Context, id string, params PaykeyRefreshReviewParams, opts ...option.RequestOption) (res *PaykeyResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", params.IdempotencyKey.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/refresh_review", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, nil, &res, opts...)
	return res, err
}

// Starts an asynchronous balance refresh for a paykey. The response returns the paykey before the refresh finishes.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	params: PaykeyRefreshBalanceParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyResponse: Accepted
//
// Example:
//
//	paykey, err := client.Paykeys.RefreshBalance(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRefreshBalanceParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) RefreshBalance(ctx context.Context, id string, params PaykeyRefreshBalanceParams, opts ...option.RequestOption) (res *PaykeyResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", params.IdempotencyKey.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/refresh_balance", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, nil, &res, opts...)
	return res, err
}

// Unblocks a paykey that was blocked by an `R29` return. The paykey must not have been unblocked before.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	body: PaykeyUnblockParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyResponse: OK
//
// Example:
//
//	paykey, err := client.Paykeys.Unblock(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyUnblockParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(paykey)
func (r *PaykeyService) Unblock(ctx context.Context, id string, body PaykeyUnblockParams, opts ...option.RequestOption) (res *PaykeyResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/unblock", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

type UnmaskedPaykeyResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType               `json:"response_type" api:"required"`
	Data         UnmaskedPaykey             `json:"data" api:"required"`
	JSON         unmaskedPaykeyResponseJSON `json:"-"`
}

// unmaskedPaykeyResponseJSON contains the JSON metadata for the struct [UnmaskedPaykeyResponse]
type unmaskedPaykeyResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedPaykeyResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedPaykeyResponseJSON) RawJSON() string {
	return r.raw
}

type PaykeySummaryList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType `json:"response_type" api:"required"`
	// The `data` field contains the paykeys on this page.
	Data []PaykeySummary       `json:"data" api:"required"`
	JSON paykeySummaryListJSON `json:"-"`
}

// paykeySummaryListJSON contains the JSON metadata for the struct [PaykeySummaryList]
type paykeySummaryListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *PaykeySummaryList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeySummaryListJSON) RawJSON() string {
	return r.raw
}

type UnmaskedPaykey struct {
	// Unique identifier for the paykey.
	ID string `json:"id" api:"required" format:"uuid"`
	// Human-readable label for the paykey.
	Label  string       `json:"label" api:"required"`
	Source PaykeySource `json:"source" api:"required"`
	Status PaykeyStatus `json:"status" api:"required"`
	// Timestamp of when the paykey was created.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp of the most recent update to the paykey.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Full paykey value for creating payments. Store this value securely.
	Paykey string              `json:"paykey" api:"required"`
	Config PaykeyConfiguration `json:"config" api:"required"`
	// Unique identifier for the customer associated with the paykey.
	CustomerID string `json:"customer_id" api:"nullable" format:"uuid"`
	// Name of the financial institution.
	InstitutionName string               `json:"institution_name" api:"nullable"`
	StatusDetails   PaymentStatusDetails `json:"status_details"`
	// Expiration date and time of the paykey, if applicable.
	ExpiresAt time.Time                 `json:"expires_at" api:"nullable" format:"date-time"`
	BankData  UnmaskedPaykeyBankDetails `json:"bank_data"`
	// Up to 20 user-defined key-value pairs associated with the paykey.
	Metadata map[string]string    `json:"metadata" api:"nullable"`
	Balance  PaykeyBalanceDetails `json:"balance"`
	// Unique identifier for the paykey in your system.
	ExternalID string             `json:"external_id" api:"nullable"`
	JSON       unmaskedPaykeyJSON `json:"-"`
}

// unmaskedPaykeyJSON contains the JSON metadata for the struct [UnmaskedPaykey]
type unmaskedPaykeyJSON struct {
	ID              apijson.Field
	Label           apijson.Field
	Source          apijson.Field
	Status          apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	Paykey          apijson.Field
	Config          apijson.Field
	CustomerID      apijson.Field
	InstitutionName apijson.Field
	StatusDetails   apijson.Field
	ExpiresAt       apijson.Field
	BankData        apijson.Field
	Metadata        apijson.Field
	Balance         apijson.Field
	ExternalID      apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *UnmaskedPaykey) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedPaykeyJSON) RawJSON() string {
	return r.raw
}

type PaykeySummary struct {
	// Unique identifier for the paykey.
	ID string `json:"id" api:"required" format:"uuid"`
	// Display label combining the bank name and masked account number.
	Label  string       `json:"label" api:"required"`
	Source PaykeySource `json:"source" api:"required"`
	Status PaykeyStatus `json:"status" api:"required"`
	// Timestamp of when the paykey was created.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp of the most recent update to the paykey.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Masked paykey value.
	Paykey string              `json:"paykey" api:"required"`
	Config PaykeyConfiguration `json:"config" api:"required"`
	// Unique identifier for the customer associated with the paykey.
	CustomerID string `json:"customer_id" api:"nullable" format:"uuid"`
	// Name of the financial institution.
	InstitutionName string               `json:"institution_name" api:"nullable"`
	StatusDetails   PaymentStatusDetails `json:"status_details"`
	// Expiration date and time of the paykey, if applicable.
	ExpiresAt time.Time         `json:"expires_at" api:"nullable" format:"date-time"`
	BankData  PaykeyBankDetails `json:"bank_data"`
	// Unique identifier for the paykey in your system.
	ExternalID string `json:"external_id" api:"nullable"`
	// Whether the paykey is eligible for client-initiated unblocking. `true` only when
	// the paykey is blocked by an `R29` return and has not been unblocked before.
	// `false` for other blocked paykeys. `null` when the paykey is not blocked.
	UnblockEligible bool              `json:"unblock_eligible" api:"nullable"`
	JSON            paykeySummaryJSON `json:"-"`
}

// paykeySummaryJSON contains the JSON metadata for the struct [PaykeySummary]
type paykeySummaryJSON struct {
	ID              apijson.Field
	Label           apijson.Field
	Source          apijson.Field
	Status          apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	Paykey          apijson.Field
	Config          apijson.Field
	CustomerID      apijson.Field
	InstitutionName apijson.Field
	StatusDetails   apijson.Field
	ExpiresAt       apijson.Field
	BankData        apijson.Field
	ExternalID      apijson.Field
	UnblockEligible apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *PaykeySummary) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeySummaryJSON) RawJSON() string {
	return r.raw
}

type UnmaskedPaykeyBankDetails struct {
	// Bank routing number.
	RoutingNumber string `json:"routing_number" api:"required"`
	// Bank account number.
	AccountNumber string                        `json:"account_number" api:"required"`
	AccountType   AccountType                   `json:"account_type" api:"required"`
	JSON          unmaskedPaykeyBankDetailsJSON `json:"-"`
}

// unmaskedPaykeyBankDetailsJSON contains the JSON metadata for the struct [UnmaskedPaykeyBankDetails]
type unmaskedPaykeyBankDetailsJSON struct {
	RoutingNumber apijson.Field
	AccountNumber apijson.Field
	AccountType   apijson.Field
	raw           string
	ExtraFields   map[string]apijson.Field
}

func (r *UnmaskedPaykeyBankDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedPaykeyBankDetailsJSON) RawJSON() string {
	return r.raw
}

type PaykeyGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PaykeyListUnmaskedParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PaykeyListParams struct {
	// Start date for filtering by creation date.
	CreatedFrom param.Field[time.Time] `query:"created_from" format:"date-time"`
	// End date for filtering by creation date.
	CreatedTo param.Field[time.Time] `query:"created_to" format:"date-time"`
	// Filter paykeys by related customer ID.
	CustomerID param.Field[string] `query:"customer_id" format:"uuid"`
	// Page number for paginated results. Starts at 1.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results per page. Maximum: 1000.
	PageSize param.Field[int64] `query:"page_size"`
	// General search term to filter paykeys.
	SearchText param.Field[string] `query:"search_text"`
	// Field used to sort the results.
	SortBy param.Field[PaykeyListParamsSortBy] `query:"sort_by"`
	// Order in which to sort the results.
	SortOrder param.Field[SortOrder] `query:"sort_order"`
	// Filter paykeys by their source.
	Source param.Field[[]PaykeySource] `query:"source"`
	// Filter paykeys by their current status.
	Status param.Field[[]PaykeyStatus] `query:"status"`
	// Filters paykeys by unblock eligibility. `true` returns blocked paykeys that are
	// eligible because of an `R29` return and have not been unblocked before. `false`
	// returns blocked paykeys that are not eligible.
	UnblockEligible param.Field[bool] `query:"unblock_eligible"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

// URLQuery serializes [PaykeyListParams]'s query parameters as `url.Values`.
func (r PaykeyListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PaykeyListParamsSortBy string

const (
	PaykeyListParamsSortByInstitutionName PaykeyListParamsSortBy = "institution_name"
	PaykeyListParamsSortByExpiresAt       PaykeyListParamsSortBy = "expires_at"
	PaykeyListParamsSortByCreatedAt       PaykeyListParamsSortBy = "created_at"
)

func (r PaykeyListParamsSortBy) IsKnown() bool {
	switch r {
	case PaykeyListParamsSortByInstitutionName, PaykeyListParamsSortByExpiresAt, PaykeyListParamsSortByCreatedAt:
		return true
	}
	return false
}

type PaykeyRevealParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PaykeyCancelParams struct {
	// Reason for canceling the paykey.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PaykeyCancelParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PaykeyRefreshReviewParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PaykeyRefreshBalanceParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PaykeyUnblockParams struct {
	// Optional message describing the reason for unblocking.
	Message param.Field[string] `json:"message"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PaykeyUnblockParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}
