// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// PaykeyReviewService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPaykeyReviewService] method instead.
type PaykeyReviewService struct {
	Options []option.RequestOption
}

// NewPaykeyReviewService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPaykeyReviewService(opts ...option.RequestOption) (r *PaykeyReviewService) {
	r = &PaykeyReviewService{}
	r.Options = opts
	return
}

// Updates the verification decision for a paykey. The paykey's current `status` must be `review`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	body: PaykeyReviewSetVerificationDecisionParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyResponse: OK
//
// Example:
//
//	review, err := client.Paykeys.Review.SetVerificationDecision(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyReviewSetVerificationDecisionParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(review)
func (r *PaykeyReviewService) SetVerificationDecision(ctx context.Context, id string, body PaykeyReviewSetVerificationDecisionParams, opts ...option.RequestOption) (res *PaykeyResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/review", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPatch, path, body, &res, opts...)
	return res, err
}

// Returns a paykey verification review, including the decision, score breakdowns, and result codes.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the paykey.
//	params: PaykeyReviewListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaykeyReviewResponse: OK
//
// Example:
//
//	review, err := client.Paykeys.Review.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyReviewListParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(review)
func (r *PaykeyReviewService) List(ctx context.Context, id string, params PaykeyReviewListParams, opts ...option.RequestOption) (res *PaykeyReviewResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/paykeys/%s/review", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type PaykeyReviewResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType             `json:"response_type" api:"required"`
	Data         PaykeyReview             `json:"data" api:"required"`
	JSON         paykeyReviewResponseJSON `json:"-"`
}

// paykeyReviewResponseJSON contains the JSON metadata for the struct [PaykeyReviewResponse]
type paykeyReviewResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *PaykeyReviewResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeyReviewResponseJSON) RawJSON() string {
	return r.raw
}

type PaykeyReview struct {
	PaykeyDetails       Paykey                    `json:"paykey_details" api:"required"`
	VerificationDetails PaykeyVerificationDetails `json:"verification_details"`
	JSON                paykeyReviewJSON          `json:"-"`
}

// paykeyReviewJSON contains the JSON metadata for the struct [PaykeyReview]
type paykeyReviewJSON struct {
	PaykeyDetails       apijson.Field
	VerificationDetails apijson.Field
	raw                 string
	ExtraFields         map[string]apijson.Field
}

func (r *PaykeyReview) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeyReviewJSON) RawJSON() string {
	return r.raw
}

type PaykeyVerificationDetails struct {
	// Unique identifier for the verification details.
	ID       string                   `json:"id" api:"required" format:"uuid"`
	Decision PaykeyVerificationResult `json:"decision" api:"required"`
	// Messages returned by the paykey verification process.
	Messages  map[string]string           `json:"messages" api:"required"`
	Breakdown PaykeyVerificationBreakdown `json:"breakdown" api:"required"`
	// Timestamp of when the verification was initiated.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp of the most recent update to the verification details.
	UpdatedAt time.Time                     `json:"updated_at" api:"required" format:"date-time"`
	JSON      paykeyVerificationDetailsJSON `json:"-"`
}

// paykeyVerificationDetailsJSON contains the JSON metadata for the struct [PaykeyVerificationDetails]
type paykeyVerificationDetailsJSON struct {
	ID          apijson.Field
	Decision    apijson.Field
	Messages    apijson.Field
	Breakdown   apijson.Field
	CreatedAt   apijson.Field
	UpdatedAt   apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *PaykeyVerificationDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeyVerificationDetailsJSON) RawJSON() string {
	return r.raw
}

type PaykeyVerificationResult string

const (
	PaykeyVerificationResultAccept PaykeyVerificationResult = "accept"
	PaykeyVerificationResultReject PaykeyVerificationResult = "reject"
	PaykeyVerificationResultReview PaykeyVerificationResult = "review"
)

func (r PaykeyVerificationResult) IsKnown() bool {
	switch r {
	case PaykeyVerificationResultAccept, PaykeyVerificationResultReject, PaykeyVerificationResultReview:
		return true
	}
	return false
}

type PaykeyVerificationBreakdown struct {
	NameMatch         AccountNameMatchDetails         `json:"name_match"`
	AccountValidation AccountValidationDetails        `json:"account_validation"`
	JSON              paykeyVerificationBreakdownJSON `json:"-"`
}

// paykeyVerificationBreakdownJSON contains the JSON metadata for the struct [PaykeyVerificationBreakdown]
type paykeyVerificationBreakdownJSON struct {
	NameMatch         apijson.Field
	AccountValidation apijson.Field
	raw               string
	ExtraFields       map[string]apijson.Field
}

func (r *PaykeyVerificationBreakdown) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paykeyVerificationBreakdownJSON) RawJSON() string {
	return r.raw
}

type AccountNameMatchDetails struct {
	Decision PaykeyVerificationResult `json:"decision" api:"required"`
	// Result codes returned by the name-match check.
	Codes []string `json:"codes" api:"required"`
	// Account-holder names returned by the financial institution.
	NamesOnAccount []string `json:"names_on_account" api:"nullable"`
	// Account-holder name that matched the customer record.
	MatchedName string `json:"matched_name" api:"nullable"`
	// Customer name evaluated during account verification.
	CustomerName string `json:"customer_name" api:"nullable"`
	// Strength of the match between the customer name and account-holder names.
	CorrelationScore float64 `json:"correlation_score" api:"nullable"`
	// Reason for the name-match decision.
	Reason string                      `json:"reason" api:"nullable"`
	JSON   accountNameMatchDetailsJSON `json:"-"`
}

// accountNameMatchDetailsJSON contains the JSON metadata for the struct [AccountNameMatchDetails]
type accountNameMatchDetailsJSON struct {
	Decision         apijson.Field
	Codes            apijson.Field
	NamesOnAccount   apijson.Field
	MatchedName      apijson.Field
	CustomerName     apijson.Field
	CorrelationScore apijson.Field
	Reason           apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *AccountNameMatchDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountNameMatchDetailsJSON) RawJSON() string {
	return r.raw
}

type AccountValidationDetails struct {
	Decision PaykeyVerificationResult `json:"decision" api:"required"`
	// Result codes returned by the account-validation check.
	Codes []string `json:"codes" api:"required"`
	// Reason for the account-validation decision.
	Reason string                       `json:"reason" api:"nullable"`
	JSON   accountValidationDetailsJSON `json:"-"`
}

// accountValidationDetailsJSON contains the JSON metadata for the struct [AccountValidationDetails]
type accountValidationDetailsJSON struct {
	Decision    apijson.Field
	Codes       apijson.Field
	Reason      apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *AccountValidationDetails) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r accountValidationDetailsJSON) RawJSON() string {
	return r.raw
}

type PaykeyReviewSetVerificationDecisionParams struct {
	Status param.Field[PaykeyReviewSetVerificationDecisionParamsStatus] `json:"status" api:"required"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PaykeyReviewSetVerificationDecisionParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PaykeyReviewSetVerificationDecisionParamsStatus string

const (
	PaykeyReviewSetVerificationDecisionParamsStatusActive   PaykeyReviewSetVerificationDecisionParamsStatus = "active"
	PaykeyReviewSetVerificationDecisionParamsStatusRejected PaykeyReviewSetVerificationDecisionParamsStatus = "rejected"
)

func (r PaykeyReviewSetVerificationDecisionParamsStatus) IsKnown() bool {
	switch r {
	case PaykeyReviewSetVerificationDecisionParamsStatusActive, PaykeyReviewSetVerificationDecisionParamsStatusRejected:
		return true
	}
	return false
}

type PaykeyReviewListParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}
