// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// PaymentService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPaymentService] method instead.
type PaymentService struct {
	Options []option.RequestOption
}

// NewPaymentService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPaymentService(opts ...option.RequestOption) (r *PaymentService) {
	r = &PaymentService{}
	r.Options = opts
	return
}

// Returns a paged list of charges and payouts that match the filters.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: PaymentListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PaymentSummaryList: OK
//
// Example:
//
//	payment, err := client.Payments.List(context.Background(), sdk.PaymentListParams{
//		DefaultSort:      sdk.F[sdk.PaymentListParamsDefaultSort](sdk.PaymentListParamsDefaultSort("id")),
//		DefaultSortOrder: sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
//		PageNumber:       sdk.F[int64](1),
//		PageSize:         sdk.F[int64](100),
//		SortBy:           sdk.F[sdk.PaymentListParamsSortBy](sdk.PaymentListParamsSortBy("id")),
//		SortOrder:        sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payment)
func (r *PaymentService) List(ctx context.Context, query PaymentListParams, opts ...option.RequestOption) (res *PaymentSummaryList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	if query.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", query.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/payments"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

type PaymentSummaryList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType `json:"response_type" api:"required"`
	// Payments returned for this page.
	Data []PaymentSummary       `json:"data" api:"required"`
	JSON paymentSummaryListJSON `json:"-"`
}

// paymentSummaryListJSON contains the JSON metadata for the struct [PaymentSummaryList]
type paymentSummaryListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *PaymentSummaryList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paymentSummaryListJSON) RawJSON() string {
	return r.raw
}

type PaymentSummary struct {
	// Unique identifier for this charge or payout.
	ID string `json:"id" api:"required" format:"uuid"`
	// Whether this payment is a charge or payout.
	PaymentType PaymentType `json:"payment_type" api:"required"`
	// Date when Straddle submits the payment for processing.
	PaymentDate time.Time `json:"payment_date" api:"required" format:"date"`
	// Human-readable description of the payment.
	Description string `json:"description" api:"required,nullable"`
	// Your unique identifier for the charge or payout.
	ExternalID string `json:"external_id" api:"required"`
	// Amount in cents.
	Amount int64 `json:"amount" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency string `json:"currency" api:"required"`
	// Masked paykey token used for the charge or payout.
	Paykey string `json:"paykey" api:"required"`
	// Current status of the charge or payout.
	Status PaymentStatus `json:"status" api:"required"`
	// Reason, source, and message for the most recent status change.
	StatusDetails PaymentStatusDetails `json:"status_details" api:"required"`
	// Timestamp when the charge or payout was created.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Timestamp when the charge or payout was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// IDs of the funding events that included this payment.
	FundingIDs []string `json:"funding_ids" api:"required" format:"uuid"`
	// Network-level trace identifiers assigned during processing. Keys vary by payment
	// rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Whether this payment is a payout that refunds an original charge.
	IsRefund bool `json:"is_refund" api:"required"`
	// Whether this payment is a charge refunded by an associated payout.
	HasRefund bool `json:"has_refund" api:"required"`
	// Whether this payment resubmits an original payment.
	IsResubmit bool `json:"is_resubmit" api:"required"`
	// Whether this payment has been resubmitted.
	HasResubmit bool `json:"has_resubmit" api:"required"`
	// Timestamp when funds settled. Null until settlement is confirmed.
	EffectiveAt time.Time `json:"effective_at" api:"nullable" format:"date-time"`
	// Information about the customer associated with the charge or payout.
	CustomerDetails CustomerDetails `json:"customer_details"`
	// Details of the paykey used for the charge or payout.
	PaykeyDetails PaykeyDetails `json:"paykey_details"`
	// Unique identifier for the funding event associated with the `charge` or
	// `payout`.
	FundingID string `json:"funding_id" api:"nullable" format:"uuid"`
	// Key-value metadata for the payment. Included only when `include_metadata` is
	// true.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	// Related payments and their relationship to this charge or payout.
	RelatedPayments []RelatedPayment   `json:"related_payments" api:"nullable"`
	JSON            paymentSummaryJSON `json:"-"`
}

// paymentSummaryJSON contains the JSON metadata for the struct [PaymentSummary]
type paymentSummaryJSON struct {
	ID              apijson.Field
	PaymentType     apijson.Field
	PaymentDate     apijson.Field
	Description     apijson.Field
	ExternalID      apijson.Field
	Amount          apijson.Field
	Currency        apijson.Field
	Paykey          apijson.Field
	Status          apijson.Field
	StatusDetails   apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	FundingIDs      apijson.Field
	TraceIDs        apijson.Field
	IsRefund        apijson.Field
	HasRefund       apijson.Field
	IsResubmit      apijson.Field
	HasResubmit     apijson.Field
	EffectiveAt     apijson.Field
	CustomerDetails apijson.Field
	PaykeyDetails   apijson.Field
	FundingID       apijson.Field
	Metadata        apijson.Field
	RelatedPayments apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *PaymentSummary) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r paymentSummaryJSON) RawJSON() string {
	return r.raw
}

type PaymentListParams struct {
	// Filter by the unique identifier of the customer.
	CustomerID param.Field[string] `query:"customer_id" format:"uuid"`
	// Default number of results returned per page.
	DefaultPageSize param.Field[int64] `query:"default_page_size"`
	// Default field used to sort the results.
	DefaultSort param.Field[PaymentListParamsDefaultSort] `query:"default_sort"`
	// Default order in which to sort the results.
	DefaultSortOrder param.Field[SortOrder] `query:"default_sort_order"`
	// Filter by your external identifier for the payment.
	ExternalID param.Field[string] `query:"external_id"`
	// Filter by the unique identifier of a funding event.
	FundingID param.Field[string] `query:"funding_id" format:"uuid"`
	// Filter charges by whether an associated payout has refunded them.
	HasRefund param.Field[bool] `query:"has_refund"`
	// Filter payments by whether they have been resubmitted.
	HasResubmit param.Field[bool] `query:"has_resubmit"`
	// Whether to include metadata in each returned payment. Defaults to false.
	IncludeMetadata param.Field[bool] `query:"include_metadata"`
	// Filter payouts by whether they refund an original charge.
	IsRefund param.Field[bool] `query:"is_refund"`
	// Filter payments by whether they resubmit an original payment.
	IsResubmit param.Field[bool] `query:"is_resubmit"`
	// Filter to payments with an amount in cents less than or equal to this value.
	MaxAmount param.Field[int64] `query:"max_amount"`
	// Filter to payments created at or before this timestamp.
	MaxCreatedAt param.Field[time.Time] `query:"max_created_at" format:"date-time"`
	// Filter to payments effective at or before this timestamp.
	MaxEffectiveAt param.Field[time.Time] `query:"max_effective_at" format:"date-time"`
	// Filter to payments with a payment date on or before this date.
	MaxPaymentDate param.Field[time.Time] `query:"max_payment_date" format:"date"`
	// Filter to payments last updated on or before this timestamp.
	MaxUpdatedAt param.Field[time.Time] `query:"max_updated_at" format:"date-time"`
	// Filter to payments with an amount in cents greater than or equal to this value.
	MinAmount param.Field[int64] `query:"min_amount"`
	// Filter to payments created at or after this timestamp.
	MinCreatedAt param.Field[time.Time] `query:"min_created_at" format:"date-time"`
	// Filter to payments effective at or after this timestamp.
	MinEffectiveAt param.Field[time.Time] `query:"min_effective_at" format:"date-time"`
	// Filter to payments with a payment date on or after this date.
	MinPaymentDate param.Field[time.Time] `query:"min_payment_date" format:"date"`
	// Filter to payments last updated on or after this timestamp.
	MinUpdatedAt param.Field[time.Time] `query:"min_updated_at" format:"date-time"`
	// Page number to return.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results to return per page.
	PageSize param.Field[int64] `query:"page_size"`
	// Filter by the paykey token.
	Paykey param.Field[string] `query:"paykey"`
	// Filter by the unique identifier of the paykey.
	PaykeyID param.Field[string] `query:"paykey_id" format:"uuid"`
	// Filter by the payment's unique identifier.
	PaymentID param.Field[string] `query:"payment_id" format:"uuid"`
	// Filter by payment status.
	PaymentStatus param.Field[[]PaymentStatus] `query:"payment_status"`
	// Filter by payment type.
	PaymentType param.Field[[]PaymentType] `query:"payment_type"`
	// Free-text search across payment fields.
	SearchText param.Field[string] `query:"search_text"`
	// Field used to sort the results.
	SortBy param.Field[PaymentListParamsSortBy] `query:"sort_by"`
	// Order in which to sort the results.
	SortOrder param.Field[SortOrder] `query:"sort_order"`
	// Filter by the reason for the most recent payment status change.
	StatusReason param.Field[[]PaymentStatusReason] `query:"status_reason"`
	// Filter by the source of the most recent payment status change.
	StatusSource param.Field[[]PaymentStatusSource] `query:"status_source"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

// URLQuery serializes [PaymentListParams]'s query parameters as `url.Values`.
func (r PaymentListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type PaymentListParamsSortBy string

const (
	PaymentListParamsSortByCreatedAt   PaymentListParamsSortBy = "created_at"
	PaymentListParamsSortByPaymentDate PaymentListParamsSortBy = "payment_date"
	PaymentListParamsSortByEffectiveAt PaymentListParamsSortBy = "effective_at"
	PaymentListParamsSortByID          PaymentListParamsSortBy = "id"
	PaymentListParamsSortByAmount      PaymentListParamsSortBy = "amount"
	PaymentListParamsSortByUpdatedAt   PaymentListParamsSortBy = "updated_at"
)

func (r PaymentListParamsSortBy) IsKnown() bool {
	switch r {
	case PaymentListParamsSortByCreatedAt, PaymentListParamsSortByPaymentDate, PaymentListParamsSortByEffectiveAt, PaymentListParamsSortByID, PaymentListParamsSortByAmount, PaymentListParamsSortByUpdatedAt:
		return true
	}
	return false
}

type PaymentListParamsDefaultSort string

const (
	PaymentListParamsDefaultSortCreatedAt   PaymentListParamsDefaultSort = "created_at"
	PaymentListParamsDefaultSortPaymentDate PaymentListParamsDefaultSort = "payment_date"
	PaymentListParamsDefaultSortEffectiveAt PaymentListParamsDefaultSort = "effective_at"
	PaymentListParamsDefaultSortID          PaymentListParamsDefaultSort = "id"
	PaymentListParamsDefaultSortAmount      PaymentListParamsDefaultSort = "amount"
	PaymentListParamsDefaultSortUpdatedAt   PaymentListParamsDefaultSort = "updated_at"
)

func (r PaymentListParamsDefaultSort) IsKnown() bool {
	switch r {
	case PaymentListParamsDefaultSortCreatedAt, PaymentListParamsDefaultSortPaymentDate, PaymentListParamsDefaultSortEffectiveAt, PaymentListParamsDefaultSortID, PaymentListParamsDefaultSortAmount, PaymentListParamsDefaultSortUpdatedAt:
		return true
	}
	return false
}
