// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apiform"
	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// PayoutService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewPayoutService] method instead.
type PayoutService struct {
	Options []option.RequestOption
}

// NewPayoutService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewPayoutService(opts ...option.RequestOption) (r *PayoutService) {
	r = &PayoutService{}
	r.Options = opts
	return
}

// Returns a payout by its unique identifier.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	params: PayoutGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: OK
//
// Example:
//
//	payout, err := client.Payouts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) Get(ctx context.Context, id string, params PayoutGetParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Updates the description, amount, `payment_date`, or metadata. The payout must have a status of `created` or `on_hold`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	body: PayoutUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: OK
//
// Example:
//
//	payout, err := client.Payouts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutUpdateParams{
//		Amount:      sdk.F[int64](10000),
//		Description: sdk.F[string](""),
//		PaymentDate: sdk.F[time.Time](time.Now()),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) Update(ctx context.Context, id string, body PayoutUpdateParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Creates a payout to a customer's bank account. Straddle submits the payout for processing on `payment_date` unless the payout is on hold.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: PayoutNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: Created
//
// Example:
//
//	payout, err := client.Payouts.New(context.Background(), sdk.PayoutNewParams{
//		Amount:      sdk.F[int64](10000),
//		Currency:    sdk.F[string](""),
//		Description: sdk.F[string]("Vendor invoice payment"),
//		Device: sdk.F[sdk.PaymentDeviceParam](sdk.PaymentDeviceParam{
//			IPAddress: sdk.F[string]("192.168.1.1"),
//		}),
//		ExternalID:  sdk.F[string](""),
//		Paykey:      sdk.F[string](""),
//		PaymentDate: sdk.F[time.Time](time.Now()),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) New(ctx context.Context, body PayoutNewParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/payouts"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Places a payout on hold to prevent submission for processing. The payout must have a status of `created` or `scheduled`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	body: PayoutHoldParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: OK
//
// Example:
//
//	payout, err := client.Payouts.Hold(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutHoldParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) Hold(ctx context.Context, id string, body PayoutHoldParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s/hold", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Releases a payout from `on_hold` and returns it to `created` for submission on `payment_date`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	body: PayoutReleaseParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: OK
//
// Example:
//
//	payout, err := client.Payouts.Release(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutReleaseParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) Release(ctx context.Context, id string, body PayoutReleaseParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s/release", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Cancels a payout. The payout must have a status of `created`, `scheduled`, or `on_hold`.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	body: PayoutCancelParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: OK
//
// Example:
//
//	payout, err := client.Payouts.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutCancelParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) Cancel(ctx context.Context, id string, body PayoutCancelParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s/cancel", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Return a payout with its sensitive fields unmasked.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	params: PayoutListUnmaskedParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*UnmaskedPayoutResponse: OK
//
// Example:
//
//	payout, err := client.Payouts.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutListUnmaskedParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) ListUnmasked(ctx context.Context, id string, params PayoutListUnmaskedParams, opts ...option.RequestOption) (res *UnmaskedPayoutResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	if params.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", params.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s/unmask", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Creates a new payout from a failed, reversed, or cancelled payout. The request can override `description`, `external_id`, and `payment_date`. Other payment details come from the original payout.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	body: PayoutResubmitParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: Created
//
// Example:
//
//	payout, err := client.Payouts.Resubmit(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutResubmitParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) Resubmit(ctx context.Context, id string, body PayoutResubmitParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s/resubmit", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Uploads a proof-of-authorization document for a payout. A later upload adds another document and does not replace an existing one.
//
// Parameters:
//
//	ctx: Context for the request.
//	id: Unique identifier for the payout.
//	body: PayoutUploadAuthorizationProofParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*PayoutResponse: Created
//
// Example:
//
//	payout, err := client.Payouts.UploadAuthorizationProof(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutUploadAuthorizationProofParams{
//		File: sdk.F[io.Reader](strings.NewReader("")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(payout)
func (r *PayoutService) UploadAuthorizationProof(ctx context.Context, id string, body PayoutUploadAuthorizationProofParams, opts ...option.RequestOption) (res *PayoutResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	if body.StraddleAccountID.Present {
		opts = append(opts, option.WithHeader("Straddle-Account-Id", fmt.Sprintf("%v", body.StraddleAccountID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if id == "" {
		err = errors.New("missing required id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/payouts/%s/authorization", url.PathEscape(id))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

type UnmaskedPayoutResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Shape of the response envelope. - `object` means `data` contains one JSON
	// object. - `array` means `data` contains an array of JSON objects. - `error`
	// means `error` contains the error details. - `none` means the response contains
	// no data.
	ResponseType ResponseType               `json:"response_type" api:"required"`
	Data         UnmaskedPayout             `json:"data" api:"required"`
	JSON         unmaskedPayoutResponseJSON `json:"-"`
}

// unmaskedPayoutResponseJSON contains the JSON metadata for the struct [UnmaskedPayoutResponse]
type unmaskedPayoutResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedPayoutResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedPayoutResponseJSON) RawJSON() string {
	return r.raw
}

type UnmaskedPayout struct {
	// Unique identifier for this payout.
	ID string `json:"id" api:"required" format:"uuid"`
	// A human-readable description of the payout.
	Description string `json:"description" api:"required,nullable"`
	// Amount in cents.
	Amount int64 `json:"amount" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency string `json:"currency" api:"required"`
	// Date when Straddle submits the payout for processing.
	PaymentDate time.Time     `json:"payment_date" api:"required" format:"date"`
	Device      PaymentDevice `json:"device" api:"required"`
	// Your unique identifier for this payout, used to correlate with your internal
	// records.
	ExternalID string              `json:"external_id" api:"required"`
	Config     PayoutConfiguration `json:"config" api:"required"`
	// The current status of the `charge` or `payout`.
	Status        PaymentStatus        `json:"status" api:"required"`
	StatusDetails PaymentStatusDetails `json:"status_details" api:"required"`
	// Complete ordered history of all status changes for this payout.
	StatusHistory []PaymentStatusHistory `json:"status_history" api:"required"`
	// IDs of the funding events that included this payout.
	FundingIDs []string `json:"funding_ids" api:"required" format:"uuid"`
	// Unmasked paykey token used for this payout.
	Paykey string `json:"paykey" api:"required"`
	// Trace identifiers from the payment network. Keys depend on the payment rail.
	TraceIDs map[string]string `json:"trace_ids" api:"required"`
	// Whether this payout refunds an original charge.
	IsRefund bool `json:"is_refund" api:"required"`
	// Whether this payout resubmits an original payout.
	IsResubmit bool `json:"is_resubmit" api:"required"`
	// Whether this payout has been resubmitted.
	HasResubmit bool `json:"has_resubmit" api:"required"`
	// The payment rail used for the charge or payout.
	PaymentRail PaymentRail `json:"payment_rail"`
	// Information about the customer associated with the charge or payout.
	CustomerDetails CustomerDetails `json:"customer_details"`
	PaykeyDetails   PaykeyDetails   `json:"paykey_details"`
	// Timestamp when this payout was created.
	CreatedAt time.Time `json:"created_at" api:"nullable" format:"date-time"`
	// Timestamp when this payout was last updated.
	UpdatedAt time.Time `json:"updated_at" api:"nullable" format:"date-time"`
	// Timestamp when this payout was submitted to the payment network. Null until
	// processed.
	ProcessedAt time.Time `json:"processed_at" api:"nullable" format:"date-time"`
	// Timestamp when funds were settled. Null until settlement is confirmed.
	EffectiveAt time.Time `json:"effective_at" api:"nullable" format:"date-time"`
	// Key-value metadata stored with this payout.
	Metadata map[string]string `json:"metadata" api:"nullable"`
	// Related payments and their relationship to this payout.
	RelatedPayments []RelatedPayment `json:"related_payments" api:"nullable"`
	// Authorization documents for this payout, ordered by upload time.
	Documents []PaymentAuthorizationProof `json:"documents" api:"nullable"`
	JSON      unmaskedPayoutJSON          `json:"-"`
}

// unmaskedPayoutJSON contains the JSON metadata for the struct [UnmaskedPayout]
type unmaskedPayoutJSON struct {
	ID              apijson.Field
	Description     apijson.Field
	Amount          apijson.Field
	Currency        apijson.Field
	PaymentDate     apijson.Field
	Device          apijson.Field
	ExternalID      apijson.Field
	Config          apijson.Field
	Status          apijson.Field
	StatusDetails   apijson.Field
	StatusHistory   apijson.Field
	FundingIDs      apijson.Field
	Paykey          apijson.Field
	TraceIDs        apijson.Field
	IsRefund        apijson.Field
	IsResubmit      apijson.Field
	HasResubmit     apijson.Field
	PaymentRail     apijson.Field
	CustomerDetails apijson.Field
	PaykeyDetails   apijson.Field
	CreatedAt       apijson.Field
	UpdatedAt       apijson.Field
	ProcessedAt     apijson.Field
	EffectiveAt     apijson.Field
	Metadata        apijson.Field
	RelatedPayments apijson.Field
	Documents       apijson.Field
	raw             string
	ExtraFields     map[string]apijson.Field
}

func (r *UnmaskedPayout) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedPayoutJSON) RawJSON() string {
	return r.raw
}

type PayoutGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PayoutUpdateParams struct {
	// Amount in cents.
	Amount param.Field[int64] `json:"amount" api:"required"`
	// Updated description for the payout.
	Description param.Field[string] `json:"description" api:"required"`
	// New date for Straddle to submit the payout for processing.
	PaymentDate param.Field[time.Time] `json:"payment_date" api:"required" format:"date"`
	// Replacement metadata for the payout. Up to 20 user-defined string key-value
	// pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutNewParams struct {
	// Amount in cents.
	Amount param.Field[int64] `json:"amount" api:"required"`
	// Currency code. Only `USD` is supported.
	Currency param.Field[string] `json:"currency" api:"required"`
	// Description shown on the customer's bank statement where supported.
	Description param.Field[string] `json:"description" api:"required"`
	// Device used when the customer authorized the payout.
	Device param.Field[PaymentDeviceParam] `json:"device" api:"required"`
	// Your unique identifier for the payout. Must be unique across payouts.
	ExternalID param.Field[string] `json:"external_id" api:"required"`
	// The paykey token that identifies the customer's bank account.
	Paykey param.Field[string] `json:"paykey" api:"required"`
	// Date when Straddle submits the payout for processing.
	PaymentDate param.Field[time.Time]                `json:"payment_date" api:"required" format:"date"`
	Config      param.Field[PayoutConfigurationParam] `json:"config"`
	// Up to 20 user-defined string key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutHoldParams struct {
	// Message explaining the payout status change.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutHoldParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutReleaseParams struct {
	// Message explaining the payout status change.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutReleaseParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutCancelParams struct {
	// Message explaining the payout status change.
	Reason param.Field[string] `json:"reason"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutCancelParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutListUnmaskedParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

type PayoutResubmitParams struct {
	// Description for the resubmitted payout. Defaults to the original description if
	// omitted.
	Description param.Field[string] `json:"description"`
	// Your unique identifier for the resubmitted payout. Defaults to a new value if
	// omitted.
	ExternalID param.Field[string] `json:"external_id"`
	// Date when Straddle submits the resubmitted payout for processing. Defaults to
	// today if omitted.
	PaymentDate param.Field[time.Time] `json:"payment_date" format:"date"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutResubmitParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type PayoutUploadAuthorizationProofParams struct {
	// The document file to upload as proof of authorization for this payout. Supported
	// file types are PDF (.pdf), PNG (.png), JPEG (.jpg, .jpeg), Word (.doc), and Word
	// (.docx), with a maximum file size of 10 MiB (10,485,760 bytes). Empty (0-byte)
	// files are rejected. Uploaded files are validated for matching file signatures
	// (magic bytes) and file extension agreement.
	File param.Field[io.Reader] `json:"File" api:"required" format:"binary"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
	// For platform requests, the embedded account UUID that sets the request scope.
	StraddleAccountID param.Field[string] `header:"Straddle-Account-Id" format:"uuid"`
}

func (r PayoutUploadAuthorizationProofParams) MarshalMultipart() (data []byte, contentType string, err error) {
	buf := bytes.NewBuffer(nil)
	writer := multipart.NewWriter(buf)
	err = apiform.MarshalRoot(r, writer)
	if err != nil {
		writer.Close()
		return nil, "", err
	}
	err = writer.Close()
	if err != nil {
		return nil, "", err
	}
	return buf.Bytes(), writer.FormDataContentType(), nil
}
