// Code generated by Scalar SDK Generator. DO NOT EDIT.

package straddle

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"slices"
	"time"

	"github.com/straddle-build/straddle-go/internal/apijson"
	"github.com/straddle-build/straddle-go/internal/apiquery"
	"github.com/straddle-build/straddle-go/internal/param"
	"github.com/straddle-build/straddle-go/internal/requestconfig"
	"github.com/straddle-build/straddle-go/option"
)

// RepresentativeService contains methods and other services that help with interacting
// with the API. You should not instantiate this service directly, and instead use
// the [NewRepresentativeService] method instead.
type RepresentativeService struct {
	Options []option.RequestOption
}

// NewRepresentativeService generates a new service that applies the given options to each request.
// These options are applied after the parent client's options (if there is one), and
// before any request-specific options.
func NewRepresentativeService(opts ...option.RequestOption) (r *RepresentativeService) {
	r = &RepresentativeService{}
	r.Options = opts
	return
}

// Creates a representative for an account and returns the representative. Relationship fields identify primary representatives, control persons, and owners.
//
// Parameters:
//
//	ctx: Context for the request.
//	body: RepresentativeNewParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*RepresentativeResponse: Created
//
// Example:
//
//	representative, err := client.Representatives.New(context.Background(), sdk.RepresentativeNewParams{
//		AccountID:    sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
//		Dob:          sdk.F[time.Time](time.Now()),
//		Email:        sdk.F[string]("ron.swanson@pawnee.com"),
//		FirstName:    sdk.F[string](""),
//		LastName:     sdk.F[string](""),
//		MobileNumber: sdk.F[string]("+12128675309"),
//		Relationship: sdk.F[sdk.RepresentativeRelationshipParam](sdk.RepresentativeRelationshipParam{
//			Primary: sdk.F[bool](false),
//			Control: sdk.F[bool](false),
//			Owner:   sdk.F[bool](false),
//		}),
//		SsnLast4: sdk.F[string]("1234"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(representative)
func (r *RepresentativeService) New(ctx context.Context, body RepresentativeNewParams, opts ...option.RequestOption) (res *RepresentativeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/representatives"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPost, path, body, &res, opts...)
	return res, err
}

// Returns a paginated list of representatives. Filter the list by account, organization, platform, or scope.
//
// Parameters:
//
//	ctx: Context for the request.
//	query: RepresentativeListParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*RepresentativeList: OK
//
// Example:
//
//	representative, err := client.Representatives.List(context.Background(), sdk.RepresentativeListParams{
//		PageNumber: sdk.F[int64](1),
//		PageSize:   sdk.F[int64](100),
//		SortBy:     sdk.F[string]("id"),
//		SortOrder:  sdk.F[sdk.RepresentativeListParamsSortOrder](sdk.RepresentativeListParamsSortOrder("asc")),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(representative)
func (r *RepresentativeService) List(ctx context.Context, query RepresentativeListParams, opts ...option.RequestOption) (res *RepresentativeList, err error) {
	if query.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", query.CorrelationID.Value)))
	}
	if query.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", query.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	path := "v1/representatives"
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, query, &res, opts...)
	return res, err
}

// Updates a representative's personal, contact, relationship, external ID, and metadata fields, then returns the representative.
//
// Parameters:
//
//	ctx: Context for the request.
//	representativeID: The ID of the representative.
//	body: RepresentativeUpdateParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*RepresentativeResponse: OK
//
// Example:
//
//	representative, err := client.Representatives.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeUpdateParams{
//		Dob:          sdk.F[time.Time](time.Now()),
//		Email:        sdk.F[string]("ron.swanson@pawnee.com"),
//		FirstName:    sdk.F[string]("Ron"),
//		LastName:     sdk.F[string]("Swanson"),
//		MobileNumber: sdk.F[string]("+12128675309"),
//		Relationship: sdk.F[sdk.RepresentativeRelationshipParam](sdk.RepresentativeRelationshipParam{
//			Primary: sdk.F[bool](false),
//			Control: sdk.F[bool](false),
//			Owner:   sdk.F[bool](false),
//		}),
//		SsnLast4: sdk.F[string]("1234"),
//	})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(representative)
func (r *RepresentativeService) Update(ctx context.Context, representativeID string, body RepresentativeUpdateParams, opts ...option.RequestOption) (res *RepresentativeResponse, err error) {
	if body.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", body.CorrelationID.Value)))
	}
	if body.IdempotencyKey.Present {
		opts = append(opts, option.WithHeader("Idempotency-Key", fmt.Sprintf("%v", body.IdempotencyKey.Value)))
	}
	if body.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", body.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if representativeID == "" {
		err = errors.New("missing required representative_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/representatives/%s", url.PathEscape(representativeID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodPut, path, body, &res, opts...)
	return res, err
}

// Returns the representative with the specified ID.
//
// Parameters:
//
//	ctx: Context for the request.
//	representativeID: The ID of the representative.
//	params: RepresentativeGetParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*RepresentativeResponse: OK
//
// Example:
//
//	representative, err := client.Representatives.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeGetParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(representative)
func (r *RepresentativeService) Get(ctx context.Context, representativeID string, params RepresentativeGetParams, opts ...option.RequestOption) (res *RepresentativeResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if representativeID == "" {
		err = errors.New("missing required representative_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/representatives/%s", url.PathEscape(representativeID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

// Returns the representative with the specified ID without masking sensitive fields. This endpoint requires an administrator role.
//
// Parameters:
//
//	ctx: Context for the request.
//	representativeID: The ID of the representative.
//	params: RepresentativeListUnmaskedParams request parameters.
//	opts: Options to apply to this request.
//
// Returns:
//
//	*UnmaskedRepresentativeResponse: OK
//
// Example:
//
//	representative, err := client.Representatives.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeListUnmaskedParams{})
//	if err != nil {
//		panic(err)
//	}
//
//	fmt.Println(representative)
func (r *RepresentativeService) ListUnmasked(ctx context.Context, representativeID string, params RepresentativeListUnmaskedParams, opts ...option.RequestOption) (res *UnmaskedRepresentativeResponse, err error) {
	if params.CorrelationID.Present {
		opts = append(opts, option.WithHeader("Correlation-Id", fmt.Sprintf("%v", params.CorrelationID.Value)))
	}
	if params.RequestID.Present {
		opts = append(opts, option.WithHeader("Request-Id", fmt.Sprintf("%v", params.RequestID.Value)))
	}
	opts = slices.Concat(r.Options, opts)
	if representativeID == "" {
		err = errors.New("missing required representative_id parameter")
		return nil, err
	}
	path := fmt.Sprintf("v1/representatives/%s/unmask", url.PathEscape(representativeID))
	err = requestconfig.ExecuteNewRequest(ctx, http.MethodGet, path, nil, &res, opts...)
	return res, err
}

type RepresentativeResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType RepresentativeResponseResponseType `json:"response_type" api:"required"`
	Data         Representative                     `json:"data" api:"required"`
	JSON         representativeResponseJSON         `json:"-"`
}

// representativeResponseJSON contains the JSON metadata for the struct [RepresentativeResponse]
type representativeResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *RepresentativeResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r representativeResponseJSON) RawJSON() string {
	return r.raw
}

type RepresentativeResponseResponseType string

const (
	RepresentativeResponseResponseTypeObject RepresentativeResponseResponseType = "object"
	RepresentativeResponseResponseTypeArray  RepresentativeResponseResponseType = "array"
	RepresentativeResponseResponseTypeError  RepresentativeResponseResponseType = "error"
	RepresentativeResponseResponseTypeNone   RepresentativeResponseResponseType = "none"
)

func (r RepresentativeResponseResponseType) IsKnown() bool {
	switch r {
	case RepresentativeResponseResponseTypeObject, RepresentativeResponseResponseTypeArray, RepresentativeResponseResponseTypeError, RepresentativeResponseResponseTypeNone:
		return true
	}
	return false
}

type RepresentativeList struct {
	// Metadata for an API request and a page of results.
	Meta PageMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType RepresentativeListResponseType `json:"response_type" api:"required"`
	// Representatives returned for this page.
	Data []Representative       `json:"data" api:"required"`
	JSON representativeListJSON `json:"-"`
}

// representativeListJSON contains the JSON metadata for the struct [RepresentativeList]
type representativeListJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *RepresentativeList) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r representativeListJSON) RawJSON() string {
	return r.raw
}

type RepresentativeListResponseType string

const (
	RepresentativeListResponseTypeObject RepresentativeListResponseType = "object"
	RepresentativeListResponseTypeArray  RepresentativeListResponseType = "array"
	RepresentativeListResponseTypeError  RepresentativeListResponseType = "error"
	RepresentativeListResponseTypeNone   RepresentativeListResponseType = "none"
)

func (r RepresentativeListResponseType) IsKnown() bool {
	switch r {
	case RepresentativeListResponseTypeObject, RepresentativeListResponseTypeArray, RepresentativeListResponseTypeError, RepresentativeListResponseTypeNone:
		return true
	}
	return false
}

type UnmaskedRepresentativeResponse struct {
	// Metadata for an API request.
	Meta ResponseMetadata `json:"meta" api:"required"`
	// Indicates how the response content is structured. - `object` means `data`
	// contains one JSON object. - `array` means `data` contains an array of objects. -
	// `error` means `error` contains error details. - `none` means the response has no
	// data.
	ResponseType UnmaskedRepresentativeResponseResponseType `json:"response_type" api:"required"`
	Data         UnmaskedRepresentative                     `json:"data" api:"required"`
	JSON         unmaskedRepresentativeResponseJSON         `json:"-"`
}

// unmaskedRepresentativeResponseJSON contains the JSON metadata for the struct [UnmaskedRepresentativeResponse]
type unmaskedRepresentativeResponseJSON struct {
	Meta         apijson.Field
	ResponseType apijson.Field
	Data         apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedRepresentativeResponse) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedRepresentativeResponseJSON) RawJSON() string {
	return r.raw
}

type UnmaskedRepresentativeResponseResponseType string

const (
	UnmaskedRepresentativeResponseResponseTypeObject UnmaskedRepresentativeResponseResponseType = "object"
	UnmaskedRepresentativeResponseResponseTypeArray  UnmaskedRepresentativeResponseResponseType = "array"
	UnmaskedRepresentativeResponseResponseTypeError  UnmaskedRepresentativeResponseResponseType = "error"
	UnmaskedRepresentativeResponseResponseTypeNone   UnmaskedRepresentativeResponseResponseType = "none"
)

func (r UnmaskedRepresentativeResponseResponseType) IsKnown() bool {
	switch r {
	case UnmaskedRepresentativeResponseResponseTypeObject, UnmaskedRepresentativeResponseResponseTypeArray, UnmaskedRepresentativeResponseResponseTypeError, UnmaskedRepresentativeResponseResponseTypeNone:
		return true
	}
	return false
}

type Representative struct {
	// Straddle's unique ID for the representative.
	ID string `json:"id" api:"required" format:"uuid"`
	// ID of the account associated with the representative.
	AccountID string `json:"account_id" api:"required" format:"uuid"`
	// Status of the representative.
	Status       RepresentativeStatus       `json:"status" api:"required"`
	StatusDetail RepresentativeStatusDetail `json:"status_detail" api:"required"`
	// Representative's first name.
	FirstName string `json:"first_name" api:"required"`
	// Representative's last name.
	LastName string `json:"last_name" api:"required"`
	// Representative's date of birth in `YYYY-MM-DD` format.
	Dob time.Time `json:"dob" api:"required" format:"date"`
	// Last four digits of the representative's Social Security number.
	SsnLast4 string `json:"ssn_last4" api:"required"`
	// Representative's email address.
	Email string `json:"email" api:"required,nullable" format:"email"`
	// Representative's mobile phone number in E.164 format.
	MobileNumber string                     `json:"mobile_number" api:"required"`
	Relationship RepresentativeRelationship `json:"relationship" api:"required"`
	// Date and time when Straddle created the representative.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Date and time of the most recent representative update.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Representative's display name.
	Name string `json:"name" api:"required"`
	// ID of the Straddle user linked to the representative, if any.
	UserID string `json:"user_id" api:"nullable" format:"uuid"`
	// Your unique ID for the representative.
	ExternalID string `json:"external_id" api:"nullable"`
	// Representative's phone number.
	Phone string `json:"phone" api:"nullable"`
	// Up to 20 user-defined key-value pairs.
	Metadata map[string]string  `json:"metadata" api:"nullable"`
	JSON     representativeJSON `json:"-"`
}

// representativeJSON contains the JSON metadata for the struct [Representative]
type representativeJSON struct {
	ID           apijson.Field
	AccountID    apijson.Field
	Status       apijson.Field
	StatusDetail apijson.Field
	FirstName    apijson.Field
	LastName     apijson.Field
	Dob          apijson.Field
	SsnLast4     apijson.Field
	Email        apijson.Field
	MobileNumber apijson.Field
	Relationship apijson.Field
	CreatedAt    apijson.Field
	UpdatedAt    apijson.Field
	Name         apijson.Field
	UserID       apijson.Field
	ExternalID   apijson.Field
	Phone        apijson.Field
	Metadata     apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *Representative) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r representativeJSON) RawJSON() string {
	return r.raw
}

type RepresentativeStatus string

const (
	RepresentativeStatusCreated    RepresentativeStatus = "created"
	RepresentativeStatusOnboarding RepresentativeStatus = "onboarding"
	RepresentativeStatusActive     RepresentativeStatus = "active"
	RepresentativeStatusRejected   RepresentativeStatus = "rejected"
	RepresentativeStatusInactive   RepresentativeStatus = "inactive"
)

func (r RepresentativeStatus) IsKnown() bool {
	switch r {
	case RepresentativeStatusCreated, RepresentativeStatusOnboarding, RepresentativeStatusActive, RepresentativeStatusRejected, RepresentativeStatusInactive:
		return true
	}
	return false
}

type UnmaskedRepresentative struct {
	// Straddle's unique ID for the representative.
	ID string `json:"id" api:"required" format:"uuid"`
	// ID of the account associated with the representative.
	AccountID string `json:"account_id" api:"required" format:"uuid"`
	// Status of the representative.
	Status       UnmaskedRepresentativeStatus `json:"status" api:"required"`
	StatusDetail RepresentativeStatusDetail   `json:"status_detail" api:"required"`
	// Representative's first name.
	FirstName string `json:"first_name" api:"required"`
	// Representative's last name.
	LastName string `json:"last_name" api:"required"`
	// Representative's date of birth in `YYYY-MM-DD` format.
	Dob time.Time `json:"dob" api:"required" format:"date"`
	// Representative's email address.
	Email string `json:"email" api:"required"`
	// Representative's mobile phone number.
	MobileNumber string                     `json:"mobile_number" api:"required"`
	Relationship RepresentativeRelationship `json:"relationship" api:"required"`
	// Date and time when Straddle created the representative.
	CreatedAt time.Time `json:"created_at" api:"required" format:"date-time"`
	// Date and time of the most recent representative update.
	UpdatedAt time.Time `json:"updated_at" api:"required" format:"date-time"`
	// Last four digits of the representative's Social Security number.
	SsnLast4 string `json:"ssn_last4" api:"required"`
	// ID of the Straddle user linked to the representative, if any.
	UserID string `json:"user_id" api:"nullable" format:"uuid"`
	// Your unique ID for the representative.
	ExternalID string `json:"external_id" api:"nullable"`
	// Up to 20 user-defined key-value pairs.
	Metadata map[string]string          `json:"metadata" api:"nullable"`
	JSON     unmaskedRepresentativeJSON `json:"-"`
}

// unmaskedRepresentativeJSON contains the JSON metadata for the struct [UnmaskedRepresentative]
type unmaskedRepresentativeJSON struct {
	ID           apijson.Field
	AccountID    apijson.Field
	Status       apijson.Field
	StatusDetail apijson.Field
	FirstName    apijson.Field
	LastName     apijson.Field
	Dob          apijson.Field
	Email        apijson.Field
	MobileNumber apijson.Field
	Relationship apijson.Field
	CreatedAt    apijson.Field
	UpdatedAt    apijson.Field
	SsnLast4     apijson.Field
	UserID       apijson.Field
	ExternalID   apijson.Field
	Metadata     apijson.Field
	raw          string
	ExtraFields  map[string]apijson.Field
}

func (r *UnmaskedRepresentative) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r unmaskedRepresentativeJSON) RawJSON() string {
	return r.raw
}

type UnmaskedRepresentativeStatus string

const (
	UnmaskedRepresentativeStatusCreated    UnmaskedRepresentativeStatus = "created"
	UnmaskedRepresentativeStatusOnboarding UnmaskedRepresentativeStatus = "onboarding"
	UnmaskedRepresentativeStatusActive     UnmaskedRepresentativeStatus = "active"
	UnmaskedRepresentativeStatusRejected   UnmaskedRepresentativeStatus = "rejected"
	UnmaskedRepresentativeStatusInactive   UnmaskedRepresentativeStatus = "inactive"
)

func (r UnmaskedRepresentativeStatus) IsKnown() bool {
	switch r {
	case UnmaskedRepresentativeStatusCreated, UnmaskedRepresentativeStatusOnboarding, UnmaskedRepresentativeStatusActive, UnmaskedRepresentativeStatusRejected, UnmaskedRepresentativeStatusInactive:
		return true
	}
	return false
}

type RepresentativeStatusDetail struct {
	// Machine-readable reason for the representative's status.
	Reason RepresentativeStatusDetailReason `json:"reason" api:"required"`
	// System that produced the representative status detail.
	Source RepresentativeStatusDetailSource `json:"source" api:"required"`
	// Machine-readable status code from the source.
	Code string `json:"code" api:"required"`
	// Human-readable description of the representative's status.
	Message string                         `json:"message" api:"required"`
	JSON    representativeStatusDetailJSON `json:"-"`
}

// representativeStatusDetailJSON contains the JSON metadata for the struct [RepresentativeStatusDetail]
type representativeStatusDetailJSON struct {
	Reason      apijson.Field
	Source      apijson.Field
	Code        apijson.Field
	Message     apijson.Field
	raw         string
	ExtraFields map[string]apijson.Field
}

func (r *RepresentativeStatusDetail) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r representativeStatusDetailJSON) RawJSON() string {
	return r.raw
}

type RepresentativeStatusDetailReason string

const (
	RepresentativeStatusDetailReasonUnverified         RepresentativeStatusDetailReason = "unverified"
	RepresentativeStatusDetailReasonInReview           RepresentativeStatusDetailReason = "in_review"
	RepresentativeStatusDetailReasonPending            RepresentativeStatusDetailReason = "pending"
	RepresentativeStatusDetailReasonStuck              RepresentativeStatusDetailReason = "stuck"
	RepresentativeStatusDetailReasonVerified           RepresentativeStatusDetailReason = "verified"
	RepresentativeStatusDetailReasonFailedVerification RepresentativeStatusDetailReason = "failed_verification"
	RepresentativeStatusDetailReasonDisabled           RepresentativeStatusDetailReason = "disabled"
	RepresentativeStatusDetailReasonNew                RepresentativeStatusDetailReason = "new"
)

func (r RepresentativeStatusDetailReason) IsKnown() bool {
	switch r {
	case RepresentativeStatusDetailReasonUnverified, RepresentativeStatusDetailReasonInReview, RepresentativeStatusDetailReasonPending, RepresentativeStatusDetailReasonStuck, RepresentativeStatusDetailReasonVerified, RepresentativeStatusDetailReasonFailedVerification, RepresentativeStatusDetailReasonDisabled, RepresentativeStatusDetailReasonNew:
		return true
	}
	return false
}

type RepresentativeStatusDetailSource string

const (
	RepresentativeStatusDetailSourceWatchtower RepresentativeStatusDetailSource = "watchtower"
)

func (r RepresentativeStatusDetailSource) IsKnown() bool {
	switch r {
	case RepresentativeStatusDetailSourceWatchtower:
		return true
	}
	return false
}

type RepresentativeRelationship struct {
	// Whether this person is the account's primary representative. The primary
	// representative provides personal and business information and accepts the
	// services agreement. An account can have only one primary representative.
	Primary bool `json:"primary" api:"required"`
	// Whether the representative controls, manages, or directs the business. Each
	// legal entity must have one representative with `control` set to `true`.
	Control bool `json:"control" api:"required"`
	// Whether the representative owns any equity in the business.
	Owner bool `json:"owner" api:"required"`
	// The representative's ownership percentage. Required when `owner` is `true`.
	PercentOwnership float64 `json:"percent_ownership" api:"nullable"`
	// The representative's job title.
	Title string                         `json:"title" api:"nullable"`
	JSON  representativeRelationshipJSON `json:"-"`
}

// representativeRelationshipJSON contains the JSON metadata for the struct [RepresentativeRelationship]
type representativeRelationshipJSON struct {
	Primary          apijson.Field
	Control          apijson.Field
	Owner            apijson.Field
	PercentOwnership apijson.Field
	Title            apijson.Field
	raw              string
	ExtraFields      map[string]apijson.Field
}

func (r *RepresentativeRelationship) UnmarshalJSON(data []byte) (err error) {
	return apijson.UnmarshalRoot(data, r)
}

func (r representativeRelationshipJSON) RawJSON() string {
	return r.raw
}

type RepresentativeRelationshipParam struct {
	// Whether the representative controls, manages, or directs the business. Each
	// legal entity must have one representative with `control` set to `true`.
	Control param.Field[bool] `json:"control" api:"required"`
	// Whether the representative owns any equity in the business.
	Owner param.Field[bool] `json:"owner" api:"required"`
	// Whether this person is the account's primary representative. The primary
	// representative provides personal and business information and accepts the
	// services agreement. An account can have only one primary representative.
	Primary param.Field[bool] `json:"primary" api:"required"`
	// The representative's ownership percentage. Required when `owner` is `true`.
	PercentOwnership param.Field[float64] `json:"percent_ownership"`
	// The representative's job title.
	Title param.Field[string] `json:"title"`
}

func (r RepresentativeRelationshipParam) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RepresentativeNewParams struct {
	// ID of the account associated with the representative.
	AccountID param.Field[string] `json:"account_id" api:"required" format:"uuid"`
	// Representative's date of birth in `YYYY-MM-DD` format.
	Dob param.Field[time.Time] `json:"dob" api:"required" format:"date"`
	// Representative's company email address.
	Email param.Field[string] `json:"email" api:"required" format:"email"`
	// Representative's first name.
	FirstName param.Field[string] `json:"first_name" api:"required"`
	// Representative's last name.
	LastName param.Field[string] `json:"last_name" api:"required"`
	// Representative's mobile phone number in E.164 format.
	MobileNumber param.Field[string]                          `json:"mobile_number" api:"required"`
	Relationship param.Field[RepresentativeRelationshipParam] `json:"relationship" api:"required"`
	// Last four digits of the representative's Social Security number.
	SsnLast4 param.Field[string] `json:"ssn_last4" api:"required"`
	// Your unique ID for the representative.
	ExternalID param.Field[string] `json:"external_id"`
	// Up to 20 user-defined key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

func (r RepresentativeNewParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RepresentativeListParams struct {
	// Account ID used to filter the results.
	AccountID param.Field[string] `query:"account_id" format:"uuid"`
	// Scope of representatives to return.
	Level param.Field[RepresentativeListParamsLevel] `query:"level"`
	// Organization ID used to filter the results.
	OrganizationID param.Field[string] `query:"organization_id" format:"uuid"`
	// Page number. Defaults to `1`.
	PageNumber param.Field[int64] `query:"page_number"`
	// Number of results per page. Defaults to `100`. Maximum `1000`.
	PageSize param.Field[int64] `query:"page_size"`
	// Platform ID used to filter the results.
	PlatformID param.Field[string] `query:"platform_id" format:"uuid"`
	// Field used to sort results. Defaults to `id`.
	SortBy param.Field[string] `query:"sort_by"`
	// Sort direction. Defaults to `asc`.
	SortOrder param.Field[RepresentativeListParamsSortOrder] `query:"sort_order"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

// URLQuery serializes [RepresentativeListParams]'s query parameters as `url.Values`.
func (r RepresentativeListParams) URLQuery() (v url.Values) {
	return apiquery.MarshalWithSettings(r, apiquery.QuerySettings{
		ArrayFormat:  apiquery.ArrayQueryFormatRepeat,
		NestedFormat: apiquery.NestedQueryFormatBrackets,
	})
}

type RepresentativeListParamsSortOrder string

const (
	RepresentativeListParamsSortOrderAsc  RepresentativeListParamsSortOrder = "asc"
	RepresentativeListParamsSortOrderDesc RepresentativeListParamsSortOrder = "desc"
)

func (r RepresentativeListParamsSortOrder) IsKnown() bool {
	switch r {
	case RepresentativeListParamsSortOrderAsc, RepresentativeListParamsSortOrderDesc:
		return true
	}
	return false
}

type RepresentativeListParamsLevel string

const (
	RepresentativeListParamsLevelAccount  RepresentativeListParamsLevel = "account"
	RepresentativeListParamsLevelPlatform RepresentativeListParamsLevel = "platform"
)

func (r RepresentativeListParamsLevel) IsKnown() bool {
	switch r {
	case RepresentativeListParamsLevelAccount, RepresentativeListParamsLevelPlatform:
		return true
	}
	return false
}

type RepresentativeUpdateParams struct {
	// Representative's date of birth in `YYYY-MM-DD` format.
	Dob param.Field[time.Time] `json:"dob" api:"required" format:"date"`
	// Representative's email address.
	Email param.Field[string] `json:"email" api:"required" format:"email"`
	// Representative's first name.
	FirstName param.Field[string] `json:"first_name" api:"required"`
	// Representative's last name.
	LastName param.Field[string] `json:"last_name" api:"required"`
	// Representative's mobile phone number in E.164 format.
	MobileNumber param.Field[string]                          `json:"mobile_number" api:"required"`
	Relationship param.Field[RepresentativeRelationshipParam] `json:"relationship" api:"required"`
	// Last four digits of the representative's Social Security number.
	SsnLast4 param.Field[string] `json:"ssn_last4" api:"required"`
	// Your unique ID for the representative.
	ExternalID param.Field[string] `json:"external_id"`
	// Up to 20 user-defined key-value pairs.
	Metadata param.Field[map[string]string] `json:"metadata"`
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated key for an idempotent request.
	IdempotencyKey param.Field[string] `header:"Idempotency-Key"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

func (r RepresentativeUpdateParams) MarshalJSON() (data []byte, err error) {
	return apijson.MarshalRoot(r)
}

type RepresentativeGetParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}

type RepresentativeListUnmaskedParams struct {
	// Optional client-generated identifier for tracing a series of related requests.
	CorrelationID param.Field[string] `header:"Correlation-Id"`
	// Optional client-generated identifier for tracing one request.
	RequestID param.Field[string] `header:"Request-Id"`
}
