// Code generated by Scalar SDK Generator. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"strings"
	"sync"
	"time"

	sdk "github.com/straddle-build/straddle-go"
	"github.com/straddle-build/straddle-go/option"
)

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `go run tests/smoke-test.go`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
var client = sdk.NewClient(option.WithBearer("test"), option.WithHeader("Authorization", "Bearer test"))

type smokeResult struct {
	Operation  string `json:"operation"`
	Method     string `json:"method"`
	Path       string `json:"path"`
	Label      string `json:"label,omitempty"`
	Status     string `json:"status"`
	DurationMs int64  `json:"durationMs"`
	Error      string `json:"error,omitempty"`
}

// Label says which of an operation's two calls this is — "required params" or "all params".
// It is empty when the operation contributed a single case.
type smokeCase struct {
	Operation string
	Method    string
	Path      string
	Label     string
	Run       func()
}

func _smokeCase0() {
	account, err := client.Accounts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase1() {
	account, err := client.Accounts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountGetParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase2() {
	account, err := client.Accounts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountUpdateParams{
		BusinessProfile: sdk.F[sdk.AccountBusinessProfileParam](sdk.AccountBusinessProfileParam{
			Name:    sdk.F[string](""),
			Website: sdk.F[string]("https://example.com"),
		}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase3() {
	account, err := client.Accounts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountUpdateParams{
		BusinessProfile: sdk.F[sdk.AccountBusinessProfileParam](sdk.AccountBusinessProfileParam{
			Name:    sdk.F[string](""),
			Website: sdk.F[string]("https://example.com"),
		}),
		ExternalID:     sdk.F[string](""),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase4() {
	account, err := client.Accounts.New(context.Background(), sdk.AccountNewParams{
		BusinessProfile: sdk.F[sdk.AccountBusinessProfileParam](sdk.AccountBusinessProfileParam{
			Name:    sdk.F[string](""),
			Website: sdk.F[string]("https://example.com"),
		}),
		OrganizationID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase5() {
	account, err := client.Accounts.New(context.Background(), sdk.AccountNewParams{
		BusinessProfile: sdk.F[sdk.AccountBusinessProfileParam](sdk.AccountBusinessProfileParam{
			Name:    sdk.F[string](""),
			Website: sdk.F[string]("https://example.com"),
		}),
		OrganizationID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		ExternalID:     sdk.F[string](""),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase6() {
	account, err := client.Accounts.List(context.Background(), sdk.AccountListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortBy:     sdk.F[string]("id"),
		SortOrder:  sdk.F[sdk.AccountListParamsSortOrder](sdk.AccountListParamsSortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase7() {
	account, err := client.Accounts.List(context.Background(), sdk.AccountListParams{
		ExternalID:    sdk.F[string](""),
		PageNumber:    sdk.F[int64](1),
		PageSize:      sdk.F[int64](100),
		SearchText:    sdk.F[string](""),
		SortBy:        sdk.F[string]("id"),
		SortOrder:     sdk.F[sdk.AccountListParamsSortOrder](sdk.AccountListParamsSortOrder("asc")),
		Status:        sdk.F[sdk.AccountListParamsStatus](sdk.AccountListParamsStatus("created")),
		Type:          sdk.F[sdk.AccountListParamsType](sdk.AccountListParamsType("business")),
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase8() {
	account, err := client.Accounts.Onboard(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountOnboardParams{
		TermsOfService: sdk.F[sdk.TermsOfServiceParam](sdk.TermsOfServiceParam{
			AcceptedDate: sdk.F[time.Time](time.Now()),
			AgreementURL: sdk.F[string](""),
		}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase9() {
	account, err := client.Accounts.Onboard(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountOnboardParams{
		TermsOfService: sdk.F[sdk.TermsOfServiceParam](sdk.TermsOfServiceParam{
			AcceptedDate: sdk.F[time.Time](time.Now()),
			AgreementURL: sdk.F[string](""),
		}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase10() {
	account, err := client.Accounts.SimulateOnboarding(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountSimulateOnboardingParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase11() {
	account, err := client.Accounts.SimulateOnboarding(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountSimulateOnboardingParams{
		FinalStatus:    sdk.F[sdk.AccountSimulateOnboardingParamsFinalStatus](sdk.AccountSimulateOnboardingParamsFinalStatus("onboarding")),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(account)
}

func _smokeCase12() {
	capabilityRequest, err := client.CapabilityRequests.New(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CapabilityRequestNewParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(capabilityRequest)
}

func _smokeCase13() {
	capabilityRequest, err := client.CapabilityRequests.New(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CapabilityRequestNewParams{
		Businesses: sdk.F[sdk.CapabilityRequestNewParamsBusinesses](sdk.CapabilityRequestNewParamsBusinesses{
			Enable: sdk.F[bool](false),
		}),
		Charges: sdk.F[sdk.CapabilityRequestNewParamsCharges](sdk.CapabilityRequestNewParamsCharges{
			Enable:        sdk.F[bool](false),
			MaxAmount:     sdk.F[float64](0),
			DailyAmount:   sdk.F[float64](0),
			MonthlyCount:  sdk.F[int64](0),
			MonthlyAmount: sdk.F[float64](0),
		}),
		Individuals: sdk.F[sdk.CapabilityRequestNewParamsIndividuals](sdk.CapabilityRequestNewParamsIndividuals{
			Enable: sdk.F[bool](false),
		}),
		Internet: sdk.F[sdk.CapabilityRequestNewParamsInternet](sdk.CapabilityRequestNewParamsInternet{
			Enable: sdk.F[bool](false),
		}),
		Payouts: sdk.F[sdk.CapabilityRequestNewParamsPayouts](sdk.CapabilityRequestNewParamsPayouts{
			Enable:        sdk.F[bool](false),
			MaxAmount:     sdk.F[float64](0),
			DailyAmount:   sdk.F[float64](0),
			MonthlyCount:  sdk.F[int64](0),
			MonthlyAmount: sdk.F[float64](0),
		}),
		SignedAgreement: sdk.F[sdk.CapabilityRequestNewParamsSignedAgreement](sdk.CapabilityRequestNewParamsSignedAgreement{
			Enable: sdk.F[bool](false),
		}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(capabilityRequest)
}

func _smokeCase14() {
	capabilityRequest, err := client.CapabilityRequests.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CapabilityRequestListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortBy:     sdk.F[string]("id"),
		SortOrder:  sdk.F[sdk.CapabilityRequestListParamsSortOrder](sdk.CapabilityRequestListParamsSortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(capabilityRequest)
}

func _smokeCase15() {
	capabilityRequest, err := client.CapabilityRequests.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CapabilityRequestListParams{
		Category:      sdk.F[sdk.CapabilityRequestListParamsCategory](sdk.CapabilityRequestListParamsCategory("payment_type")),
		PageNumber:    sdk.F[int64](1),
		PageSize:      sdk.F[int64](100),
		SortBy:        sdk.F[string]("id"),
		SortOrder:     sdk.F[sdk.CapabilityRequestListParamsSortOrder](sdk.CapabilityRequestListParamsSortOrder("asc")),
		Status:        sdk.F[sdk.CapabilityRequestListParamsStatus](sdk.CapabilityRequestListParamsStatus("active")),
		Type:          sdk.F[sdk.CapabilityRequestListParamsType](sdk.CapabilityRequestListParamsType("charges")),
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(capabilityRequest)
}

func _smokeCase16() {
	linkedBankAccount, err := client.LinkedBankAccounts.New(context.Background(), sdk.LinkedBankAccountNewParams{
		BankAccount: sdk.F[sdk.LinkedBankAccountNewParamsBankAccount](sdk.LinkedBankAccountNewParamsBankAccount{
			AccountHolder: sdk.F[string](""),
			RoutingNumber: sdk.F[string]("xxxxxxxxx"),
			AccountNumber: sdk.F[string](""),
		}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase17() {
	linkedBankAccount, err := client.LinkedBankAccounts.New(context.Background(), sdk.LinkedBankAccountNewParams{
		BankAccount: sdk.F[sdk.LinkedBankAccountNewParamsBankAccount](sdk.LinkedBankAccountNewParamsBankAccount{
			AccountHolder: sdk.F[string](""),
			RoutingNumber: sdk.F[string]("xxxxxxxxx"),
			AccountNumber: sdk.F[string](""),
		}),
		AccountID:      sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Description:    sdk.F[string](""),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		PlatformID:     sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Purposes:       sdk.F[[]sdk.LinkedBankAccountNewParamsPurpose]([]sdk.LinkedBankAccountNewParamsPurpose{"charges"}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase18() {
	linkedBankAccount, err := client.LinkedBankAccounts.List(context.Background(), sdk.LinkedBankAccountListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortBy:     sdk.F[string]("id"),
		SortOrder:  sdk.F[sdk.LinkedBankAccountListParamsSortOrder](sdk.LinkedBankAccountListParamsSortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase19() {
	linkedBankAccount, err := client.LinkedBankAccounts.List(context.Background(), sdk.LinkedBankAccountListParams{
		AccountID:     sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Level:         sdk.F[sdk.LinkedBankAccountListParamsLevel](sdk.LinkedBankAccountListParamsLevel("account")),
		PageNumber:    sdk.F[int64](1),
		PageSize:      sdk.F[int64](100),
		Purpose:       sdk.F[sdk.LinkedBankAccountListParamsPurpose](sdk.LinkedBankAccountListParamsPurpose("charges")),
		SortBy:        sdk.F[string]("id"),
		SortOrder:     sdk.F[sdk.LinkedBankAccountListParamsSortOrder](sdk.LinkedBankAccountListParamsSortOrder("asc")),
		Status:        sdk.F[sdk.LinkedBankAccountListParamsStatus](sdk.LinkedBankAccountListParamsStatus("created")),
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase20() {
	linkedBankAccount, err := client.LinkedBankAccounts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountUpdateParams{
		BankAccount: sdk.F[sdk.LinkedBankAccountUpdateParamsBankAccount](sdk.LinkedBankAccountUpdateParamsBankAccount{
			AccountHolder: sdk.F[string](""),
			RoutingNumber: sdk.F[string]("xxxxxxxxx"),
			AccountNumber: sdk.F[string](""),
		}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase21() {
	linkedBankAccount, err := client.LinkedBankAccounts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountUpdateParams{
		BankAccount: sdk.F[sdk.LinkedBankAccountUpdateParamsBankAccount](sdk.LinkedBankAccountUpdateParamsBankAccount{
			AccountHolder: sdk.F[string](""),
			RoutingNumber: sdk.F[string]("xxxxxxxxx"),
			AccountNumber: sdk.F[string](""),
		}),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase22() {
	linkedBankAccount, err := client.LinkedBankAccounts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase23() {
	linkedBankAccount, err := client.LinkedBankAccounts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountGetParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase24() {
	linkedBankAccount, err := client.LinkedBankAccounts.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountListUnmaskedParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase25() {
	linkedBankAccount, err := client.LinkedBankAccounts.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountListUnmaskedParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase26() {
	linkedBankAccount, err := client.LinkedBankAccounts.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountCancelParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase27() {
	linkedBankAccount, err := client.LinkedBankAccounts.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.LinkedBankAccountCancelParams{
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(linkedBankAccount)
}

func _smokeCase28() {
	organization, err := client.Organizations.New(context.Background(), sdk.OrganizationNewParams{
		Name: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(organization)
}

func _smokeCase29() {
	organization, err := client.Organizations.New(context.Background(), sdk.OrganizationNewParams{
		Name:           sdk.F[string](""),
		ExternalID:     sdk.F[string](""),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(organization)
}

func _smokeCase30() {
	organization, err := client.Organizations.List(context.Background(), sdk.OrganizationListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortBy:     sdk.F[string]("id"),
		SortOrder:  sdk.F[sdk.OrganizationListParamsSortOrder](sdk.OrganizationListParamsSortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(organization)
}

func _smokeCase31() {
	organization, err := client.Organizations.List(context.Background(), sdk.OrganizationListParams{
		ExternalID:    sdk.F[string](""),
		Name:          sdk.F[string](""),
		PageNumber:    sdk.F[int64](1),
		PageSize:      sdk.F[int64](100),
		SortBy:        sdk.F[string]("id"),
		SortOrder:     sdk.F[sdk.OrganizationListParamsSortOrder](sdk.OrganizationListParamsSortOrder("asc")),
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(organization)
}

func _smokeCase32() {
	organization, err := client.Organizations.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.OrganizationGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(organization)
}

func _smokeCase33() {
	organization, err := client.Organizations.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.OrganizationGetParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(organization)
}

func _smokeCase34() {
	representative, err := client.Representatives.New(context.Background(), sdk.RepresentativeNewParams{
		AccountID:    sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Dob:          sdk.F[time.Time](time.Now()),
		Email:        sdk.F[string]("ron.swanson@pawnee.com"),
		FirstName:    sdk.F[string](""),
		LastName:     sdk.F[string](""),
		MobileNumber: sdk.F[string]("+12128675309"),
		Relationship: sdk.F[sdk.RepresentativeRelationshipParam](sdk.RepresentativeRelationshipParam{
			Primary: sdk.F[bool](false),
			Control: sdk.F[bool](false),
			Owner:   sdk.F[bool](false),
		}),
		SsnLast4: sdk.F[string]("1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase35() {
	representative, err := client.Representatives.New(context.Background(), sdk.RepresentativeNewParams{
		AccountID:    sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Dob:          sdk.F[time.Time](time.Now()),
		Email:        sdk.F[string]("ron.swanson@pawnee.com"),
		FirstName:    sdk.F[string](""),
		LastName:     sdk.F[string](""),
		MobileNumber: sdk.F[string]("+12128675309"),
		Relationship: sdk.F[sdk.RepresentativeRelationshipParam](sdk.RepresentativeRelationshipParam{
			Primary: sdk.F[bool](false),
			Control: sdk.F[bool](false),
			Owner:   sdk.F[bool](false),
		}),
		SsnLast4:       sdk.F[string]("1234"),
		ExternalID:     sdk.F[string](""),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase36() {
	representative, err := client.Representatives.List(context.Background(), sdk.RepresentativeListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortBy:     sdk.F[string]("id"),
		SortOrder:  sdk.F[sdk.RepresentativeListParamsSortOrder](sdk.RepresentativeListParamsSortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase37() {
	representative, err := client.Representatives.List(context.Background(), sdk.RepresentativeListParams{
		AccountID:      sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Level:          sdk.F[sdk.RepresentativeListParamsLevel](sdk.RepresentativeListParamsLevel("account")),
		OrganizationID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		PageNumber:     sdk.F[int64](1),
		PageSize:       sdk.F[int64](100),
		PlatformID:     sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		SortBy:         sdk.F[string]("id"),
		SortOrder:      sdk.F[sdk.RepresentativeListParamsSortOrder](sdk.RepresentativeListParamsSortOrder("asc")),
		CorrelationID:  sdk.F[string](""),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase38() {
	representative, err := client.Representatives.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeUpdateParams{
		Dob:          sdk.F[time.Time](time.Now()),
		Email:        sdk.F[string]("ron.swanson@pawnee.com"),
		FirstName:    sdk.F[string]("Ron"),
		LastName:     sdk.F[string]("Swanson"),
		MobileNumber: sdk.F[string]("+12128675309"),
		Relationship: sdk.F[sdk.RepresentativeRelationshipParam](sdk.RepresentativeRelationshipParam{
			Primary: sdk.F[bool](false),
			Control: sdk.F[bool](false),
			Owner:   sdk.F[bool](false),
		}),
		SsnLast4: sdk.F[string]("1234"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase39() {
	representative, err := client.Representatives.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeUpdateParams{
		Dob:          sdk.F[time.Time](time.Now()),
		Email:        sdk.F[string]("ron.swanson@pawnee.com"),
		FirstName:    sdk.F[string]("Ron"),
		LastName:     sdk.F[string]("Swanson"),
		MobileNumber: sdk.F[string]("+12128675309"),
		Relationship: sdk.F[sdk.RepresentativeRelationshipParam](sdk.RepresentativeRelationshipParam{
			Primary: sdk.F[bool](false),
			Control: sdk.F[bool](false),
			Owner:   sdk.F[bool](false),
		}),
		SsnLast4:       sdk.F[string]("1234"),
		ExternalID:     sdk.F[string](""),
		Metadata:       sdk.F[map[string]string](map[string]string{}),
		CorrelationID:  sdk.F[string](""),
		IdempotencyKey: sdk.F[string]("xxxxxxxxxx"),
		RequestID:      sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase40() {
	representative, err := client.Representatives.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase41() {
	representative, err := client.Representatives.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeGetParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase42() {
	representative, err := client.Representatives.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeListUnmaskedParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase43() {
	representative, err := client.Representatives.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.RepresentativeListUnmaskedParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(representative)
}

func _smokeCase44() {
	bridge, err := client.Bridge.NewBankAccountPaykey(context.Background(), sdk.BridgeNewBankAccountPaykeyParams{
		AccountNumber: sdk.F[string](""),
		CustomerID:    sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		RoutingNumber: sdk.F[string]("xxxxxxxxx"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase45() {
	bridge, err := client.Bridge.NewBankAccountPaykey(context.Background(), sdk.BridgeNewBankAccountPaykeyParams{
		AccountNumber:     sdk.F[string](""),
		CustomerID:        sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		RoutingNumber:     sdk.F[string]("xxxxxxxxx"),
		Config:            sdk.F[sdk.PaykeyConfigurationParam](sdk.PaykeyConfigurationParam{}),
		ExternalID:        sdk.F[string](""),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase46() {
	bridge, err := client.Bridge.NewPlaidPaykey(context.Background(), sdk.BridgeNewPlaidPaykeyParams{
		CustomerID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		PlaidToken: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase47() {
	bridge, err := client.Bridge.NewPlaidPaykey(context.Background(), sdk.BridgeNewPlaidPaykeyParams{
		CustomerID:        sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		PlaidToken:        sdk.F[string](""),
		Config:            sdk.F[sdk.PaykeyConfigurationParam](sdk.PaykeyConfigurationParam{}),
		ExternalID:        sdk.F[string](""),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase48() {
	bridge, err := client.Bridge.NewToken(context.Background(), sdk.BridgeNewTokenParams{
		CustomerID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase49() {
	bridge, err := client.Bridge.NewToken(context.Background(), sdk.BridgeNewTokenParams{
		CustomerID:        sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		Config:            sdk.F[sdk.PaykeyConfigurationParam](sdk.PaykeyConfigurationParam{}),
		ExternalID:        sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase50() {
	bridge, err := client.Bridge.NewQuilttPaykey(context.Background(), sdk.BridgeNewQuilttPaykeyParams{
		CustomerID:  sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		QuilttToken: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase51() {
	bridge, err := client.Bridge.NewQuilttPaykey(context.Background(), sdk.BridgeNewQuilttPaykeyParams{
		CustomerID:        sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		QuilttToken:       sdk.F[string](""),
		Config:            sdk.F[sdk.PaykeyConfigurationParam](sdk.PaykeyConfigurationParam{}),
		ExternalID:        sdk.F[string](""),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(bridge)
}

func _smokeCase52() {
	customer, err := client.Customers.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase53() {
	customer, err := client.Customers.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerGetParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase54() {
	customer, err := client.Customers.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerUpdateParams{
		Device: sdk.F[sdk.CustomerDeviceParam](sdk.CustomerDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		Email: sdk.F[string]("user@example.com"),
		Name:  sdk.F[string](""),
		Phone: sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase55() {
	customer, err := client.Customers.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerUpdateParams{
		Device: sdk.F[sdk.CustomerDeviceParam](sdk.CustomerDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		Email: sdk.F[string]("user@example.com"),
		Name:  sdk.F[string](""),
		Phone: sdk.F[string](""),
		Address: sdk.F[sdk.CustomerUpdateParamsAddress](sdk.CustomerUpdateParamsAddress{
			Address1: sdk.F[string]("123 Main St"),
			City:     sdk.F[string]("Anytown"),
			State:    sdk.F[string]("CA"),
			Zip:      sdk.F[string]("12345"),
		}),
		ExternalID:        sdk.F[string](""),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase56() {
	customer, err := client.Customers.Delete(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerDeleteParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase57() {
	customer, err := client.Customers.Delete(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerDeleteParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase58() {
	customer, err := client.Customers.List(context.Background(), sdk.CustomerListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase59() {
	customer, err := client.Customers.List(context.Background(), sdk.CustomerListParams{
		CreatedFrom:       sdk.F[time.Time](time.Now()),
		CreatedTo:         sdk.F[time.Time](time.Now()),
		Email:             sdk.F[string](""),
		ExternalID:        sdk.F[string](""),
		Name:              sdk.F[string](""),
		PageNumber:        sdk.F[int64](1),
		PageSize:          sdk.F[int64](100),
		SearchText:        sdk.F[string](""),
		SortBy:            sdk.F[sdk.CustomerListParamsSortBy](sdk.CustomerListParamsSortBy("name")),
		SortOrder:         sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		Status:            sdk.F[[]sdk.CustomerStatus]([]sdk.CustomerStatus{"pending"}),
		Types:             sdk.F[[]sdk.CustomerType]([]sdk.CustomerType{"individual"}),
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase60() {
	customer, err := client.Customers.New(context.Background(), sdk.CustomerNewParams{
		Device: sdk.F[sdk.CustomerDeviceParam](sdk.CustomerDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		Email: sdk.F[string]("ron.swanson@pawnee.com"),
		Name:  sdk.F[string]("Ron Swanson"),
		Phone: sdk.F[string]("+12128675309"),
		Address: sdk.F[sdk.CustomerUpdateParamsAddress](sdk.CustomerUpdateParamsAddress{
			Address1: sdk.F[string]("123 Main St"),
			City:     sdk.F[string]("Anytown"),
			State:    sdk.F[string]("CA"),
			Zip:      sdk.F[string]("94105"),
		}),
		ExternalID: sdk.F[string]("customer_123"),
		Metadata:   sdk.F[map[string]string](map[string]string{}),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase61() {
	customer, err := client.Customers.New(context.Background(), sdk.CustomerNewParams{
		Device: sdk.F[sdk.CustomerDeviceParam](sdk.CustomerDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		Email: sdk.F[string]("ron.swanson@pawnee.com"),
		Name:  sdk.F[string]("Ron Swanson"),
		Phone: sdk.F[string]("+12128675309"),
		Address: sdk.F[sdk.CustomerUpdateParamsAddress](sdk.CustomerUpdateParamsAddress{
			Address1: sdk.F[string]("123 Main St"),
			City:     sdk.F[string]("Anytown"),
			State:    sdk.F[string]("CA"),
			Zip:      sdk.F[string]("94105"),
		}),
		Config:            sdk.F[sdk.CustomerConfigurationParam](sdk.CustomerConfigurationParam{}),
		ExternalID:        sdk.F[string]("customer_123"),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase62() {
	customer, err := client.Customers.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerListUnmaskedParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase63() {
	customer, err := client.Customers.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerListUnmaskedParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase64() {
	customer, err := client.Customers.RefreshReview(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerRefreshReviewParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase65() {
	customer, err := client.Customers.RefreshReview(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerRefreshReviewParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(customer)
}

func _smokeCase66() {
	review, err := client.Customers.Review.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerReviewListParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase67() {
	review, err := client.Customers.Review.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerReviewListParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase68() {
	review, err := client.Customers.Review.SetVerificationDecision(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerReviewSetVerificationDecisionParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase69() {
	review, err := client.Customers.Review.SetVerificationDecision(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.CustomerReviewSetVerificationDecisionParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase70() {
	paykey, err := client.Paykeys.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase71() {
	paykey, err := client.Paykeys.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyGetParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase72() {
	paykey, err := client.Paykeys.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyListUnmaskedParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase73() {
	paykey, err := client.Paykeys.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyListUnmaskedParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase74() {
	paykey, err := client.Paykeys.List(context.Background(), sdk.PaykeyListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase75() {
	paykey, err := client.Paykeys.List(context.Background(), sdk.PaykeyListParams{
		CreatedFrom:       sdk.F[time.Time](time.Now()),
		CreatedTo:         sdk.F[time.Time](time.Now()),
		CustomerID:        sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		PageNumber:        sdk.F[int64](1),
		PageSize:          sdk.F[int64](100),
		SearchText:        sdk.F[string](""),
		SortBy:            sdk.F[sdk.PaykeyListParamsSortBy](sdk.PaykeyListParamsSortBy("institution_name")),
		SortOrder:         sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		Source:            sdk.F[[]sdk.PaykeySource]([]sdk.PaykeySource{"bank_account"}),
		Status:            sdk.F[[]sdk.PaykeyStatus]([]sdk.PaykeyStatus{"pending"}),
		UnblockEligible:   sdk.F[bool](false),
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase76() {
	paykey, err := client.Paykeys.Reveal(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRevealParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase77() {
	paykey, err := client.Paykeys.Reveal(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRevealParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase78() {
	paykey, err := client.Paykeys.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyCancelParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase79() {
	paykey, err := client.Paykeys.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyCancelParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase80() {
	paykey, err := client.Paykeys.RefreshReview(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRefreshReviewParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase81() {
	paykey, err := client.Paykeys.RefreshReview(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRefreshReviewParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase82() {
	paykey, err := client.Paykeys.RefreshBalance(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRefreshBalanceParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase83() {
	paykey, err := client.Paykeys.RefreshBalance(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyRefreshBalanceParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase84() {
	paykey, err := client.Paykeys.Unblock(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyUnblockParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase85() {
	paykey, err := client.Paykeys.Unblock(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyUnblockParams{
		Message:           sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(paykey)
}

func _smokeCase86() {
	review, err := client.Paykeys.Review.SetVerificationDecision(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyReviewSetVerificationDecisionParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase87() {
	review, err := client.Paykeys.Review.SetVerificationDecision(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyReviewSetVerificationDecisionParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase88() {
	review, err := client.Paykeys.Review.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyReviewListParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase89() {
	review, err := client.Paykeys.Review.List(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PaykeyReviewListParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(review)
}

func _smokeCase90() {
	charge, err := client.Charges.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase91() {
	charge, err := client.Charges.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeGetParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase92() {
	charge, err := client.Charges.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeUpdateParams{
		Amount:      sdk.F[int64](10000),
		Description: sdk.F[string]("Monthly subscription fee"),
		PaymentDate: sdk.F[time.Time](time.Now()),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase93() {
	charge, err := client.Charges.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeUpdateParams{
		Amount:            sdk.F[int64](10000),
		Description:       sdk.F[string]("Monthly subscription fee"),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase94() {
	charge, err := client.Charges.New(context.Background(), sdk.ChargeNewParams{
		Amount:      sdk.F[int64](10000),
		Config:      sdk.F[sdk.ChargeConfigurationParam](sdk.ChargeConfigurationParam{}),
		Currency:    sdk.F[string](""),
		Description: sdk.F[string]("Monthly subscription fee"),
		Device: sdk.F[sdk.PaymentDeviceParam](sdk.PaymentDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		ExternalID:  sdk.F[string](""),
		Paykey:      sdk.F[string](""),
		PaymentDate: sdk.F[time.Time](time.Now()),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase95() {
	charge, err := client.Charges.New(context.Background(), sdk.ChargeNewParams{
		Amount:      sdk.F[int64](10000),
		Config:      sdk.F[sdk.ChargeConfigurationParam](sdk.ChargeConfigurationParam{}),
		Currency:    sdk.F[string](""),
		Description: sdk.F[string]("Monthly subscription fee"),
		Device: sdk.F[sdk.PaymentDeviceParam](sdk.PaymentDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		ExternalID:        sdk.F[string](""),
		Paykey:            sdk.F[string](""),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase96() {
	charge, err := client.Charges.Hold(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeHoldParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase97() {
	charge, err := client.Charges.Hold(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeHoldParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase98() {
	charge, err := client.Charges.Release(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeReleaseParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase99() {
	charge, err := client.Charges.Release(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeReleaseParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase100() {
	charge, err := client.Charges.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeCancelParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase101() {
	charge, err := client.Charges.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeCancelParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase102() {
	charge, err := client.Charges.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeListUnmaskedParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase103() {
	charge, err := client.Charges.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeListUnmaskedParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase104() {
	charge, err := client.Charges.Resubmit(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeResubmitParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase105() {
	charge, err := client.Charges.Resubmit(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeResubmitParams{
		Description:       sdk.F[string](""),
		ExternalID:        sdk.F[string](""),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase106() {
	charge, err := client.Charges.Refund(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeRefundParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase107() {
	charge, err := client.Charges.Refund(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeRefundParams{
		Amount:            sdk.F[int64](5000),
		Description:       sdk.F[string](""),
		ExternalID:        sdk.F[string](""),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase108() {
	charge, err := client.Charges.UploadAuthorizationProof(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeUploadAuthorizationProofParams{
		File: sdk.F[io.Reader](strings.NewReader("")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase109() {
	charge, err := client.Charges.UploadAuthorizationProof(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.ChargeUploadAuthorizationProofParams{
		File:              sdk.F[io.Reader](strings.NewReader("")),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(charge)
}

func _smokeCase110() {
	fundingEvent, err := client.FundingEvents.List(context.Background(), sdk.FundingEventListParams{
		PageNumber: sdk.F[int64](1),
		PageSize:   sdk.F[int64](100),
		SortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase111() {
	fundingEvent, err := client.FundingEvents.List(context.Background(), sdk.FundingEventListParams{
		CreatedFrom:       sdk.F[time.Time](time.Now()),
		CreatedTo:         sdk.F[time.Time](time.Now()),
		Direction:         sdk.F[sdk.TransferDirection](sdk.TransferDirection("deposit")),
		EventType:         sdk.F[sdk.FundingEventType](sdk.FundingEventType("charge_deposit")),
		PageNumber:        sdk.F[int64](1),
		PageSize:          sdk.F[int64](100),
		SearchText:        sdk.F[string](""),
		SortBy:            sdk.F[sdk.FundingEventListParamsSortBy](sdk.FundingEventListParamsSortBy("transfer_date")),
		SortOrder:         sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		Status:            sdk.F[[]sdk.PaymentStatus]([]sdk.PaymentStatus{"created"}),
		StatusReason:      sdk.F[[]sdk.PaymentStatusReason]([]sdk.PaymentStatusReason{"insufficient_funds"}),
		StatusSource:      sdk.F[[]sdk.PaymentStatusSource]([]sdk.PaymentStatusSource{"watchtower"}),
		TraceID:           sdk.F[string](""),
		TraceNumber:       sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase112() {
	fundingEvent, err := client.FundingEvents.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.FundingEventGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase113() {
	fundingEvent, err := client.FundingEvents.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.FundingEventGetParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase114() {
	fundingEvent, err := client.FundingEvents.Simulate(context.Background(), sdk.FundingEventSimulateParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase115() {
	fundingEvent, err := client.FundingEvents.Simulate(context.Background(), sdk.FundingEventSimulateParams{
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase116() {
	fundingEvent, err := client.FundingEvents.ListPayments(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.FundingEventListPaymentsParams{
		DefaultSortOrder: sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		SortOrder:        sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase117() {
	fundingEvent, err := client.FundingEvents.ListPayments(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.FundingEventListPaymentsParams{
		DefaultPageSize:   sdk.F[int64](0),
		DefaultSort:       sdk.F[sdk.FundingEventListPaymentsParamsDefaultSort](sdk.FundingEventListPaymentsParamsDefaultSort("created_at")),
		DefaultSortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		IncludeMetadata:   sdk.F[bool](false),
		PageNumber:        sdk.F[int64](0),
		PageSize:          sdk.F[int64](0),
		SortBy:            sdk.F[sdk.FundingEventListPaymentsParamsSortBy](sdk.FundingEventListPaymentsParamsSortBy("created_at")),
		SortOrder:         sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(fundingEvent)
}

func _smokeCase118() {
	payment, err := client.Payments.List(context.Background(), sdk.PaymentListParams{
		DefaultSort:      sdk.F[sdk.PaymentListParamsDefaultSort](sdk.PaymentListParamsDefaultSort("id")),
		DefaultSortOrder: sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		PageNumber:       sdk.F[int64](1),
		PageSize:         sdk.F[int64](100),
		SortBy:           sdk.F[sdk.PaymentListParamsSortBy](sdk.PaymentListParamsSortBy("id")),
		SortOrder:        sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payment)
}

func _smokeCase119() {
	payment, err := client.Payments.List(context.Background(), sdk.PaymentListParams{
		CustomerID:        sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		DefaultPageSize:   sdk.F[int64](0),
		DefaultSort:       sdk.F[sdk.PaymentListParamsDefaultSort](sdk.PaymentListParamsDefaultSort("id")),
		DefaultSortOrder:  sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		ExternalID:        sdk.F[string](""),
		FundingID:         sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		HasRefund:         sdk.F[bool](false),
		HasResubmit:       sdk.F[bool](false),
		IncludeMetadata:   sdk.F[bool](false),
		IsRefund:          sdk.F[bool](false),
		IsResubmit:        sdk.F[bool](false),
		MaxAmount:         sdk.F[int64](0),
		MaxCreatedAt:      sdk.F[time.Time](time.Now()),
		MaxEffectiveAt:    sdk.F[time.Time](time.Now()),
		MaxPaymentDate:    sdk.F[time.Time](time.Now()),
		MaxUpdatedAt:      sdk.F[time.Time](time.Now()),
		MinAmount:         sdk.F[int64](0),
		MinCreatedAt:      sdk.F[time.Time](time.Now()),
		MinEffectiveAt:    sdk.F[time.Time](time.Now()),
		MinPaymentDate:    sdk.F[time.Time](time.Now()),
		MinUpdatedAt:      sdk.F[time.Time](time.Now()),
		PageNumber:        sdk.F[int64](1),
		PageSize:          sdk.F[int64](100),
		Paykey:            sdk.F[string](""),
		PaykeyID:          sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		PaymentID:         sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
		PaymentStatus:     sdk.F[[]sdk.PaymentStatus]([]sdk.PaymentStatus{"created"}),
		PaymentType:       sdk.F[[]sdk.PaymentType]([]sdk.PaymentType{"charge"}),
		SearchText:        sdk.F[string](""),
		SortBy:            sdk.F[sdk.PaymentListParamsSortBy](sdk.PaymentListParamsSortBy("id")),
		SortOrder:         sdk.F[sdk.SortOrder](sdk.SortOrder("asc")),
		StatusReason:      sdk.F[[]sdk.PaymentStatusReason]([]sdk.PaymentStatusReason{"insufficient_funds"}),
		StatusSource:      sdk.F[[]sdk.PaymentStatusSource]([]sdk.PaymentStatusSource{"watchtower"}),
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payment)
}

func _smokeCase120() {
	payout, err := client.Payouts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase121() {
	payout, err := client.Payouts.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutGetParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase122() {
	payout, err := client.Payouts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutUpdateParams{
		Amount:      sdk.F[int64](10000),
		Description: sdk.F[string](""),
		PaymentDate: sdk.F[time.Time](time.Now()),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase123() {
	payout, err := client.Payouts.Update(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutUpdateParams{
		Amount:            sdk.F[int64](10000),
		Description:       sdk.F[string](""),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase124() {
	payout, err := client.Payouts.New(context.Background(), sdk.PayoutNewParams{
		Amount:      sdk.F[int64](10000),
		Currency:    sdk.F[string](""),
		Description: sdk.F[string]("Vendor invoice payment"),
		Device: sdk.F[sdk.PaymentDeviceParam](sdk.PaymentDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		ExternalID:  sdk.F[string](""),
		Paykey:      sdk.F[string](""),
		PaymentDate: sdk.F[time.Time](time.Now()),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase125() {
	payout, err := client.Payouts.New(context.Background(), sdk.PayoutNewParams{
		Amount:      sdk.F[int64](10000),
		Currency:    sdk.F[string](""),
		Description: sdk.F[string]("Vendor invoice payment"),
		Device: sdk.F[sdk.PaymentDeviceParam](sdk.PaymentDeviceParam{
			IPAddress: sdk.F[string]("192.168.1.1"),
		}),
		ExternalID:        sdk.F[string](""),
		Paykey:            sdk.F[string](""),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		Config:            sdk.F[sdk.PayoutConfigurationParam](sdk.PayoutConfigurationParam{}),
		Metadata:          sdk.F[map[string]string](map[string]string{}),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase126() {
	payout, err := client.Payouts.Hold(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutHoldParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase127() {
	payout, err := client.Payouts.Hold(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutHoldParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase128() {
	payout, err := client.Payouts.Release(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutReleaseParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase129() {
	payout, err := client.Payouts.Release(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutReleaseParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase130() {
	payout, err := client.Payouts.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutCancelParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase131() {
	payout, err := client.Payouts.Cancel(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutCancelParams{
		Reason:            sdk.F[string](""),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase132() {
	payout, err := client.Payouts.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutListUnmaskedParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase133() {
	payout, err := client.Payouts.ListUnmasked(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutListUnmaskedParams{
		CorrelationID:     sdk.F[string](""),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase134() {
	payout, err := client.Payouts.Resubmit(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutResubmitParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase135() {
	payout, err := client.Payouts.Resubmit(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutResubmitParams{
		Description:       sdk.F[string](""),
		ExternalID:        sdk.F[string](""),
		PaymentDate:       sdk.F[time.Time](time.Now()),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase136() {
	payout, err := client.Payouts.UploadAuthorizationProof(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutUploadAuthorizationProofParams{
		File: sdk.F[io.Reader](strings.NewReader("")),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase137() {
	payout, err := client.Payouts.UploadAuthorizationProof(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.PayoutUploadAuthorizationProofParams{
		File:              sdk.F[io.Reader](strings.NewReader("")),
		CorrelationID:     sdk.F[string](""),
		IdempotencyKey:    sdk.F[string]("xxxxxxxxxx"),
		RequestID:         sdk.F[string](""),
		StraddleAccountID: sdk.F[string]("7c9e6679-7425-40de-944b-e07fc1f90ae7"),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(payout)
}

func _smokeCase138() {
	accountSetting, err := client.AccountSettings.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountSettingGetParams{})
	if err != nil {
		panic(err)
	}

	fmt.Println(accountSetting)
}

func _smokeCase139() {
	accountSetting, err := client.AccountSettings.Get(context.Background(), "7c9e6679-7425-40de-944b-e07fc1f90ae7", sdk.AccountSettingGetParams{
		CorrelationID: sdk.F[string](""),
		RequestID:     sdk.F[string](""),
	})
	if err != nil {
		panic(err)
	}

	fmt.Println(accountSetting)
}

var cases = []smokeCase{
	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/accounts/{account_id}",
		Label:     "required params",
		Run:       _smokeCase0,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/accounts/{account_id}",
		Label:     "all params",
		Run:       _smokeCase1,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/accounts/{account_id}",
		Label:     "required params",
		Run:       _smokeCase2,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/accounts/{account_id}",
		Label:     "all params",
		Run:       _smokeCase3,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/accounts",
		Label:     "required params",
		Run:       _smokeCase4,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/accounts",
		Label:     "all params",
		Run:       _smokeCase5,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/accounts",
		Label:     "required params",
		Run:       _smokeCase6,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/accounts",
		Label:     "all params",
		Run:       _smokeCase7,
	},

	{
		Operation: "onboard",
		Method:    "POST",
		Path:      "/v1/accounts/{account_id}/onboard",
		Label:     "required params",
		Run:       _smokeCase8,
	},

	{
		Operation: "onboard",
		Method:    "POST",
		Path:      "/v1/accounts/{account_id}/onboard",
		Label:     "all params",
		Run:       _smokeCase9,
	},

	{
		Operation: "simulateOnboarding",
		Method:    "POST",
		Path:      "/v1/accounts/{account_id}/simulate",
		Label:     "required params",
		Run:       _smokeCase10,
	},

	{
		Operation: "simulateOnboarding",
		Method:    "POST",
		Path:      "/v1/accounts/{account_id}/simulate",
		Label:     "all params",
		Run:       _smokeCase11,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/accounts/{account_id}/capability_requests",
		Label:     "required params",
		Run:       _smokeCase12,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/accounts/{account_id}/capability_requests",
		Label:     "all params",
		Run:       _smokeCase13,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/accounts/{account_id}/capability_requests",
		Label:     "required params",
		Run:       _smokeCase14,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/accounts/{account_id}/capability_requests",
		Label:     "all params",
		Run:       _smokeCase15,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/linked_bank_accounts",
		Label:     "required params",
		Run:       _smokeCase16,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/linked_bank_accounts",
		Label:     "all params",
		Run:       _smokeCase17,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/linked_bank_accounts",
		Label:     "required params",
		Run:       _smokeCase18,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/linked_bank_accounts",
		Label:     "all params",
		Run:       _smokeCase19,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}",
		Label:     "required params",
		Run:       _smokeCase20,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}",
		Label:     "all params",
		Run:       _smokeCase21,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}",
		Label:     "required params",
		Run:       _smokeCase22,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}",
		Label:     "all params",
		Run:       _smokeCase23,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}/unmask",
		Label:     "required params",
		Run:       _smokeCase24,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}/unmask",
		Label:     "all params",
		Run:       _smokeCase25,
	},

	{
		Operation: "cancel",
		Method:    "PATCH",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}/cancel",
		Label:     "required params",
		Run:       _smokeCase26,
	},

	{
		Operation: "cancel",
		Method:    "PATCH",
		Path:      "/v1/linked_bank_accounts/{linked_bank_account_id}/cancel",
		Label:     "all params",
		Run:       _smokeCase27,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/organizations",
		Label:     "required params",
		Run:       _smokeCase28,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/organizations",
		Label:     "all params",
		Run:       _smokeCase29,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/organizations",
		Label:     "required params",
		Run:       _smokeCase30,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/organizations",
		Label:     "all params",
		Run:       _smokeCase31,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/organizations/{organization_id}",
		Label:     "required params",
		Run:       _smokeCase32,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/organizations/{organization_id}",
		Label:     "all params",
		Run:       _smokeCase33,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/representatives",
		Label:     "required params",
		Run:       _smokeCase34,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/representatives",
		Label:     "all params",
		Run:       _smokeCase35,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/representatives",
		Label:     "required params",
		Run:       _smokeCase36,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/representatives",
		Label:     "all params",
		Run:       _smokeCase37,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/representatives/{representative_id}",
		Label:     "required params",
		Run:       _smokeCase38,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/representatives/{representative_id}",
		Label:     "all params",
		Run:       _smokeCase39,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/representatives/{representative_id}",
		Label:     "required params",
		Run:       _smokeCase40,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/representatives/{representative_id}",
		Label:     "all params",
		Run:       _smokeCase41,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/representatives/{representative_id}/unmask",
		Label:     "required params",
		Run:       _smokeCase42,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/representatives/{representative_id}/unmask",
		Label:     "all params",
		Run:       _smokeCase43,
	},

	{
		Operation: "createBankAccountPaykey",
		Method:    "POST",
		Path:      "/v1/bridge/bank_account",
		Label:     "required params",
		Run:       _smokeCase44,
	},

	{
		Operation: "createBankAccountPaykey",
		Method:    "POST",
		Path:      "/v1/bridge/bank_account",
		Label:     "all params",
		Run:       _smokeCase45,
	},

	{
		Operation: "createPlaidPaykey",
		Method:    "POST",
		Path:      "/v1/bridge/plaid",
		Label:     "required params",
		Run:       _smokeCase46,
	},

	{
		Operation: "createPlaidPaykey",
		Method:    "POST",
		Path:      "/v1/bridge/plaid",
		Label:     "all params",
		Run:       _smokeCase47,
	},

	{
		Operation: "createToken",
		Method:    "POST",
		Path:      "/v1/bridge/initialize",
		Label:     "required params",
		Run:       _smokeCase48,
	},

	{
		Operation: "createToken",
		Method:    "POST",
		Path:      "/v1/bridge/initialize",
		Label:     "all params",
		Run:       _smokeCase49,
	},

	{
		Operation: "createQuilttPaykey",
		Method:    "POST",
		Path:      "/v1/bridge/quiltt",
		Label:     "required params",
		Run:       _smokeCase50,
	},

	{
		Operation: "createQuilttPaykey",
		Method:    "POST",
		Path:      "/v1/bridge/quiltt",
		Label:     "all params",
		Run:       _smokeCase51,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/customers/{id}",
		Label:     "required params",
		Run:       _smokeCase52,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/customers/{id}",
		Label:     "all params",
		Run:       _smokeCase53,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/customers/{id}",
		Label:     "required params",
		Run:       _smokeCase54,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/customers/{id}",
		Label:     "all params",
		Run:       _smokeCase55,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/customers/{id}",
		Label:     "required params",
		Run:       _smokeCase56,
	},

	{
		Operation: "delete",
		Method:    "DELETE",
		Path:      "/v1/customers/{id}",
		Label:     "all params",
		Run:       _smokeCase57,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/customers",
		Label:     "required params",
		Run:       _smokeCase58,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/customers",
		Label:     "all params",
		Run:       _smokeCase59,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/customers",
		Label:     "required params",
		Run:       _smokeCase60,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/customers",
		Label:     "all params",
		Run:       _smokeCase61,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/customers/{id}/unmasked",
		Label:     "required params",
		Run:       _smokeCase62,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/customers/{id}/unmasked",
		Label:     "all params",
		Run:       _smokeCase63,
	},

	{
		Operation: "refreshReview",
		Method:    "PUT",
		Path:      "/v1/customers/{id}/refresh_review",
		Label:     "required params",
		Run:       _smokeCase64,
	},

	{
		Operation: "refreshReview",
		Method:    "PUT",
		Path:      "/v1/customers/{id}/refresh_review",
		Label:     "all params",
		Run:       _smokeCase65,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/customers/{id}/review",
		Label:     "required params",
		Run:       _smokeCase66,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/customers/{id}/review",
		Label:     "all params",
		Run:       _smokeCase67,
	},

	{
		Operation: "setVerificationDecision",
		Method:    "PATCH",
		Path:      "/v1/customers/{id}/review",
		Label:     "required params",
		Run:       _smokeCase68,
	},

	{
		Operation: "setVerificationDecision",
		Method:    "PATCH",
		Path:      "/v1/customers/{id}/review",
		Label:     "all params",
		Run:       _smokeCase69,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}",
		Label:     "required params",
		Run:       _smokeCase70,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}",
		Label:     "all params",
		Run:       _smokeCase71,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}/unmasked",
		Label:     "required params",
		Run:       _smokeCase72,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}/unmasked",
		Label:     "all params",
		Run:       _smokeCase73,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/paykeys",
		Label:     "required params",
		Run:       _smokeCase74,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/paykeys",
		Label:     "all params",
		Run:       _smokeCase75,
	},

	{
		Operation: "reveal",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}/reveal",
		Label:     "required params",
		Run:       _smokeCase76,
	},

	{
		Operation: "reveal",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}/reveal",
		Label:     "all params",
		Run:       _smokeCase77,
	},

	{
		Operation: "cancel",
		Method:    "PUT",
		Path:      "/v1/paykeys/{id}/cancel",
		Label:     "required params",
		Run:       _smokeCase78,
	},

	{
		Operation: "cancel",
		Method:    "PUT",
		Path:      "/v1/paykeys/{id}/cancel",
		Label:     "all params",
		Run:       _smokeCase79,
	},

	{
		Operation: "refreshReview",
		Method:    "PUT",
		Path:      "/v1/paykeys/{id}/refresh_review",
		Label:     "required params",
		Run:       _smokeCase80,
	},

	{
		Operation: "refreshReview",
		Method:    "PUT",
		Path:      "/v1/paykeys/{id}/refresh_review",
		Label:     "all params",
		Run:       _smokeCase81,
	},

	{
		Operation: "refreshBalance",
		Method:    "PUT",
		Path:      "/v1/paykeys/{id}/refresh_balance",
		Label:     "required params",
		Run:       _smokeCase82,
	},

	{
		Operation: "refreshBalance",
		Method:    "PUT",
		Path:      "/v1/paykeys/{id}/refresh_balance",
		Label:     "all params",
		Run:       _smokeCase83,
	},

	{
		Operation: "unblock",
		Method:    "PATCH",
		Path:      "/v1/paykeys/{id}/unblock",
		Label:     "required params",
		Run:       _smokeCase84,
	},

	{
		Operation: "unblock",
		Method:    "PATCH",
		Path:      "/v1/paykeys/{id}/unblock",
		Label:     "all params",
		Run:       _smokeCase85,
	},

	{
		Operation: "setVerificationDecision",
		Method:    "PATCH",
		Path:      "/v1/paykeys/{id}/review",
		Label:     "required params",
		Run:       _smokeCase86,
	},

	{
		Operation: "setVerificationDecision",
		Method:    "PATCH",
		Path:      "/v1/paykeys/{id}/review",
		Label:     "all params",
		Run:       _smokeCase87,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}/review",
		Label:     "required params",
		Run:       _smokeCase88,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/paykeys/{id}/review",
		Label:     "all params",
		Run:       _smokeCase89,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/charges/{id}",
		Label:     "required params",
		Run:       _smokeCase90,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/charges/{id}",
		Label:     "all params",
		Run:       _smokeCase91,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/charges/{id}",
		Label:     "required params",
		Run:       _smokeCase92,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/charges/{id}",
		Label:     "all params",
		Run:       _smokeCase93,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/charges",
		Label:     "required params",
		Run:       _smokeCase94,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/charges",
		Label:     "all params",
		Run:       _smokeCase95,
	},

	{
		Operation: "hold",
		Method:    "PUT",
		Path:      "/v1/charges/{id}/hold",
		Label:     "required params",
		Run:       _smokeCase96,
	},

	{
		Operation: "hold",
		Method:    "PUT",
		Path:      "/v1/charges/{id}/hold",
		Label:     "all params",
		Run:       _smokeCase97,
	},

	{
		Operation: "release",
		Method:    "PUT",
		Path:      "/v1/charges/{id}/release",
		Label:     "required params",
		Run:       _smokeCase98,
	},

	{
		Operation: "release",
		Method:    "PUT",
		Path:      "/v1/charges/{id}/release",
		Label:     "all params",
		Run:       _smokeCase99,
	},

	{
		Operation: "cancel",
		Method:    "PUT",
		Path:      "/v1/charges/{id}/cancel",
		Label:     "required params",
		Run:       _smokeCase100,
	},

	{
		Operation: "cancel",
		Method:    "PUT",
		Path:      "/v1/charges/{id}/cancel",
		Label:     "all params",
		Run:       _smokeCase101,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/charges/{id}/unmask",
		Label:     "required params",
		Run:       _smokeCase102,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/charges/{id}/unmask",
		Label:     "all params",
		Run:       _smokeCase103,
	},

	{
		Operation: "resubmit",
		Method:    "POST",
		Path:      "/v1/charges/{id}/resubmit",
		Label:     "required params",
		Run:       _smokeCase104,
	},

	{
		Operation: "resubmit",
		Method:    "POST",
		Path:      "/v1/charges/{id}/resubmit",
		Label:     "all params",
		Run:       _smokeCase105,
	},

	{
		Operation: "refund",
		Method:    "POST",
		Path:      "/v1/charges/{id}/refund",
		Label:     "required params",
		Run:       _smokeCase106,
	},

	{
		Operation: "refund",
		Method:    "POST",
		Path:      "/v1/charges/{id}/refund",
		Label:     "all params",
		Run:       _smokeCase107,
	},

	{
		Operation: "uploadAuthorizationProof",
		Method:    "POST",
		Path:      "/v1/charges/{id}/authorization",
		Label:     "required params",
		Run:       _smokeCase108,
	},

	{
		Operation: "uploadAuthorizationProof",
		Method:    "POST",
		Path:      "/v1/charges/{id}/authorization",
		Label:     "all params",
		Run:       _smokeCase109,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/funding_events",
		Label:     "required params",
		Run:       _smokeCase110,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/funding_events",
		Label:     "all params",
		Run:       _smokeCase111,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/funding_events/{id}",
		Label:     "required params",
		Run:       _smokeCase112,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/funding_events/{id}",
		Label:     "all params",
		Run:       _smokeCase113,
	},

	{
		Operation: "simulate",
		Method:    "POST",
		Path:      "/v1/funding_events/simulate",
		Label:     "required params",
		Run:       _smokeCase114,
	},

	{
		Operation: "simulate",
		Method:    "POST",
		Path:      "/v1/funding_events/simulate",
		Label:     "all params",
		Run:       _smokeCase115,
	},

	{
		Operation: "listPayments",
		Method:    "GET",
		Path:      "/v1/funding_event_payments/{id}",
		Label:     "required params",
		Run:       _smokeCase116,
	},

	{
		Operation: "listPayments",
		Method:    "GET",
		Path:      "/v1/funding_event_payments/{id}",
		Label:     "all params",
		Run:       _smokeCase117,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/payments",
		Label:     "required params",
		Run:       _smokeCase118,
	},

	{
		Operation: "list",
		Method:    "GET",
		Path:      "/v1/payments",
		Label:     "all params",
		Run:       _smokeCase119,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/payouts/{id}",
		Label:     "required params",
		Run:       _smokeCase120,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/payouts/{id}",
		Label:     "all params",
		Run:       _smokeCase121,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}",
		Label:     "required params",
		Run:       _smokeCase122,
	},

	{
		Operation: "update",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}",
		Label:     "all params",
		Run:       _smokeCase123,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/payouts",
		Label:     "required params",
		Run:       _smokeCase124,
	},

	{
		Operation: "create",
		Method:    "POST",
		Path:      "/v1/payouts",
		Label:     "all params",
		Run:       _smokeCase125,
	},

	{
		Operation: "hold",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}/hold",
		Label:     "required params",
		Run:       _smokeCase126,
	},

	{
		Operation: "hold",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}/hold",
		Label:     "all params",
		Run:       _smokeCase127,
	},

	{
		Operation: "release",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}/release",
		Label:     "required params",
		Run:       _smokeCase128,
	},

	{
		Operation: "release",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}/release",
		Label:     "all params",
		Run:       _smokeCase129,
	},

	{
		Operation: "cancel",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}/cancel",
		Label:     "required params",
		Run:       _smokeCase130,
	},

	{
		Operation: "cancel",
		Method:    "PUT",
		Path:      "/v1/payouts/{id}/cancel",
		Label:     "all params",
		Run:       _smokeCase131,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/payouts/{id}/unmask",
		Label:     "required params",
		Run:       _smokeCase132,
	},

	{
		Operation: "listUnmasked",
		Method:    "GET",
		Path:      "/v1/payouts/{id}/unmask",
		Label:     "all params",
		Run:       _smokeCase133,
	},

	{
		Operation: "resubmit",
		Method:    "POST",
		Path:      "/v1/payouts/{id}/resubmit",
		Label:     "required params",
		Run:       _smokeCase134,
	},

	{
		Operation: "resubmit",
		Method:    "POST",
		Path:      "/v1/payouts/{id}/resubmit",
		Label:     "all params",
		Run:       _smokeCase135,
	},

	{
		Operation: "uploadAuthorizationProof",
		Method:    "POST",
		Path:      "/v1/payouts/{id}/authorization",
		Label:     "required params",
		Run:       _smokeCase136,
	},

	{
		Operation: "uploadAuthorizationProof",
		Method:    "POST",
		Path:      "/v1/payouts/{id}/authorization",
		Label:     "all params",
		Run:       _smokeCase137,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/account_settings/{account_id}",
		Label:     "required params",
		Run:       _smokeCase138,
	},

	{
		Operation: "retrieve",
		Method:    "GET",
		Path:      "/v1/account_settings/{account_id}",
		Label:     "all params",
		Run:       _smokeCase139,
	},
}

func selectedCases() []smokeCase {
	filter := os.Getenv("SCALAR_SMOKE_FILTER")
	if filter == "" {
		return cases
	}
	needles := strings.Split(filter, ",")
	selected := make([]smokeCase, 0, len(cases))
	for _, testCase := range cases {
		for _, needle := range needles {
			needle = strings.TrimSpace(needle)
			if needle == "" {
				continue
			}
			if strings.Contains(testCase.Operation, needle) || strings.Contains(testCase.Path, needle) {
				selected = append(selected, testCase)
				break
			}
		}
	}
	return selected
}

func runCase(testCase smokeCase) (result smokeResult) {
	startedAt := time.Now()
	result = smokeResult{
		Operation: testCase.Operation,
		Method:    testCase.Method,
		Path:      testCase.Path,
		Label:     testCase.Label,
		Status:    "passed",
	}
	defer func() {
		result.DurationMs = time.Since(startedAt).Milliseconds()
		if recovered := recover(); recovered != nil {
			result.Status = "failed"
			result.Error = fmt.Sprint(recovered)
		}
	}()
	testCase.Run()
	return result
}

func main() {
	selected := selectedCases()
	results := make([]smokeResult, len(selected))
	var wg sync.WaitGroup
	for index, testCase := range selected {
		wg.Add(1)
		go func(index int, testCase smokeCase) {
			defer wg.Done()
			results[index] = runCase(testCase)
		}(index, testCase)
	}
	wg.Wait()

	failed := 0
	for _, result := range results {
		if result.Status == "failed" {
			failed++
		}
	}

	report := map[string]interface{}{"total": len(results), "failed": failed, "results": results}
	if reportPath := os.Getenv("SCALAR_SMOKE_REPORT"); reportPath != "" {
		bytes, err := json.Marshal(report)
		if err != nil {
			panic(err)
		}
		if err := os.WriteFile(reportPath, bytes, 0o644); err != nil {
			panic(err)
		}
	} else {
		for _, result := range results {
			suffix := ""
			if result.Label != "" {
				suffix = " [" + result.Label + "]"
			}
			if result.Status == "passed" {
				fmt.Printf("PASS %s%s (%s %s) %dms\n", result.Operation, suffix, result.Method, result.Path, result.DurationMs)
			} else {
				fmt.Fprintf(os.Stderr, "FAIL %s%s (%s %s)\n%s\n", result.Operation, suffix, result.Method, result.Path, result.Error)
			}
		}
		if len(results) == 0 {
			fmt.Fprintln(os.Stderr, "No code samples ran (empty SDK or a SCALAR_SMOKE_FILTER that matched nothing).")
		} else {
			fmt.Printf("\n%d/%d samples passed\n", len(results)-failed, len(results))
		}
	}

	if failed > 0 || len(results) == 0 {
		os.Exit(1)
	}
}
